import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { parseYAML } from "@intentius/chant/yaml";
import { init } from "../src/init";
import { migrationFiles, migrationPipelineProblems, runMigrations } from "../src/migrate";
import { PIPELINE_PATHS, renderPipeline } from "../src/render";
import { tmp, twoRootRepo, write } from "./helpers";

const doc = (text: string): Record<string, any> => parseYAML(text.split("\n").filter((l) => !l.startsWith("#")).join("\n")) as Record<string, any>;
/** Each apply job's `permissions.contents`, by job name. */
const applyContents = (text: string): Record<string, string> =>
  Object.fromEntries(Object.entries(doc(text).jobs as Record<string, { permissions?: { contents?: string } }>).filter(([n]) => /^apply/.test(n)).map(([n, j]) => [n, j.permissions?.contents ?? ""]));
const MIGRATION = "moves:\n  - from: network\n    to: app\n    addresses: [aws_s3_bucket.logs]\n";

describe("the pipeline of a repo that carries migrations", () => {
  const input = { binary: "tofu" as const, version: "1.13.1", image: "img:1", layers: [["network"], ["app"]], env: {}, gate: "never" as const };

  it("on GitHub under gate: never, gives the apply jobs contents: write only when the repo has migration files", () => {
    const plain = applyContents(renderPipeline({ ...input, forge: "github" }).content);
    const migrating = applyContents(renderPipeline({ ...input, forge: "github", migrations: true }).content);
    expect(Object.keys(plain).length).toBeGreaterThan(1);
    expect(new Set(Object.values(plain))).toEqual(new Set(["read"]));
    expect(Object.keys(migrating)).toEqual(Object.keys(plain));
    expect(new Set(Object.values(migrating))).toEqual(new Set(["write"]));
    // Under a gate that can hold a wave the apply jobs write already, migrations or not.
    expect(renderPipeline({ ...input, forge: "github", gate: "always", migrations: true }).content).toBe(renderPipeline({ ...input, forge: "github", gate: "always" }).content);
  });

  it("on Forgejo, is the pipeline it was", () => {
    expect(renderPipeline({ ...input, forge: "forgejo", migrations: true }).content).toBe(renderPipeline({ ...input, forge: "forgejo" }).content);
  });

  it("init finds the migration files as the plan job does, and writes the GitHub pipeline with write", async () => {
    const dir = write(twoRootRepo(), { "terragucci.yml": "forge: github\ngate: never\n" });
    const before = await init(dir, { binary: "tofu", dryRun: true });
    expect(new Set(Object.values(applyContents(before.files.find((f) => f.path.endsWith(PIPELINE_PATHS.github))!.content)))).toEqual(new Set(["read"]));
    write(dir, { "migrations/move-logs.yml": MIGRATION, "migrations/notes.md": "not a migration" });
    expect(migrationFiles(dir)).toEqual(["migrations/move-logs.yml"]);
    const after = await init(dir, { binary: "tofu", dryRun: true });
    expect(new Set(Object.values(applyContents(after.files.find((f) => f.path.endsWith(PIPELINE_PATHS.github))!.content)))).toEqual(new Set(["write"]));
  });
});

describe("a pipeline that cannot run its migrations", () => {
  async function repo(withMigration: boolean): Promise<string> {
    const dir = write(twoRootRepo(), { "terragucci.yml": "forge: github\ngate: never\n" });
    await init(dir, { binary: "tofu" });
    if (withMigration) write(dir, { "migrations/move-logs.yml": MIGRATION });
    return dir;
  }

  it("is a config check problem naming the read-only apply jobs and terragucci init, until init writes the pipeline again", async () => {
    const dir = await repo(true);
    const problems = migrationPipelineProblems(dir);
    expect(problems).toHaveLength(1);
    expect(problems[0]).toMatch(/^migrations\/ holds a migration \(migrations\/move-logs\.yml\), and in \.github\/workflows\/terragucci\.yml apply-comment, apply-wave-1, apply-wave-2 may not write chant\/lifecycle, where a migration waits for its approval; run terragucci init to write the pipeline again$/);
    await init(dir, { binary: "tofu" });
    expect(migrationPipelineProblems(dir)).toEqual([]);
  });

  it("is no problem with no migration files, or with a pipeline terragucci did not write", async () => {
    expect(migrationPipelineProblems(await repo(false))).toEqual([]);
    const own = await repo(true);
    const path = join(own, PIPELINE_PATHS.github);
    writeFileSync(path, readFileSync(path, "utf-8").replace(/^# Generated by terragucci\./, "# ours"));
    expect(migrationPipelineProblems(own)).toEqual([]);
    expect(migrationPipelineProblems(write(tmp(), { "migrations/m.yml": MIGRATION }))).toEqual([]);
  });

  it("fails the pull request's plan before any migration is read", async () => {
    const lines: string[] = [];
    const r = await runMigrations(await repo(true), { binary: "tofu", planOnly: true, log: (l) => void lines.push(l), exec: async () => ({ code: 1, stdout: "", out: "no binary should run" }) });
    expect(r).toEqual({ code: 1, records: [] });
    expect(lines.join("\n")).toContain("run terragucci init to write the pipeline again");
  });
});
