import { spawnSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { decideApplyComment, decidePlanLock, mergePullRequest, reachedUnits, type Git } from "../src/comment-apply";
import type { Fetch } from "../src/forge";
import { describeHeld, LOCKS_PATH, parseLocks, readLocks, releaseLocks, takeLocks } from "../src/locks";
import { backend, git, tmp, write } from "./helpers";

const layers = [["network"], ["app"]];
const commit = (dir: string, m: string): string => {
  git(dir, "add", "-A");
  git(dir, "-c", "user.name=t", "-c", "user.email=t@t", "-c", "commit.gpgsign=false", "commit", "-q", "--allow-empty", "-m", m);
  return git(dir, "rev-parse", "HEAD").trim();
};

/**
 * origin with main (two roots) and a branch `feature` that changes network,
 * and a checkout of main, as the comment's job has it. `behind` moves main on
 * after the branch was cut; `pipeline` makes the branch change the pipeline.
 */
function repos(o: { behind?: boolean; pipeline?: boolean } = {}): { work: string; origin: string; head: string; git: Git } {
  const dir = tmp("tg-pr-apply-");
  const origin = join(dir, "origin.git");
  git(dir, "init", "-q", "--bare", "-b", "main", origin);
  const work = join(dir, "work");
  git(dir, "init", "-q", "-b", "main", work);
  git(work, "remote", "add", "origin", origin);
  write(work, { "network/main.tf": backend("network"), "app/main.tf": backend("app"), ".github/workflows/terragucci.yml": "# Generated by terragucci.\n" });
  commit(work, "base");
  git(work, "push", "-q", "origin", "main");
  git(work, "checkout", "-q", "-b", "feature");
  write(work, { "network/extra.tf": "# a change\n", ...(o.pipeline ? { ".github/workflows/terragucci.yml": "# edited\n" } : {}) });
  const head = commit(work, "change network");
  git(work, "push", "-q", "origin", "feature");
  git(work, "checkout", "-q", "main");
  if (o.behind) {
    write(work, { "app/later.tf": "# later\n" });
    commit(work, "later on main");
    git(work, "push", "-q", "origin", "main");
    git(work, "reset", "-q", "--hard", "HEAD~1");
  }
  return { work, origin, head, git: (args) => spawnSync("git", args, { cwd: work, encoding: "utf-8" }) as ReturnType<Git> };
}

interface Sent { method: string; path: string; body?: any }

const OPEN = (head: string, extra: Record<string, unknown> = {}) => ({
  state: "open", merged: false, mergeable: true, mergeable_state: "clean", number: 7, user: { login: "author" },
  head: { sha: head, ref: "feature", repo: { full_name: "acme/infra" } }, base: { ref: "main" }, ...extra,
});

interface Forge {
  pr: any;
  reviews?: unknown[];
  statuses?: unknown[];
  checkRuns?: unknown[];
  permission?: Record<string, string>;
  others?: Record<number, string>;
  /** Answers to the later reads of pull request 7, one each, the last repeated; the first read answers `pr`. */
  later?: any[];
}

function setup(comment: string, f: Forge, forgejo = false): { env: NodeJS.ProcessEnv; fetch: Fetch; sent: Sent[] } {
  const dir = tmp("tg-pr-apply-event-");
  const file = join(dir, "event.json");
  writeFileSync(file, JSON.stringify({
    action: "created",
    comment: { body: comment, user: { login: "dev" } },
    issue: { number: 7, pull_request: {} },
    repository: { full_name: "acme/infra", default_branch: "main", ...(forgejo ? { permissions: { push: true, admin: false } } : {}) },
    ...(forgejo ? { sender: { login: "dev" } } : {}),
  }));
  const sent: Sent[] = [];
  const fetch: Fetch = async (url, init) => {
    const path = url.replace("https://forge.test/api/v1/", "");
    sent.push({ method: init?.method ?? "GET", path, body: init?.body ? JSON.parse(init.body) : undefined });
    const answer = (status: number, json: unknown) => ({ ok: status < 300, status, json: async () => json, text: async () => JSON.stringify(json) });
    const perm = /collaborators\/([^/]+)\/permission/.exec(path);
    if (perm) return answer(200, { permission: f.permission?.[decodeURIComponent(perm[1]!)] ?? "write" }) as never;
    if (path.includes("/reviews")) return answer(200, f.reviews ?? []) as never;
    if (path.endsWith("/status")) return answer(200, { statuses: f.statuses ?? [] }) as never;
    if (path.includes("/check-runs")) return answer(200, { check_runs: f.checkRuns ?? [] }) as never;
    const other = /pulls\/(\d+)$/.exec(path);
    if (other && Number(other[1]) !== 7) return answer(200, { state: f.others?.[Number(other[1])] ?? "closed" }) as never;
    if (path.endsWith("pulls/7")) {
      const reads = sent.filter((x) => x.path.endsWith("pulls/7")).length;
      return answer(200, reads === 1 || !f.later?.length ? f.pr : f.later[Math.min(reads - 2, f.later.length - 1)]) as never;
    }
    return answer(201, {}) as never;
  };
  return { env: { GITHUB_EVENT_PATH: file, GITHUB_REPOSITORY: "acme/infra", GITHUB_API_URL: "https://forge.test/api/v1", TG_TOKEN: "t" }, fetch, sent };
}

const replies = (s: { sent: Sent[] }): string[] => s.sent.filter((x) => x.method === "POST" && x.path.endsWith("/comments")).map((x) => x.body.body as string);
const approved = (head: string, by = "rev") => [{ user: { login: by }, state: "APPROVED", commit_id: head }];
const GREEN = [{ id: 1, context: "terragucci/plan", state: "success" }, { id: 2, context: "terragucci / check (push)", state: "success" }];

describe("apply.when: pull-request, an open pull request", () => {
  const decide = (r: ReturnType<typeof repos>, s: ReturnType<typeof setup>, forge?: "forgejo", requires?: ("approved" | "mergeable" | "undiverged" | "checks")[]) =>
    decideApplyComment({ layers, env: s.env, fetch: s.fetch, git: r.git, repo: r.work, when: "pull-request", wait: async () => {}, ...(forge ? { forge } : {}), ...(requires ? { requires } : {}) });

  it("applies the head once it is approved, green and up to date, and locks the roots it reaches", async () => {
    const r = repos();
    const s = setup("/terragucci apply", { pr: OPEN(r.head), reviews: approved(r.head), statuses: GREEN });
    const d = await decide(r, s);
    expect(d).toMatchObject({ go: true, open: true, pr: 7, sha: r.head, base: "main" });
    expect(replies(s)).toEqual([]);
    // network changed, and app reads nothing, so network alone is locked.
    expect(readLocks(r.work).locks).toEqual({ network: expect.objectContaining({ pr: 7, by: "dev", head: r.head }) });
  });

  it("with apply.when merge, an open pull request is still refused", async () => {
    const r = repos();
    const s = setup("/terragucci apply", { pr: OPEN(r.head), reviews: approved(r.head), statuses: GREEN });
    const d = await decideApplyComment({ layers, env: s.env, fetch: s.fetch, git: r.git, repo: r.work });
    expect(d.go).toBe(false);
    expect(replies(s)[0]).toContain("pull request 7 is not merged");
  });

  it("refuses a head with no approval, one approved by its author only, and one approved on an older commit", async () => {
    for (const reviews of [[], approved("a".repeat(40), "rev"), [{ user: { login: "author" }, state: "APPROVED", commit_id: "" }]]) {
      const r = repos();
      const s = setup("/terragucci apply", { pr: OPEN(r.head), reviews, statuses: GREEN });
      expect((await decide(r, s)).go).toBe(false);
      expect(replies(s)[0]).toContain("pull request 7 is not approved");
      expect(readLocks(r.work).locks).toEqual({});
    }
  });

  it("refuses when a reviewer's latest review asks for changes, and counts no approval from someone without write access", async () => {
    const r = repos();
    const changes = setup("/terragucci apply", { pr: OPEN(r.head), reviews: [...approved(r.head), { user: { login: "sam" }, state: "CHANGES_REQUESTED", commit_id: r.head }], statuses: GREEN });
    expect((await decide(r, changes)).go).toBe(false);
    expect(replies(changes)[0]).toContain("sam asked for changes");
    const reader = setup("/terragucci apply", { pr: OPEN(r.head), reviews: approved(r.head, "visitor"), statuses: GREEN, permission: { visitor: "read" } });
    expect((await decide(r, reader)).go).toBe(false);
    expect(replies(reader)[0]).toContain("not approved");
  });

  it("refuses failing or running checks by name, and a head whose plan has not passed", async () => {
    const r = repos();
    const failing = setup("/terragucci apply", { pr: OPEN(r.head), reviews: approved(r.head), statuses: [...GREEN, { id: 3, context: "lint", state: "failure" }] });
    expect((await decide(r, failing)).go).toBe(false);
    expect(replies(failing)[0]).toContain("lint failed");
    const running = setup("/terragucci apply", { pr: OPEN(r.head), reviews: approved(r.head), statuses: GREEN, checkRuns: [{ name: "build", status: "in_progress" }] });
    expect((await decide(r, running)).go).toBe(false);
    expect(replies(running)[0]).toContain("build still running");
    const noPlan = setup("/terragucci apply", { pr: OPEN(r.head), reviews: approved(r.head), statuses: [] });
    expect((await decide(r, noPlan)).go).toBe(false);
    expect(replies(noPlan)[0]).toContain("the plan of pull request 7 has not passed");
    // The apply's own status never holds it back, and a newer status of a context replaces an older one.
    const own = setup("/terragucci apply", { pr: OPEN(r.head), reviews: approved(r.head), statuses: [...GREEN, { id: 4, context: "terragucci/apply", state: "failure" }, { id: 5, context: "lint", state: "failure" }, { id: 6, context: "lint", state: "success" }] });
    expect((await decide(r, own)).go).toBe(true);
  });

  it("forgejo: reads a status's state from status, and an unofficial approval does not count", async () => {
    const r = repos();
    const s = setup("/terragucci apply", { pr: OPEN(r.head), reviews: [{ user: { login: "rev" }, state: "APPROVED", commit_id: r.head, official: false }], statuses: [{ id: 1, context: "terragucci/plan", status: "success" }] }, true);
    expect((await decide(r, s, "forgejo")).go).toBe(false);
    const ok = setup("/terragucci apply", { pr: OPEN(r.head), reviews: [{ user: { login: "rev" }, state: "APPROVED", commit_id: r.head, official: true }], statuses: [{ id: 1, context: "terragucci/plan", status: "success" }] }, true);
    expect((await decide(r, ok, "forgejo")).go).toBe(true);
    expect(ok.sent.some((x) => x.path.includes("check-runs"))).toBe(false);
  });

  it("refuses a head that is not up to date with the default branch, and names both commits", async () => {
    const r = repos({ behind: true });
    const s = setup("/terragucci apply", { pr: OPEN(r.head), reviews: approved(r.head), statuses: GREEN });
    const d = await decide(r, s);
    expect(d.go).toBe(false);
    expect(replies(s)[0]).toMatch(/pull request 7 is not up to date with main: its head [0-9a-f]{8} does not contain [0-9a-f]{8}/);
    expect(readLocks(r.work).locks).toEqual({});
  });

  it("refuses a pull request that changes the pipeline, a fork's, and one whose head moved", async () => {
    const pipe = repos({ pipeline: true });
    const s = setup("/terragucci apply", { pr: OPEN(pipe.head), reviews: approved(pipe.head), statuses: GREEN });
    expect((await decide(pipe, s)).go).toBe(false);
    expect(replies(s)[0]).toContain("changes .github/workflows/terragucci.yml");
    const r = repos();
    const fork = setup("/terragucci apply", { pr: OPEN(r.head, { head: { sha: r.head, ref: "feature", repo: { full_name: "evil/infra" } } }) });
    expect((await decide(r, fork)).go).toBe(false);
    expect(replies(fork)[0]).toContain("fork");
    const other = "b".repeat(40);
    const moved = setup("/terragucci apply", { pr: OPEN(other), reviews: approved(other), statuses: GREEN });
    expect((await decide(r, moved)).go).toBe(false);
    expect(replies(moved)[0]).toContain("moved while this comment was read");
  });

  it("refuses a root another open pull request holds, names it, and takes over a lock whose holder closed", async () => {
    const r = repos();
    await takeLocks(r.work, ["network"], { pr: 3, by: "erin", at: "2026-10-07T00:00:00.000Z", head: "c".repeat(40) }, async () => true);
    const held = setup("/terragucci apply", { pr: OPEN(r.head), reviews: approved(r.head), statuses: GREEN, others: { 3: "open" } });
    expect((await decide(r, held)).go).toBe(false);
    expect(replies(held)[0]).toContain("`network` is locked by pull request 3 (applied by erin)");
    expect(readLocks(r.work).locks.network?.pr).toBe(3);
    const closed = setup("/terragucci apply", { pr: OPEN(r.head), reviews: approved(r.head), statuses: GREEN, others: { 3: "closed" } });
    expect((await decide(r, closed)).go).toBe(true);
    expect(readLocks(r.work).locks.network?.pr).toBe(7);
  });

  it("/terragucci unlock releases the pull request's locks for someone with write access, and is refused under apply.when merge", async () => {
    const r = repos();
    await takeLocks(r.work, ["network", "app"], { pr: 7, by: "dev", at: "2026-10-07T00:00:00.000Z", head: r.head }, async () => true);
    const s = setup("/terragucci unlock", { pr: OPEN(r.head) });
    const d = await decide(r, s);
    expect(d.go).toBe(false);
    expect(replies(s)[0]).toContain("released the locks pull request 7 held on `app`, `network`");
    expect(readLocks(r.work).locks).toEqual({});
    const again = setup("/terragucci unlock", { pr: OPEN(r.head) });
    await decide(r, again);
    expect(replies(again)[0]).toContain("pull request 7 holds no lock");
    const merge = setup("/terragucci unlock", { pr: OPEN(r.head) });
    await decideApplyComment({ layers, env: merge.env, fetch: merge.fetch, git: r.git, repo: r.work });
    expect(replies(merge)[0]).toContain("there is nothing to unlock");
  });

  it("apply.requires: an approved head behind the default branch applies with [approved], and the default refuses it", async () => {
    const r = repos({ behind: true });
    const only = setup("/terragucci apply", { pr: OPEN(r.head), reviews: approved(r.head), statuses: GREEN });
    expect(await decide(r, only, undefined, ["approved"])).toMatchObject({ go: true, open: true, sha: r.head });
    const r2 = repos({ behind: true });
    const all = setup("/terragucci apply", { pr: OPEN(r2.head), reviews: approved(r2.head), statuses: GREEN });
    expect((await decide(r2, all)).go).toBe(false);
    expect(replies(all)[0]).toContain("is not up to date with main");
  });

  it("apply.requires: without approved no review is read, without checks a failed check does not hold it, and the plan must pass either way", async () => {
    const r = repos();
    const noReview = setup("/terragucci apply", { pr: OPEN(r.head), reviews: [], statuses: GREEN });
    expect((await decide(r, noReview, undefined, ["mergeable", "undiverged", "checks"])).go).toBe(true);
    expect(noReview.sent.some((x) => x.path.includes("/reviews"))).toBe(false);
    const r2 = repos();
    const red = setup("/terragucci apply", { pr: OPEN(r2.head), reviews: approved(r2.head), statuses: [...GREEN, { id: 3, context: "lint", state: "failure" }] });
    expect((await decide(r2, red, undefined, ["approved"])).go).toBe(true);
    const r3 = repos();
    const noPlan = setup("/terragucci apply", { pr: OPEN(r3.head), reviews: [], statuses: [] });
    expect((await decide(r3, noPlan, undefined, [])).go).toBe(false);
    expect(replies(noPlan)[0]).toContain("the plan of pull request 7 has not passed");
  });

  it("mergeable: refuses a pull request the forge reports conflicts on, and one branch protection blocks on GitHub", async () => {
    const r = repos();
    const conflict = setup("/terragucci apply", { pr: OPEN(r.head, { mergeable: false, mergeable_state: "dirty" }), reviews: approved(r.head), statuses: GREEN });
    expect((await decide(r, conflict)).go).toBe(false);
    expect(replies(conflict)[0]).toContain("pull request 7 is not mergeable: the forge reports conflicts with main");
    expect(readLocks(r.work).locks).toEqual({});
    const blocked = setup("/terragucci apply", { pr: OPEN(r.head, { mergeable_state: "blocked" }), reviews: approved(r.head), statuses: GREEN });
    expect((await decide(r, blocked)).go).toBe(false);
    expect(replies(blocked)[0]).toContain("branch protection on main blocks its merge");
    // Forgejo has no mergeable_state, and behind is left to undiverged.
    const behind = setup("/terragucci apply", { pr: OPEN(r.head, { mergeable_state: "behind" }), reviews: approved(r.head), statuses: GREEN });
    expect((await decide(r, behind)).go).toBe(true);
    const r2 = repos();
    const off = setup("/terragucci apply", { pr: OPEN(r2.head, { mergeable: false, mergeable_state: "dirty" }), reviews: approved(r2.head), statuses: GREEN });
    expect((await decide(r2, off, undefined, ["approved", "undiverged", "checks"])).go).toBe(true);
  });

  it("mergeable: reads the pull request again while the forge is still checking it, and refuses when it never says", async () => {
    const r = repos();
    const later = setup("/terragucci apply", { pr: OPEN(r.head, { mergeable: null, mergeable_state: "unknown" }), later: [OPEN(r.head, { mergeable: null }), OPEN(r.head)], reviews: approved(r.head), statuses: GREEN });
    expect((await decide(r, later)).go).toBe(true);
    expect(later.sent.filter((x) => x.path.endsWith("pulls/7")).length).toBe(3);
    const r2 = repos();
    const never = setup("/terragucci apply", { pr: OPEN(r2.head, { mergeable: null }), reviews: approved(r2.head), statuses: GREEN });
    expect((await decide(r2, never)).go).toBe(false);
    expect(replies(never)[0]).toContain("the forge has not worked out whether pull request 7 can merge");
    const r3 = repos();
    const checking = setup("/terragucci apply", { pr: OPEN(r3.head, { mergeable: false }), later: [OPEN(r3.head)], reviews: [{ user: { login: "rev" }, state: "APPROVED", commit_id: r3.head }], statuses: [{ id: 1, context: "terragucci/plan", status: "success" }] }, true);
    expect((await decide(r3, checking, "forgejo")).go).toBe(true);
  });

  it("/terragucci lock locks the roots the pull request reaches and applies nothing; a second pull request is refused naming the holder", async () => {
    const r = repos();
    const s = setup("/terragucci lock", { pr: OPEN(r.head) });
    const d = await decide(r, s);
    expect(d.go).toBe(false);
    expect(d.fail).toBeUndefined();
    expect(replies(s)[0]).toContain("locked `network` for pull request 7");
    expect(replies(s)[0]).toContain("nothing was applied");
    // A lock needs no approval and no green checks.
    expect(s.sent.some((x) => x.path.includes("/reviews") || x.path.endsWith("/status"))).toBe(false);
    expect(readLocks(r.work).locks).toEqual({ network: expect.objectContaining({ pr: 7, by: "dev", head: r.head, via: "lock" }) });
    // Pull request 9 reaches network too.
    await expect(takeLocks(r.work, ["network"], { pr: 9, by: "erin", at: "2026-10-07T00:00:00.000Z", head: "c".repeat(40) }, async () => true))
      .resolves.toEqual({ ok: false, held: [expect.objectContaining({ root: "network", pr: 7, via: "lock" })] });
    // The holder's own apply takes the lock over as an apply lock.
    const apply = setup("/terragucci apply", { pr: OPEN(r.head), reviews: approved(r.head), statuses: GREEN });
    expect((await decide(r, apply)).go).toBe(true);
    expect(readLocks(r.work).locks.network?.via).toBeUndefined();
  });

  it("/terragucci lock is refused when another open pull request holds a root, on a fork, and under apply.when merge", async () => {
    const r = repos();
    await takeLocks(r.work, ["network"], { pr: 3, by: "erin", at: "2026-10-07T00:00:00.000Z", head: "c".repeat(40), via: "lock" }, async () => true);
    const held = setup("/terragucci lock", { pr: OPEN(r.head), others: { 3: "open" } });
    expect((await decide(r, held)).go).toBe(false);
    expect(replies(held)[0]).toContain("`network` is locked by pull request 3 (locked with `/terragucci lock` by erin), so pull request 7 is not locked");
    expect(readLocks(r.work).locks.network?.pr).toBe(3);
    const fork = setup("/terragucci lock", { pr: OPEN(r.head, { head: { sha: r.head, ref: "feature", repo: { full_name: "evil/infra" } } }) });
    expect((await decide(r, fork)).go).toBe(false);
    expect(replies(fork)[0]).toContain("fork");
    const merge = setup("/terragucci lock", { pr: OPEN(r.head) });
    await decideApplyComment({ layers, env: merge.env, fetch: merge.fetch, git: r.git, repo: r.work });
    expect(replies(merge)[0]).toContain("pull requests take no locks");
  });
});

describe("apply.when: pull-request in a Terragrunt repo", () => {
  const unit = (deps = ""): string => `include "root" {\n  path = find_in_parent_folders("root.hcl")\n}\n${deps}`;
  const tgLayers = [["live/canary/one"], ["live/fleet/three", "live/fleet/two"]];
  /** origin with three units, live/fleet/two reading live/canary/one through a dependency block, and a branch `feature` with `change`. */
  const tgRepos = (change: Record<string, string>): ReturnType<typeof repos> => {
    const dir = tmp("tg-pr-apply-tg-");
    const origin = join(dir, "origin.git");
    git(dir, "init", "-q", "--bare", "-b", "main", origin);
    const work = join(dir, "work");
    git(dir, "init", "-q", "-b", "main", work);
    git(work, "remote", "add", "origin", origin);
    write(work, {
      "root.hcl": "# shared\n",
      "README.md": "# units\n",
      "live/canary/one/terragrunt.hcl": unit(),
      "live/canary/one/rev.txt": "1\n",
      "live/fleet/two/terragrunt.hcl": unit('dependency "one" {\n  config_path = "../../canary/one"\n}\n'),
      "live/fleet/two/rev.txt": "1\n",
      "live/fleet/three/terragrunt.hcl": unit(),
      "live/fleet/three/rev.txt": "1\n",
      ".github/workflows/terragucci.yml": "# Generated by terragucci.\n",
    });
    commit(work, "base");
    git(work, "push", "-q", "origin", "main");
    git(work, "checkout", "-q", "-b", "feature");
    write(work, change);
    const head = commit(work, "change");
    git(work, "push", "-q", "origin", "feature");
    git(work, "checkout", "-q", "main");
    git(work, "fetch", "-q", "origin");
    return { work, origin, head, git: (args) => spawnSync("git", args, { cwd: work, encoding: "utf-8" }) as ReturnType<Git> };
  };
  const reach = (change: Record<string, string>) => {
    const r = tgRepos(change);
    return reachedUnits(r.git, "origin/main", r.head, tgLayers);
  };

  it("reaches a changed unit and the units whose dependency blocks name it, from git alone", () => {
    expect(reach({ "live/canary/one/rev.txt": "2\n" })).toEqual({ units: ["live/canary/one", "live/fleet/two"] });
    expect(reach({ "live/fleet/two/rev.txt": "2\n" })).toEqual({ units: ["live/fleet/two"] });
    expect(reach({ "live/fleet/three/rev.txt": "2\n", "README.md": "# more\n" })).toEqual({ units: ["live/fleet/three"] });
    // An edge the pull request adds counts, as one it removes would.
    expect(reach({ "live/canary/one/rev.txt": "2\n", "live/fleet/three/terragrunt.hcl": unit('dependencies {\n  paths = ["../../canary/one"]\n}\n') }).units).toEqual(["live/canary/one", "live/fleet/three", "live/fleet/two"]);
  });

  it("a file in no unit's directory reaches every unit, and says which file", () => {
    expect(reach({ "root.hcl": "# changed\n" })).toEqual({ units: ["live/canary/one", "live/fleet/three", "live/fleet/two"], every: "it changes `root.hcl`, which is in no unit's directory" });
  });

  it("locks the units, refuses a second pull request that reaches one through a dependency block, naming the unit and the holder", async () => {
    const a = tgRepos({ "live/canary/one/rev.txt": "a\n" });
    const s = setup("/terragucci apply", { pr: OPEN(a.head), reviews: approved(a.head), statuses: GREEN });
    const d = await decideApplyComment({ layers: tgLayers, env: s.env, fetch: s.fetch, git: a.git, repo: a.work, when: "pull-request", terragrunt: true, wait: async () => {} });
    expect(d).toMatchObject({ go: true, open: true, pr: 7, sha: a.head });
    expect(Object.keys(readLocks(a.work).locks).sort()).toEqual(["live/canary/one", "live/fleet/two"]);
    expect(replies(s)).toEqual([]);
    // B, pull request 7 here, changes live/fleet/two while pull request 3 holds it.
    const b = tgRepos({ "live/fleet/two/rev.txt": "b\n" });
    await takeLocks(b.work, ["live/canary/one", "live/fleet/two"], { pr: 3, by: "erin", at: "2026-10-07T00:00:00.000Z", head: "c".repeat(40) }, async () => true);
    const held = setup("/terragucci apply", { pr: OPEN(b.head), reviews: approved(b.head), statuses: GREEN, others: { 3: "open" } });
    expect((await decideApplyComment({ layers: tgLayers, env: held.env, fetch: held.fetch, git: b.git, repo: b.work, when: "pull-request", terragrunt: true, wait: async () => {} })).go).toBe(false);
    expect(replies(held)[0]).toContain("`live/fleet/two` is locked by pull request 3 (applied by erin), so pull request 7 is not applied");
  });

  it("says in a reply when it locks every unit, once: the decision made again under the apply lock does not repeat it", async () => {
    const r = tgRepos({ "root.hcl": "# changed\n" });
    const s = setup("/terragucci apply", { pr: OPEN(r.head), reviews: approved(r.head), statuses: GREEN });
    const o = { layers: tgLayers, env: s.env, fetch: s.fetch, git: r.git, repo: r.work, when: "pull-request" as const, terragrunt: true, wait: async () => {} };
    expect((await decideApplyComment(o)).go).toBe(true);
    expect(replies(s)).toEqual([`terragucci: pull request 7 locks every unit: it changes \`root.hcl\`, which is in no unit's directory. Applying its head ${r.head.slice(0, 8)}`]);
    expect((await decideApplyComment({ ...o, again: true })).go).toBe(true);
    expect(replies(s)).toHaveLength(1);
    const lock = setup("/terragucci lock", { pr: OPEN(r.head) });
    await decideApplyComment({ ...o, env: lock.env, fetch: lock.fetch });
    expect(replies(lock)[0]).toMatch(/^terragucci: pull request 7 locks every unit: .*\. locked `live\/canary\/one`, `live\/fleet\/three`, `live\/fleet\/two` for pull request 7/);
  });
});

describe("locks: plan, the pr-lock job", () => {
  /** setup's forge, with the event file swapped for a pull_request_target event. */
  const target = (action: string, pr: any, f: Partial<Forge> = {}) => {
    const s = setup("", { pr, ...f });
    writeFileSync(s.env.GITHUB_EVENT_PATH!, JSON.stringify({ action, number: 7, pull_request: { number: 7, ...pr }, repository: { full_name: "acme/infra", default_branch: "main" } }));
    return s;
  };
  const statuses = (s: { sent: Sent[] }) => s.sent.filter((x) => x.method === "POST" && x.path.includes("/statuses/")).map((x) => [x.body.state, x.body.context, x.body.description]);
  const lock = (r: ReturnType<typeof repos>, s: ReturnType<typeof setup>, when?: "pull-request") => decidePlanLock({ layers, env: s.env, fetch: s.fetch, git: r.git, repo: r.work, ...(when ? { when } : {}) });

  it("a pull request opened takes plan locks on the roots its head reaches, posts terragucci/lock success, and says nothing", async () => {
    const r = repos();
    const s = target("opened", OPEN(r.head));
    expect((await lock(r, s)).go).toBe(false);
    expect(readLocks(r.work).locks).toEqual({ network: expect.objectContaining({ pr: 7, by: "author", head: r.head, stage: "plan" }) });
    expect(statuses(s)).toEqual([["success", "terragucci/lock", "holds network"]]);
    expect(s.sent.find((x) => x.path.endsWith(`statuses/${r.head}`))).toBeDefined();
    expect(replies(s)).toEqual([]);
  });

  it("a second pull request that reaches a held root fails terragucci/lock and is told who holds it, planned by its author, and how to plan again", async () => {
    const r = repos();
    await takeLocks(r.work, ["network"], { pr: 3, by: "erin", at: "2026-10-07T00:00:00.000Z", head: "c".repeat(40), stage: "plan" }, async () => true);
    const s = target("synchronize", OPEN(r.head), { others: { 3: "open" } });
    await lock(r, s);
    expect(statuses(s)).toEqual([["failure", "terragucci/lock", "locked by pull request 3: network"]]);
    expect(replies(s)[0]).toBe("terragucci: `network` is locked by pull request 3 (planned by erin), so pull request 7 is not locked. Comment `/terragucci plan` on it once that pull request merges or closes, or someone with write access comments `/terragucci unlock` on it");
    expect(readLocks(r.work).locks.network?.pr).toBe(3);
    // An apply on pull request 7 is refused the same way, naming the plan lock.
    const apply = setup("/terragucci apply", { pr: OPEN(r.head), reviews: approved(r.head), statuses: GREEN, others: { 3: "open" } });
    await decideApplyComment({ layers, env: apply.env, fetch: apply.fetch, git: r.git, repo: r.work, when: "pull-request", wait: async () => {} });
    expect(replies(apply)[0]).toContain("`network` is locked by pull request 3 (planned by erin), so pull request 7 is not applied");
  });

  it("closing releases the locks with no reply; a push releases plan locks the head no longer reaches; a fork takes none", async () => {
    const r = repos();
    await takeLocks(r.work, ["app"], { pr: 7, by: "author", at: "2026-10-07T00:00:00.000Z", head: "a".repeat(40), stage: "plan" }, async () => true);
    const push = target("synchronize", OPEN(r.head));
    expect((await lock(r, push)).reason).toContain("released app, which its head no longer reaches");
    expect(Object.keys(readLocks(r.work).locks)).toEqual(["network"]);
    const closed = target("closed", { ...OPEN(r.head), state: "closed", merged: true });
    expect((await lock(r, closed)).reason).toBe("pull request 7 closed, so its locks on network are released");
    expect(readLocks(r.work).locks).toEqual({});
    expect(replies(closed)).toEqual([]);
    const fork = target("opened", OPEN(r.head, { head: { sha: r.head, ref: "feature", repo: { full_name: "evil/infra" } } }));
    expect((await lock(r, fork)).reason).toContain("comes from a fork");
    expect(readLocks(r.work).locks).toEqual({});
    expect(statuses(fork)).toEqual([]);
  });

  it("a plan keeps the pull request's own apply lock, and the apply takes over its plan lock", async () => {
    const r = repos();
    await takeLocks(r.work, ["network"], { pr: 7, by: "dev", at: "2026-10-07T00:00:00.000Z", head: r.head }, async () => true);
    await lock(r, target("synchronize", OPEN(r.head)));
    expect(readLocks(r.work).locks.network?.stage).toBeUndefined();
    const s = setup("/terragucci apply", { pr: OPEN(r.head), reviews: approved(r.head), statuses: GREEN });
    await lock(r, target("opened", OPEN(r.head)));
    expect((await decideApplyComment({ layers, env: s.env, fetch: s.fetch, git: r.git, repo: r.work, when: "pull-request", wait: async () => {} })).go).toBe(true);
    expect(readLocks(r.work).locks.network).toEqual(expect.not.objectContaining({ stage: "plan" }));
  });

  it("comments: /terragucci plan locks for a writer, /terragucci unlock releases under apply.when merge, and under pull-request lock and unlock are another job's", async () => {
    const r = repos();
    const plan = setup("/terragucci plan", { pr: OPEN(r.head) });
    await lock(r, plan);
    expect(readLocks(r.work).locks.network).toEqual(expect.objectContaining({ pr: 7, by: "author", stage: "plan" }));
    const stranger = setup("/terragucci unlock", { pr: OPEN(r.head), permission: { dev: "read" } });
    expect((await lock(r, stranger)).reason).toContain("no write access");
    expect(readLocks(r.work).locks.network).toBeDefined();
    const unlock = setup("/terragucci unlock", { pr: OPEN(r.head) });
    await lock(r, unlock);
    expect(replies(unlock)[0]).toBe("terragucci: released the locks pull request 7 held on `network`, for dev");
    expect(readLocks(r.work).locks).toEqual({});
    const elsewhere = setup("/terragucci unlock", { pr: OPEN(r.head) });
    expect((await lock(r, elsewhere, "pull-request")).reason).toBe("another job reads this comment");
    expect((await lock(r, setup("/terragucci apply", { pr: OPEN(r.head) }))).reason).toBe("another job reads this comment");
  });
});

describe("root locks", () => {
  const origin = (): string => {
    const dir = tmp("tg-locks-");
    const o = join(dir, "origin.git");
    git(dir, "init", "-q", "--bare", "-b", "main", o);
    const work = join(dir, "work");
    git(dir, "init", "-q", "-b", "main", work);
    git(work, "remote", "add", "origin", o);
    commit(work, "base");
    git(work, "push", "-q", "origin", "main");
    return work;
  };
  const holder = (pr: number) => ({ pr, by: `user${pr}`, at: "2026-10-07T00:00:00.000Z", head: "d".repeat(40) });

  it("keeps the locks on chant/lifecycle, and a pull request keeps its own roots", async () => {
    const work = origin();
    expect(await takeLocks(work, ["b", "a"], holder(1), async () => true)).toEqual({ ok: true, taken: ["a", "b"] });
    expect(await takeLocks(work, ["a"], holder(1), async () => true)).toEqual({ ok: true, taken: ["a"] });
    const file = parseLocks(git(work, "show", `origin/chant/lifecycle:${LOCKS_PATH}`));
    expect(Object.keys(file.locks).sort()).toEqual(["a", "b"]);
    const refused = await takeLocks(work, ["b", "c"], holder(2), async () => true);
    expect(refused).toEqual({ ok: false, held: [expect.objectContaining({ root: "b", pr: 1 })] });
    expect(readLocks(work).locks.c).toBeUndefined();
    expect(describeHeld((refused as { held: Parameters<typeof describeHeld>[0] }).held)).toBe("`b` is locked by pull request 1 (applied by user1)");
  });

  it("releases only the pull request's own locks", async () => {
    const work = origin();
    await takeLocks(work, ["a"], holder(1), async () => true);
    await takeLocks(work, ["b"], holder(2), async () => true);
    expect(releaseLocks(work, 1)).toEqual(["a"]);
    expect(Object.keys(readLocks(work).locks)).toEqual(["b"]);
    expect(releaseLocks(work, 1)).toEqual([]);
  });

  it("reads an unreadable file as no locks", () => {
    expect(parseLocks("not json").locks).toEqual({});
    expect(parseLocks(JSON.stringify({ version: 1, locks: { a: { pr: "x" } } })).locks).toEqual({});
  });
});

describe("pr-merge", () => {
  const ENV = { GITHUB_REPOSITORY: "acme/infra", GITHUB_API_URL: "https://forge.test/api/v1", TG_TOKEN: "t" };
  /** The forge as pr-merge reads it: pull request 7 open at `head`, its reviews, and the answer to the merge. */
  const forgeFor = (head: string, o: { pr?: Record<string, unknown>; reviews?: unknown[]; merge?: { status: number; body: string } } = {}) => {
    const sent: { url: string; method?: string; body?: unknown; auth?: string }[] = [];
    const fetch: Fetch = async (u, init) => {
      sent.push({ url: u, method: init?.method, body: init?.body ? JSON.parse(init.body) : undefined, auth: init?.headers?.authorization });
      const answer = (status: number, json: unknown, text = JSON.stringify(json)) => ({ ok: status < 300, status, json: async () => json, text: async () => text });
      if (u.endsWith("/merge")) return (o.merge ? answer(o.merge.status, {}, o.merge.body) : answer(200, {})) as never;
      if (u.includes("/reviews")) return answer(200, o.reviews ?? approved(head)) as never;
      if (u.includes("/permission")) return answer(200, { permission: "write" }) as never;
      if (u.endsWith("/pulls/7")) return answer(200, OPEN(head, o.pr)) as never;
      return answer(404, {}) as never;
    };
    return { fetch, sent, merges: () => sent.filter((x) => x.url.endsWith("/merge")) };
  };

  it("merges only at the head that applied, on each forge, and releases the locks", async () => {
    const r = repos();
    const sha = r.head;
    for (const [forge, method, body] of [
      ["github", "PUT", { sha, merge_method: "merge" }],
      ["forgejo", "POST", { Do: "merge", head_commit_id: sha }],
    ] as const) {
      await takeLocks(r.work, ["network"], { pr: 7, by: "dev", at: "2026-10-07T00:00:00.000Z", head: sha }, async () => true);
      const f = forgeFor(sha);
      const said = await mergePullRequest({ pr: 7, sha, forge, env: ENV, fetch: f.fetch, repo: r.work });
      expect(f.merges().map(({ url, method, body }) => ({ url, method, body }))).toEqual([{ url: "https://forge.test/api/v1/repos/acme/infra/pulls/7/merge", method, body }]);
      expect(said).toContain("released its locks on network");
      expect(readLocks(r.work).locks).toEqual({});
    }
  });

  it("merges with TG_MERGE_TOKEN when the job has it, and reads the pull request with the job's own token", async () => {
    const r = repos();
    for (const forge of ["github", "forgejo"] as const) {
      const f = forgeFor(r.head);
      await mergePullRequest({ pr: 7, sha: r.head, forge, env: { ...ENV, TG_TOKEN: "job", TG_MERGE_TOKEN: "person" }, fetch: f.fetch, repo: r.work });
      expect(f.merges().map((x) => x.auth)).toEqual(["token person"]);
      expect(f.sent.filter((x) => !x.url.endsWith("/merge")).every((x) => x.auth === "token job")).toBe(true);
    }
  });

  it("merges nothing when the head moved, has no approval of its own, or the pull request closed: the sha comes from a job that ran its code", async () => {
    const r = repos();
    const other = "a".repeat(40);
    for (const [o, why] of [
      [{ pr: { head: { sha: other, ref: "feature", repo: { full_name: "acme/infra" } } } }, "moved after it applied"],
      [{ reviews: approved(other) }, "no reviewer other than its author approved"],
      [{ reviews: approved(r.head, "author") }, "no reviewer other than its author approved"],
      [{ pr: { state: "closed" } }, "is not open"],
    ] as const) {
      const f = forgeFor(r.head, o);
      await expect(mergePullRequest({ pr: 7, sha: r.head, env: ENV, fetch: f.fetch, repo: r.work })).rejects.toThrow(why);
      expect(f.merges()).toEqual([]);
    }
  });

  it("gives the forge's reason for a refused merge", async () => {
    const r = repos();
    const body = JSON.stringify({ message: "PushRejected with remote message: Forgejo: User 'forgejo-actions' is not allowed to push to branch 'main'", url: "x" });
    const f = forgeFor(r.head, { merge: { status: 409, body } });
    await expect(mergePullRequest({ pr: 7, sha: r.head, forge: "forgejo", env: ENV, fetch: f.fetch, repo: r.work }))
      .rejects.toThrow("the forge refused the merge (POST answered 409: PushRejected with remote message: Forgejo: User 'forgejo-actions' is not allowed to push to branch 'main')");
  });

  it("throws when the forge refuses, and keeps the locks", async () => {
    const r = repos();
    await takeLocks(r.work, ["network"], { pr: 7, by: "dev", at: "2026-10-07T00:00:00.000Z", head: r.head }, async () => true);
    const f = forgeFor(r.head, { merge: { status: 409, body: "" } });
    await expect(mergePullRequest({ pr: 7, sha: r.head, env: ENV, fetch: f.fetch, repo: r.work })).rejects.toThrow(/answered 409/);
    expect(readLocks(r.work).locks.network?.pr).toBe(7);
  });
});
