import { spawnSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { decideApplyComment, decideMergeRequestApply, mergePullRequest, type Git } from "../src/comment-apply";
import type { Fetch } from "../src/forge";
import { describeHeld, LOCKS_PATH, parseLocks, readLocks, releaseLocks, takeLocks } from "../src/locks";
import { backend, git, tmp, write } from "./helpers";

const layers = [["network"], ["app"]];
const commit = (dir: string, m: string): string => {
  git(dir, "add", "-A");
  git(dir, "-c", "user.name=t", "-c", "user.email=t@t", "-c", "commit.gpgsign=false", "commit", "-q", "--allow-empty", "-m", m);
  return git(dir, "rev-parse", "HEAD").trim();
};

/**
 * origin with main (two roots) and a branch `feature` that changes network,
 * and a checkout of main, as the comment's job has it. `behind` moves main on
 * after the branch was cut; `pipeline` makes the branch change the pipeline.
 */
function repos(o: { behind?: boolean; pipeline?: boolean } = {}): { work: string; origin: string; head: string; git: Git } {
  const dir = tmp("tg-pr-apply-");
  const origin = join(dir, "origin.git");
  git(dir, "init", "-q", "--bare", "-b", "main", origin);
  const work = join(dir, "work");
  git(dir, "init", "-q", "-b", "main", work);
  git(work, "remote", "add", "origin", origin);
  write(work, { "network/main.tf": backend("network"), "app/main.tf": backend("app"), ".github/workflows/terragucci.yml": "# Generated by terragucci.\n" });
  commit(work, "base");
  git(work, "push", "-q", "origin", "main");
  git(work, "checkout", "-q", "-b", "feature");
  write(work, { "network/extra.tf": "# a change\n", ...(o.pipeline ? { ".github/workflows/terragucci.yml": "# edited\n" } : {}) });
  const head = commit(work, "change network");
  git(work, "push", "-q", "origin", "feature");
  git(work, "checkout", "-q", "main");
  if (o.behind) {
    write(work, { "app/later.tf": "# later\n" });
    commit(work, "later on main");
    git(work, "push", "-q", "origin", "main");
    git(work, "reset", "-q", "--hard", "HEAD~1");
  }
  return { work, origin, head, git: (args) => spawnSync("git", args, { cwd: work, encoding: "utf-8" }) as ReturnType<Git> };
}

interface Sent { method: string; path: string; body?: any }

const OPEN = (head: string, extra: Record<string, unknown> = {}) => ({
  state: "open", merged: false, number: 7, user: { login: "author" },
  head: { sha: head, ref: "feature", repo: { full_name: "acme/infra" } }, base: { ref: "main" }, ...extra,
});

interface Forge {
  pr: any;
  reviews?: unknown[];
  statuses?: unknown[];
  checkRuns?: unknown[];
  permission?: Record<string, string>;
  others?: Record<number, string>;
}

function setup(comment: string, f: Forge, forgejo = false): { env: NodeJS.ProcessEnv; fetch: Fetch; sent: Sent[] } {
  const dir = tmp("tg-pr-apply-event-");
  const file = join(dir, "event.json");
  writeFileSync(file, JSON.stringify({
    action: "created",
    comment: { body: comment, user: { login: "dev" } },
    issue: { number: 7, pull_request: {} },
    repository: { full_name: "acme/infra", default_branch: "main", ...(forgejo ? { permissions: { push: true, admin: false } } : {}) },
    ...(forgejo ? { sender: { login: "dev" } } : {}),
  }));
  const sent: Sent[] = [];
  const fetch: Fetch = async (url, init) => {
    const path = url.replace("https://forge.test/api/v1/", "");
    sent.push({ method: init?.method ?? "GET", path, body: init?.body ? JSON.parse(init.body) : undefined });
    const answer = (status: number, json: unknown) => ({ ok: status < 300, status, json: async () => json, text: async () => JSON.stringify(json) });
    const perm = /collaborators\/([^/]+)\/permission/.exec(path);
    if (perm) return answer(200, { permission: f.permission?.[decodeURIComponent(perm[1]!)] ?? "write" }) as never;
    if (path.includes("/reviews")) return answer(200, f.reviews ?? []) as never;
    if (path.endsWith("/status")) return answer(200, { statuses: f.statuses ?? [] }) as never;
    if (path.includes("/check-runs")) return answer(200, { check_runs: f.checkRuns ?? [] }) as never;
    const other = /pulls\/(\d+)$/.exec(path);
    if (other && Number(other[1]) !== 7) return answer(200, { state: f.others?.[Number(other[1])] ?? "closed" }) as never;
    if (path.endsWith("pulls/7")) return answer(200, f.pr) as never;
    return answer(201, {}) as never;
  };
  return { env: { GITHUB_EVENT_PATH: file, GITHUB_REPOSITORY: "acme/infra", GITHUB_API_URL: "https://forge.test/api/v1", TG_TOKEN: "t" }, fetch, sent };
}

const replies = (s: { sent: Sent[] }): string[] => s.sent.filter((x) => x.method === "POST" && x.path.endsWith("/comments")).map((x) => x.body.body as string);
const approved = (head: string, by = "rev") => [{ user: { login: by }, state: "APPROVED", commit_id: head }];
const GREEN = [{ id: 1, context: "terragucci/plan", state: "success" }, { id: 2, context: "terragucci / check (push)", state: "success" }];

describe("apply.when: pull-request, an open pull request", () => {
  const decide = (r: ReturnType<typeof repos>, s: ReturnType<typeof setup>, forge?: "forgejo") =>
    decideApplyComment({ layers, env: s.env, fetch: s.fetch, git: r.git, repo: r.work, when: "pull-request", ...(forge ? { forge } : {}) });

  it("applies the head once it is approved, green and up to date, and locks the roots it reaches", async () => {
    const r = repos();
    const s = setup("/terragucci apply", { pr: OPEN(r.head), reviews: approved(r.head), statuses: GREEN });
    const d = await decide(r, s);
    expect(d).toMatchObject({ go: true, open: true, pr: 7, sha: r.head, base: "main" });
    expect(replies(s)).toEqual([]);
    // network changed, and app reads nothing, so network alone is locked.
    expect(readLocks(r.work).locks).toEqual({ network: expect.objectContaining({ pr: 7, by: "dev", head: r.head }) });
  });

  it("with apply.when merge, an open pull request is still refused", async () => {
    const r = repos();
    const s = setup("/terragucci apply", { pr: OPEN(r.head), reviews: approved(r.head), statuses: GREEN });
    const d = await decideApplyComment({ layers, env: s.env, fetch: s.fetch, git: r.git, repo: r.work });
    expect(d.go).toBe(false);
    expect(replies(s)[0]).toContain("pull request 7 is not merged");
  });

  it("refuses a head with no approval, one approved by its author only, and one approved on an older commit", async () => {
    for (const reviews of [[], approved("a".repeat(40), "rev"), [{ user: { login: "author" }, state: "APPROVED", commit_id: "" }]]) {
      const r = repos();
      const s = setup("/terragucci apply", { pr: OPEN(r.head), reviews, statuses: GREEN });
      expect((await decide(r, s)).go).toBe(false);
      expect(replies(s)[0]).toContain("pull request 7 is not approved");
      expect(readLocks(r.work).locks).toEqual({});
    }
  });

  it("refuses when a reviewer's latest review asks for changes, and counts no approval from someone without write access", async () => {
    const r = repos();
    const changes = setup("/terragucci apply", { pr: OPEN(r.head), reviews: [...approved(r.head), { user: { login: "sam" }, state: "CHANGES_REQUESTED", commit_id: r.head }], statuses: GREEN });
    expect((await decide(r, changes)).go).toBe(false);
    expect(replies(changes)[0]).toContain("sam asked for changes");
    const reader = setup("/terragucci apply", { pr: OPEN(r.head), reviews: approved(r.head, "visitor"), statuses: GREEN, permission: { visitor: "read" } });
    expect((await decide(r, reader)).go).toBe(false);
    expect(replies(reader)[0]).toContain("not approved");
  });

  it("refuses failing or running checks by name, and a head whose plan has not passed", async () => {
    const r = repos();
    const failing = setup("/terragucci apply", { pr: OPEN(r.head), reviews: approved(r.head), statuses: [...GREEN, { id: 3, context: "lint", state: "failure" }] });
    expect((await decide(r, failing)).go).toBe(false);
    expect(replies(failing)[0]).toContain("lint failed");
    const running = setup("/terragucci apply", { pr: OPEN(r.head), reviews: approved(r.head), statuses: GREEN, checkRuns: [{ name: "build", status: "in_progress" }] });
    expect((await decide(r, running)).go).toBe(false);
    expect(replies(running)[0]).toContain("build still running");
    const noPlan = setup("/terragucci apply", { pr: OPEN(r.head), reviews: approved(r.head), statuses: [] });
    expect((await decide(r, noPlan)).go).toBe(false);
    expect(replies(noPlan)[0]).toContain("the plan of pull request 7 has not passed");
    // The apply's own status never holds it back, and a newer status of a context replaces an older one.
    const own = setup("/terragucci apply", { pr: OPEN(r.head), reviews: approved(r.head), statuses: [...GREEN, { id: 4, context: "terragucci/apply", state: "failure" }, { id: 5, context: "lint", state: "failure" }, { id: 6, context: "lint", state: "success" }] });
    expect((await decide(r, own)).go).toBe(true);
  });

  it("forgejo: reads a status's state from status, and an unofficial approval does not count", async () => {
    const r = repos();
    const s = setup("/terragucci apply", { pr: OPEN(r.head), reviews: [{ user: { login: "rev" }, state: "APPROVED", commit_id: r.head, official: false }], statuses: [{ id: 1, context: "terragucci/plan", status: "success" }] }, true);
    expect((await decide(r, s, "forgejo")).go).toBe(false);
    const ok = setup("/terragucci apply", { pr: OPEN(r.head), reviews: [{ user: { login: "rev" }, state: "APPROVED", commit_id: r.head, official: true }], statuses: [{ id: 1, context: "terragucci/plan", status: "success" }] }, true);
    expect((await decide(r, ok, "forgejo")).go).toBe(true);
    expect(ok.sent.some((x) => x.path.includes("check-runs"))).toBe(false);
  });

  it("refuses a head that is not up to date with the default branch, and names both commits", async () => {
    const r = repos({ behind: true });
    const s = setup("/terragucci apply", { pr: OPEN(r.head), reviews: approved(r.head), statuses: GREEN });
    const d = await decide(r, s);
    expect(d.go).toBe(false);
    expect(replies(s)[0]).toMatch(/pull request 7 is not up to date with main: its head [0-9a-f]{8} does not contain [0-9a-f]{8}/);
    expect(readLocks(r.work).locks).toEqual({});
  });

  it("refuses a pull request that changes the pipeline, a fork's, and one whose head moved", async () => {
    const pipe = repos({ pipeline: true });
    const s = setup("/terragucci apply", { pr: OPEN(pipe.head), reviews: approved(pipe.head), statuses: GREEN });
    expect((await decide(pipe, s)).go).toBe(false);
    expect(replies(s)[0]).toContain("changes .github/workflows/terragucci.yml");
    const r = repos();
    const fork = setup("/terragucci apply", { pr: OPEN(r.head, { head: { sha: r.head, ref: "feature", repo: { full_name: "evil/infra" } } }) });
    expect((await decide(r, fork)).go).toBe(false);
    expect(replies(fork)[0]).toContain("fork");
    const other = "b".repeat(40);
    const moved = setup("/terragucci apply", { pr: OPEN(other), reviews: approved(other), statuses: GREEN });
    expect((await decide(r, moved)).go).toBe(false);
    expect(replies(moved)[0]).toContain("moved while this comment was read");
  });

  it("refuses a root another open pull request holds, names it, and takes over a lock whose holder closed", async () => {
    const r = repos();
    await takeLocks(r.work, ["network"], { pr: 3, by: "erin", at: "2026-10-07T00:00:00.000Z", head: "c".repeat(40) }, async () => true);
    const held = setup("/terragucci apply", { pr: OPEN(r.head), reviews: approved(r.head), statuses: GREEN, others: { 3: "open" } });
    expect((await decide(r, held)).go).toBe(false);
    expect(replies(held)[0]).toContain("`network` is locked by pull request 3 (applied by erin)");
    expect(readLocks(r.work).locks.network?.pr).toBe(3);
    const closed = setup("/terragucci apply", { pr: OPEN(r.head), reviews: approved(r.head), statuses: GREEN, others: { 3: "closed" } });
    expect((await decide(r, closed)).go).toBe(true);
    expect(readLocks(r.work).locks.network?.pr).toBe(7);
  });

  it("/terragucci unlock releases the pull request's locks for someone with write access, and is refused under apply.when merge", async () => {
    const r = repos();
    await takeLocks(r.work, ["network", "app"], { pr: 7, by: "dev", at: "2026-10-07T00:00:00.000Z", head: r.head }, async () => true);
    const s = setup("/terragucci unlock", { pr: OPEN(r.head) });
    const d = await decide(r, s);
    expect(d.go).toBe(false);
    expect(replies(s)[0]).toContain("released the locks pull request 7 held on `app`, `network`");
    expect(readLocks(r.work).locks).toEqual({});
    const again = setup("/terragucci unlock", { pr: OPEN(r.head) });
    await decide(r, again);
    expect(replies(again)[0]).toContain("pull request 7 holds no lock");
    const merge = setup("/terragucci unlock", { pr: OPEN(r.head) });
    await decideApplyComment({ layers, env: merge.env, fetch: merge.fetch, git: r.git, repo: r.work });
    expect(replies(merge)[0]).toContain("there is nothing to unlock");
  });
});

describe("root locks", () => {
  const origin = (): string => {
    const dir = tmp("tg-locks-");
    const o = join(dir, "origin.git");
    git(dir, "init", "-q", "--bare", "-b", "main", o);
    const work = join(dir, "work");
    git(dir, "init", "-q", "-b", "main", work);
    git(work, "remote", "add", "origin", o);
    commit(work, "base");
    git(work, "push", "-q", "origin", "main");
    return work;
  };
  const holder = (pr: number) => ({ pr, by: `user${pr}`, at: "2026-10-07T00:00:00.000Z", head: "d".repeat(40) });

  it("keeps the locks on chant/lifecycle, and a pull request keeps its own roots", async () => {
    const work = origin();
    expect(await takeLocks(work, ["b", "a"], holder(1), async () => true)).toEqual({ ok: true, taken: ["a", "b"] });
    expect(await takeLocks(work, ["a"], holder(1), async () => true)).toEqual({ ok: true, taken: ["a"] });
    const file = parseLocks(git(work, "show", `origin/chant/lifecycle:${LOCKS_PATH}`));
    expect(Object.keys(file.locks).sort()).toEqual(["a", "b"]);
    const refused = await takeLocks(work, ["b", "c"], holder(2), async () => true);
    expect(refused).toEqual({ ok: false, held: [expect.objectContaining({ root: "b", pr: 1 })] });
    expect(readLocks(work).locks.c).toBeUndefined();
    expect(describeHeld((refused as { held: Parameters<typeof describeHeld>[0] }).held)).toBe("`b` is locked by pull request 1 (applied by user1)");
  });

  it("releases only the pull request's own locks", async () => {
    const work = origin();
    await takeLocks(work, ["a"], holder(1), async () => true);
    await takeLocks(work, ["b"], holder(2), async () => true);
    expect(releaseLocks(work, 1)).toEqual(["a"]);
    expect(Object.keys(readLocks(work).locks)).toEqual(["b"]);
    expect(releaseLocks(work, 1)).toEqual([]);
  });

  it("reads an unreadable file as no locks", () => {
    expect(parseLocks("not json").locks).toEqual({});
    expect(parseLocks(JSON.stringify({ version: 1, locks: { a: { pr: "x" } } })).locks).toEqual({});
  });
});

describe("a GitLab merge request's manual apply", () => {
  const glEnv = (r: ReturnType<typeof repos>, extra: Record<string, string> = {}): NodeJS.ProcessEnv => ({
    CI_API_V4_URL: "https://gl.test/api/v4", CI_PROJECT_ID: "5", CI_MERGE_REQUEST_IID: "7", CI_COMMIT_SHA: r.head, CI_DEFAULT_BRANCH: "main",
    GITLAB_USER_LOGIN: "dev", GITLAB_USER_ID: "11", TG_TOKEN: "t", ...extra,
  });
  const gl = (o: { access?: number; mr?: Record<string, unknown>; approvedBy?: string[] }, head: string) => {
    const sent: Sent[] = [];
    const fetch: Fetch = async (url, init) => {
      const path = url.replace("https://gl.test/api/v4/projects/5/", "");
      sent.push({ method: init?.method ?? "GET", path, body: init?.body ? JSON.parse(init.body) : undefined });
      const answer = (status: number, json: unknown) => ({ ok: status < 300, status, json: async () => json, text: async () => JSON.stringify(json) });
      if (path.startsWith("members/all/")) return (o.access === undefined ? answer(200, { access_level: 30 }) : o.access === 0 ? answer(404, {}) : answer(200, { access_level: o.access })) as never;
      if (path.endsWith("/approvals")) return answer(200, { approved_by: (o.approvedBy ?? ["rev"]).map((u) => ({ user: { username: u } })) }) as never;
      if (path === "merge_requests/7") return answer(200, { state: "opened", sha: head, source_project_id: 5, target_project_id: 5, target_branch: "main", author: { username: "author" }, ...o.mr }) as never;
      return answer(201, {}) as never;
    };
    return { fetch, sent };
  };
  const notes = (s: { sent: Sent[] }): string[] => s.sent.filter((x) => x.method === "POST" && x.path.endsWith("/notes")).map((x) => x.body.body as string);

  it("applies an approved, up-to-date merge request started by a Developer, and locks its roots", async () => {
    const r = repos();
    const s = gl({}, r.head);
    const d = await decideMergeRequestApply({ layers, env: glEnv(r), fetch: s.fetch, git: r.git, repo: r.work });
    expect(d).toMatchObject({ go: true, open: true, pr: 7, sha: r.head, base: "main" });
    expect(readLocks(r.work).locks.network?.pr).toBe(7);
  });

  it("refuses a Reporter, an unapproved merge request, one approved by its author only, and a stale one, each with a note", async () => {
    const r = repos();
    const reporter = gl({ access: 20 }, r.head);
    expect((await decideMergeRequestApply({ layers, env: glEnv(r), fetch: reporter.fetch, git: r.git, repo: r.work })).go).toBe(false);
    expect(notes(reporter)[0]).toContain("dev has no Developer access");
    for (const approvedBy of [[], ["author"]]) {
      const s = gl({ approvedBy }, r.head);
      expect((await decideMergeRequestApply({ layers, env: glEnv(r), fetch: s.fetch, git: r.git, repo: r.work })).go).toBe(false);
      expect(notes(s)[0]).toContain("merge request 7 is not approved");
    }
    const behind = repos({ behind: true });
    const s = gl({}, behind.head);
    expect((await decideMergeRequestApply({ layers, env: glEnv(behind), fetch: s.fetch, git: behind.git, repo: behind.work })).go).toBe(false);
    expect(notes(s)[0]).toContain("is not up to date with main");
  });

  it("unlock releases the merge request's locks", async () => {
    const r = repos();
    await takeLocks(r.work, ["network"], { pr: 7, by: "dev", at: "2026-10-07T00:00:00.000Z", head: r.head }, async () => true);
    const s = gl({}, r.head);
    await decideMergeRequestApply({ layers, unlock: true, env: glEnv(r), fetch: s.fetch, git: r.git, repo: r.work });
    expect(notes(s)[0]).toContain("released the locks merge request 7 held on `network`");
    expect(readLocks(r.work).locks).toEqual({});
  });
});

describe("pr-merge", () => {
  it("merges only at the head that applied, on each forge, and releases the locks", async () => {
    const r = repos();
    const sha = r.head;
    for (const [forge, method, url, body] of [
      ["github", "PUT", "https://forge.test/api/v1/repos/acme/infra/pulls/7/merge", { sha, merge_method: "merge" }],
      ["forgejo", "POST", "https://forge.test/api/v1/repos/acme/infra/pulls/7/merge", { Do: "merge", head_commit_id: sha }],
      ["gitlab", "PUT", "https://gl.test/api/v4/projects/5/merge_requests/7/merge", { sha }],
    ] as const) {
      await takeLocks(r.work, ["network"], { pr: 7, by: "dev", at: "2026-10-07T00:00:00.000Z", head: sha }, async () => true);
      const sent: { url: string; method?: string; body?: unknown }[] = [];
      const fetch: Fetch = async (u, init) => {
        sent.push({ url: u, method: init?.method, body: init?.body ? JSON.parse(init.body) : undefined });
        return { ok: true, status: 200, json: async () => ({}), text: async () => "{}" } as never;
      };
      const env = { GITHUB_REPOSITORY: "acme/infra", GITHUB_API_URL: "https://forge.test/api/v1", CI_API_V4_URL: "https://gl.test/api/v4", CI_PROJECT_ID: "5", TG_TOKEN: "t" };
      const said = await mergePullRequest({ pr: 7, sha, forge, env, fetch, repo: r.work });
      expect(sent).toEqual([{ url, method, body }]);
      expect(said).toContain("released its locks on network");
      expect(readLocks(r.work).locks).toEqual({});
    }
  });

  it("throws when the forge refuses, and keeps the locks", async () => {
    const r = repos();
    await takeLocks(r.work, ["network"], { pr: 7, by: "dev", at: "2026-10-07T00:00:00.000Z", head: r.head }, async () => true);
    const fetch: Fetch = async () => ({ ok: false, status: 409, json: async () => ({}), text: async () => "" }) as never;
    await expect(mergePullRequest({ pr: 7, sha: r.head, env: { GITHUB_REPOSITORY: "acme/infra", GITHUB_API_URL: "https://forge.test/api/v1", TG_TOKEN: "t" }, fetch, repo: r.work })).rejects.toThrow(/answered 409/);
    expect(readLocks(r.work).locks.network?.pr).toBe(7);
  });
});
