/**
 * The dashboards and alert rules `init` and `reconcile` write into a repo
 * when terragucci.yml turns `dashboards:` on, next to the pipeline.
 *
 * Declared here with chant's grafana and prometheus lexicons and rendered
 * when init runs, the way render.ts renders the pipeline: through each
 * lexicon's entities and build functions, never its entry point, which
 * carries lint rules, codegen and the TypeScript compiler the bundle must
 * not (terragucci#87).
 *
 * Seven dashboards (Pipeline health, Change review, Rollouts and waves,
 * Drift, Estate, Runs, and one per SLO), the Prometheus rules (the SLOs'
 * recording rules and burn-rate alerts, and the pipeline alerts), and the
 * SLOs' burn-rate alerts again as Grafana-managed rules, for a team that
 * pages from Grafana rather than Alertmanager. The dashboards read the
 * metrics a stage sends (names.ts) and the span metrics a collector's
 * `spanmetrics` connector makes from the stage spans, and the Runs
 * dashboard lists the runs' traces from Tempo. When terragucci.yml says
 * where the reports bucket is served (`reports.url`), the Runs dashboard's
 * trace rows link each run's report, and the Estate dashboard links the
 * report index.
 */
import type { Declarable } from "@intentius/chant/declarable";
import { spanMetricsNames } from "@intentius/chant-lexicon-otel/metric-names";
import { Dashboard, DashboardProvider, type DashboardEntity } from "@intentius/chant-lexicon-grafana/dashboard";
import { Row, StatPanel, TablePanel, TimeSeriesPanel, type DashboardItem } from "@intentius/chant-lexicon-grafana/panels";
import { PromQuery, TempoQuery } from "@intentius/chant-lexicon-grafana/query";
import { QueryVariable } from "@intentius/chant-lexicon-grafana/variables";
import { buildGrafana } from "@intentius/chant-lexicon-grafana/build";
import { errorRatio, quantile, selector, type Matcher } from "@intentius/chant-lexicon-grafana/composites/shared";
import { SloDashboard } from "@intentius/chant-lexicon-grafana/composites/slo-dashboard";
import { SloAlertRules } from "@intentius/chant-lexicon-grafana/composites/slo-alert-rules";
import { Slo, type SloInstance } from "@intentius/chant-lexicon-prometheus/composites/slo";
import { RuleGroup, type RuleGroupEntity } from "@intentius/chant-lexicon-prometheus/rules";
import { buildRuleFile, emitYaml } from "@intentius/chant-lexicon-prometheus/build";
import { durationMs } from "@intentius/chant-lexicon-prometheus/duration";
import type { DashboardSettings } from "../config";
import { METRIC, PLAN_SLO_SECONDS, SPANMETRICS } from "./names";

export type { DashboardSettings };

export const DASHBOARD_DEFAULTS: Required<DashboardSettings> = {
  dir: "observability/terragucci",
  prometheus: "prometheus",
  tempo: "tempo",
  folder: "terragucci",
  path: "/var/lib/grafana/dashboards/terragucci",
  drift_age: "1d",
  wave_wait: "4h",
  schedule: "2d",
};

/**
 * Where the dashboards link down to: `reports` is the address of the reports
 * bucket's prefix (`reports.url` and `reports.prefix`), when terragucci.yml
 * says where the bucket is served. Without it the dashboards link nothing
 * outside Grafana.
 */
export interface DashboardLinks {
  reports?: string;
}

/** The settings with every default filled in. */
export function dashboardSettings(s: boolean | DashboardSettings | undefined): Required<DashboardSettings> | undefined {
  if (!s) return undefined;
  return { ...DASHBOARD_DEFAULTS, ...(s === true ? {} : s) };
}

/** Each dashboard's uid: what a link, the provisioning and the smoke claims address it by. */
export const DASHBOARD_UIDS = {
  pipeline: "terragucci-pipeline-health",
  changes: "terragucci-change-review",
  waves: "terragucci-rollouts-waves",
  drift: "terragucci-drift",
  estate: "terragucci-estate",
  runs: "terragucci-runs",
} as const;

/** The SLOs, by the name their recorded series carry in the `slo` label. */
export const SLO_NAMES = {
  plans: "terragucci-plan-time",
  applies: "terragucci-apply-success",
  drift: "terragucci-drift-corrected",
} as const;

/** The first line of every YAML file terragucci writes here; init leaves a file without it alone. */
export const YAML_MARKER = "# Generated by terragucci from terragucci.yml (dashboards). Edit terragucci.yml, then run terragucci init.";
/** The tag on every dashboard terragucci writes. */
export const DASHBOARD_TAG = "terragucci";

const seconds = (d: string): number => Math.round((durationMs(d) ?? 0) / 1000);

const spans = spanMetricsNames(SPANMETRICS);
const CALLS = spans.calls.prometheus;
const DURATION_BUCKETS = `${spans.duration!.prometheus}_bucket`;
const STATUS = spans.labels.statusCode!;
const STAGE_L = "terragucci_stage";
const PROJECT_L = "terragucci_project";
const RESULT_L = "terragucci_result";

const prom = (uid: string) => ({ type: "prometheus" as const, uid });
const tempo = (uid: string) => ({ type: "tempo" as const, uid });

/** `max by (labels) (last_over_time(metric{matchers}[range]))`: each group's latest value over the range. */
const latest = (metric: string, matchers: Matcher[], by: string[], range = "$__range"): string =>
  `max by (${by.join(", ")}) (last_over_time(${selector(metric, matchers)}[${range}]))`;

/**
 * Things still open: what has a `since` time later than its last `settled`
 * time, or no settled time at all, per group. The value is the since time.
 */
const stillOpen = (since: string, settled: string, by: string[]): string =>
  `(\n(${since}) unless on (${by.join(", ")}) (${settled})\n)\nor\n(\n(${since}) > on (${by.join(", ")}) (${settled})\n)`;

const projectVar = (ds: ReturnType<typeof prom>, metric: string, label: string) =>
  new QueryVariable({
    name: "project",
    label: "Project",
    datasource: ds,
    query: `label_values(${metric}, ${label})`,
    multi: true,
    includeAll: true,
    allValue: ".+",
    refresh: "onTimeRangeChange",
    sort: 1,
  });

const P: Matcher = ["project", "=~", "$project"];
const SP: Matcher = [PROJECT_L, "=~", "$project"];

// eslint-disable-next-line @typescript-eslint/no-explicit-any
const table = (title: string, description: string, ds: ReturnType<typeof prom>, expr: string, w = 12, h = 8, overrides: any[] = []) =>
  new TablePanel({
    title,
    description,
    datasource: ds,
    gridPos: { w, h },
    targets: [new PromQuery({ expr, instant: true, range: false, format: "table" })],
    ...(overrides.length ? { fieldConfig: { overrides } } : {}),
  });

const series = (title: string, description: string, ds: ReturnType<typeof prom>, expr: string, legend: string, unit = "short", w = 12) =>
  new TimeSeriesPanel({
    title,
    description,
    datasource: ds,
    gridPos: { w, h: 8 },
    targets: [new PromQuery({ expr, legendFormat: legend })],
    fieldConfig: { defaults: { unit } },
  });

const stat = (title: string, description: string, ds: ReturnType<typeof prom>, expr: string, unit = "short", w = 6) =>
  new StatPanel({
    title,
    description,
    datasource: ds,
    gridPos: { w, h: 5 },
    targets: [new PromQuery({ expr, instant: true, range: false })],
    options: { colorMode: "none", graphMode: "none", reduceOptions: { calcs: ["lastNotNull"] } },
    fieldConfig: { defaults: { unit } },
  });

function dashboard(s: Required<DashboardSettings>, uid: string, title: string, description: string, panels: DashboardItem[], variables: unknown[], time = "now-7d", links: { title: string; url: string }[] = []): DashboardEntity {
  return new Dashboard({
    title,
    uid,
    description,
    tags: [DASHBOARD_TAG],
    ...(links.length ? { links: links.map((l) => ({ ...l, type: "link" as const, targetBlank: true, icon: "doc" as const })) } : {}),
    time: { from: time, to: "now" },
    refresh: "1m",
    graphTooltip: "sharedCrosshair",
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    variables: variables as any,
    panels,
  });
}

/** Rate, errors and duration of the stages, from the span metrics of the stage spans (the RED queries of grafana's RedDashboard, by stage and project). */
function pipelineHealth(s: Required<DashboardSettings>): DashboardEntity {
  const ds = prom(s.prometheus);
  const stage = new QueryVariable({
    name: "stage",
    label: "Stage",
    datasource: ds,
    query: `label_values(${CALLS}, ${STAGE_L})`,
    multi: true,
    includeAll: true,
    allValue: ".+",
    refresh: "onTimeRangeChange",
    sort: 1,
  });
  // A stage span carries the stage and the project; root and binary spans carry neither, so `.+` leaves them out.
  const scope: Matcher[] = [[STAGE_L, "=~", "$stage"], SP];
  const by = [STAGE_L, PROJECT_L];
  const calls = selector(CALLS, scope);
  const errors = selector(CALLS, [...scope, [STATUS, "=", spans.errorStatus]]);
  const buckets = selector(DURATION_BUCKETS, scope);
  const legend = `{{${STAGE_L}}} {{${PROJECT_L}}}`;
  return dashboard(s, DASHBOARD_UIDS.pipeline, "terragucci: Pipeline health", "Runs, errors and duration per stage and project, from the stage spans.", [
    new Row({
      title: "Rate and errors",
      panels: [
        series("Runs per hour", "Stage runs per hour, by stage and project.", ds, `sum by (${by.join(", ")}) (increase(${calls}[1h]))`, legend),
        new TimeSeriesPanel({
          title: "Errors",
          description: "Share of stage runs that failed, by stage and project.",
          datasource: ds,
          gridPos: { w: 12, h: 8 },
          targets: [new PromQuery({ expr: errorRatio(errors, calls, by), legendFormat: legend })],
          fieldConfig: { defaults: { unit: "percentunit", min: 0 } },
        }),
      ],
    }),
    new Row({
      title: "Duration",
      panels: [0.5, 0.95].map((q) =>
        series(`Duration p${q * 100}`, `p${q * 100} stage duration, by stage and project.`, ds, quantile(q, buckets, by), legend, "s"),
      ),
    }),
    new Row({
      title: "Results",
      panels: [table("Runs by result", "Stage runs over the dashboard's range, by stage and how they ended.", ds, `sum by (${STAGE_L}, ${RESULT_L}) (increase(${calls}[$__range]))`, 24)],
    }),
  ], [projectVar(ds, CALLS, PROJECT_L), stage]);
}

/** Roots and groups per pull request, and what the plans propose over time. */
function changeReview(s: Required<DashboardSettings>): DashboardEntity {
  const ds = prom(s.prometheus);
  const plan: Matcher[] = [["stage", "=", "tf-plan"], P];
  return dashboard(s, DASHBOARD_UIDS.changes, "terragucci: Change review", "What each pull request's plan reaches, and the creates, replaces and destroys proposed over time.", [
    new Row({
      title: "Pull requests",
      panels: [
        table("Roots changed per pull request", "Roots whose plan changes something, by project and pull request, from the latest plan of each.", ds, latest(METRIC.rootsChanged, plan, ["project", "pull_request"])),
        table("Groups per pull request", "Groups the plans fold into, by project and pull request.", ds, latest(METRIC.planGroups, plan, ["project", "pull_request"])),
      ],
    }),
    new Row({
      title: "Changes",
      panels: [
        series("Changes by action", "Proposed changes in each plan run, by action.", ds, `sum by (action) (${selector(METRIC.planChanges, plan)})`, "{{action}}", "short", 24),
        stat("Creates", "Creates proposed over the range, the largest plan of each project and pull request.", ds, `sum(max by (project, pull_request) (max_over_time(${selector(METRIC.planChanges, [...plan, ["action", "=", "create"]])}[$__range])))`),
        stat("Updates", "Updates proposed over the range.", ds, `sum(max by (project, pull_request) (max_over_time(${selector(METRIC.planChanges, [...plan, ["action", "=", "update"]])}[$__range])))`),
        stat("Replaces", "Replacements proposed over the range.", ds, `sum(max by (project, pull_request) (max_over_time(${selector(METRIC.planChanges, [...plan, ["action", "=", "replace"]])}[$__range])))`),
        stat("Destroys", "Destroys proposed over the range.", ds, `sum(max by (project, pull_request) (max_over_time(${selector(METRIC.planChanges, [...plan, ["action", "=", "delete"]])}[$__range])))`),
      ],
    }),
  ], [projectVar(ds, METRIC.lastRun, "project")]);
}

/** The waves still waiting for an approval, per project and wave: the time each started waiting. */
export function wavesWaiting(matchers: Matcher[] = [P], range = "7d"): string {
  return stillOpen(latest(METRIC.waveWaitingSince, matchers, ["project", "wave"], range), latest(METRIC.waveSettled, matchers, ["project", "wave"], range), ["project", "wave"]);
}

/** The projects whose drift is still open: the time it was first seen. */
export function driftOpen(matchers: Matcher[] = [P], range = "7d"): string {
  return stillOpen(latest(METRIC.driftSince, matchers, ["project"], range), latest(METRIC.driftClear, matchers, ["project"], range), ["project"]);
}

function rolloutsAndWaves(s: Required<DashboardSettings>): DashboardEntity {
  const ds = prom(s.prometheus);
  const apply = selector(CALLS, [[STAGE_L, "=", "tf-apply"], SP]);
  return dashboard(s, DASHBOARD_UIDS.waves, "terragucci: Rollouts and waves", "Waves waiting for an approval and for how long, how wave runs ended, and how far each module version has rolled out.", [
    new Row({
      title: "Waiting",
      panels: [
        stat("Waves waiting", "Waves whose latest run waits for an approval of its digest.", ds, `count(${wavesWaiting()})`),
        table("Waiting for", "Each waiting wave, and how long since it first asked for an approval.", ds, `time() - (${wavesWaiting()})`, 18),
      ],
    }),
    new Row({
      title: "Wave runs",
      panels: [
        table("Wave runs by result", "tf-apply runs over the range: applied, nothing to apply, waiting for an approval, refused because the plans moved after approval, or failed.", ds, `sum by (${PROJECT_L}, ${RESULT_L}) (increase(${apply}[$__range]))`),
        series("Refused and failed waves", "Wave runs refused or failed per hour.", ds, `sum by (${RESULT_L}) (increase(${selector(CALLS, [[STAGE_L, "=", "tf-apply"], [RESULT_L, "=~", "refused|failed"], SP])}[1h]))`, `{{${RESULT_L}}}`),
        table("Roots per wave", "Roots in each wave of the latest apply run, by project.", ds, latest(METRIC.waveRoots, [P], ["project", "wave"])),
      ],
    }),
    new Row({
      title: "Rollouts",
      panels: [
        table("Roots per module version", "How many roots pin each module version, across the projects: a rollout's progress.", ds, `count by (module, version) (${latest(METRIC.modulePin, [P], ["project", "root", "module", "version"], "7d")})`, 24),
      ],
    }),
  ], [projectVar(ds, METRIC.lastRun, "project")]);
}

function drift(s: Required<DashboardSettings>): DashboardEntity {
  const ds = prom(s.prometheus);
  const roots = selector(METRIC.driftRoots, [P]);
  return dashboard(s, DASHBOARD_UIDS.drift, "terragucci: Drift", "Drifted roots by project, how long the drift has stood, and the roots corrected.", [
    new Row({
      title: "Drift",
      panels: [
        series("Drifted roots", "Roots each drift run found drifted, by project.", ds, `max by (project) (${roots})`, "{{project}}", "short", 24),
        table("Drift age", "How long since each project's open drift was first found (its drift issue opened).", ds, `time() - (${driftOpen()})`),
        table("Roots corrected", "Drifted roots fewer than the day before, by project.", ds, `clamp_min(max by (project) (max_over_time(${roots}[1d] offset 1d)) - max by (project) (max_over_time(${roots}[1d])), 0)`),
      ],
    }),
  ], [projectVar(ds, METRIC.lastRun, "project")]);
}

/** A table field override: each cell of `field` links to `url`, where `${__value.raw}` and `${__data.fields.<name>}` are the row's values. */
const fieldLink = (field: string, title: string, url: string) => ({
  matcher: { id: "byName", options: field },
  properties: [{ id: "links", value: [{ title, url, targetBlank: true }] }],
});

/** The URL of the report index of the project a cell names. */
export const projectIndexUrl = (reports: string): string => `${reports}/\${__value.raw}/index.html`;
/** The URL of the page that sends a trace's reader to its run's report. */
export const traceReportUrl = (reports: string): string => `${reports}/traces/\${__data.fields.traceID}.html`;

function estate(s: Required<DashboardSettings>, links: DashboardLinks): DashboardEntity {
  const ds = prom(s.prometheus);
  // Each project links to its report index in the bucket.
  const perProject = table(
    "Roots per project",
    `Roots in each project's latest plan or drift run.${links.reports ? " Each project links to its report index." : ""}`,
    ds,
    latest(METRIC.rootsPlanned, [["stage", "=~", "tf-plan|tf-drift"], P], ["project"], "7d"),
    12,
    8,
    links.reports ? [fieldLink("project", "Report index", projectIndexUrl(links.reports))] : [],
  );
  return dashboard(s, DASHBOARD_UIDS.estate, "terragucci: Estate", "Roots per project, the binary and terragucci versions they run, module pins across repos and tips by rule.", [
    new Row({
      title: "Projects",
      panels: [
        perProject,
        table("Versions", "The binary, its version and the terragucci release each project's latest run used.", ds, `count by (project, binary, version, service_version) (last_over_time(${selector(METRIC.binaryVersion, [P])}[7d]))`),
      ],
    }),
    new Row({
      title: "Modules and tips",
      panels: [
        table("Module pins", "Each module call's pin, by project and root.", ds, latest(METRIC.modulePin, [P], ["project", "root", "module", "version"], "7d")),
        table("Tips by rule", "Tips the latest run of each project gave, by rule.", ds, `sum by (rule) (${latest(METRIC.tips, [P], ["project", "rule"], "7d")})`),
      ],
    }),
  ], [projectVar(ds, METRIC.lastRun, "project")], undefined, links.reports ? [{ title: "Report index", url: `${links.reports}/index.html` }] : []);
}

function runs(s: Required<DashboardSettings>, links: DashboardLinks): DashboardEntity {
  const ds = prom(s.prometheus);
  const t = tempo(s.tempo);
  const top = (metric: string, by: string[]) => `topk(10, max by (${by.join(", ")}) (max_over_time(${selector(metric, [P])}[$__range])))`;
  return dashboard(s, DASHBOARD_UIDS.runs, "terragucci: Runs", "Where the runs spend their time: the slowest roots and resources, provider init, lock waits, and the trace of any run.", [
    new Row({
      title: "Slowest",
      panels: [
        table("Slowest roots", "The ten slowest root plans over the range, in seconds.", ds, top(METRIC.rootPlan, ["project", "root"])),
        table("Slowest root applies", "The ten slowest root applies over the range, in seconds.", ds, top(METRIC.rootApply, ["project", "root"])),
        table("Slowest resources", "The ten slowest resources over the range, from the binary's spans, in seconds.", ds, top(METRIC.resource, ["project", "root", "address"])),
        table("Provider init", "Time spent starting each provider, in seconds.", ds, top(METRIC.providerInit, ["project", "provider"])),
        table("Lock waits", "Time spent waiting for a state lock, by root, in seconds.", ds, top(METRIC.lockWait, ["project", "root"])),
      ],
    }),
    new Row({
      title: "Stages",
      panels: [series("Stage duration", "How long each stage run took.", ds, `max by (project, stage) (${selector(METRIC.stageDuration, [P])})`, "{{project}} {{stage}}", "s", 24)],
    }),
    new Row({
      title: "Traces",
      panels: [
        new TablePanel({
          title: "Runs",
          description: links.reports
            ? "The trace of each stage run. Open one to see its waves, roots and the binary's own spans; a run's name links to its report."
            : "The trace of each stage run. Open one to see its waves, roots and the binary's own spans.",
          datasource: t,
          gridPos: { w: 24, h: 10 },
          targets: [new TempoQuery({ queryType: "traceql", query: `{ resource.service.name = "terragucci" && name =~ "terragucci .*" && span.terragucci.project =~ "$project" }`, limit: 50, tableType: "traces" })],
          // The trace id keeps Grafana's own link to the trace; the name links the run's report.
          ...(links.reports ? { fieldConfig: { overrides: [fieldLink("traceName", "Report", traceReportUrl(links.reports))] }, links: [{ title: "Report index", url: `${links.reports}/index.html`, targetBlank: true }] } : {}),
        }),
      ],
    }),
  ], [projectVar(ds, METRIC.lastRun, "project")], undefined, links.reports ? [{ title: "Report index", url: `${links.reports}/index.html` }] : []);
}

/** The three SLOs: plans finish within ten minutes, applies succeed, drift is corrected within a day. */
export function slos(): Record<keyof typeof SLO_NAMES, SloInstance> {
  const plan = [[STAGE_L, "=", "tf-plan"]] as Matcher[];
  const apply = [[STAGE_L, "=", "tf-apply"]] as Matcher[];
  return {
    plans: Slo({
      name: SLO_NAMES.plans,
      objective: 0.95,
      window: "28d",
      description: `Plans finish within ${PLAN_SLO_SECONDS / 60} minutes.`,
      sli: {
        good: `sum by (${PROJECT_L}) (rate(${selector(DURATION_BUCKETS, [...plan, ["le", "=~", `${PLAN_SLO_SECONDS}(\\.0)?`]])}[{{window}}]))`,
        total: `sum by (${PROJECT_L}) (rate(${selector(`${spans.duration!.prometheus}_count`, plan)}[{{window}}]))`,
      },
    }),
    applies: Slo({
      name: SLO_NAMES.applies,
      objective: 0.99,
      window: "28d",
      description: "Wave applies succeed.",
      sli: {
        errors: `sum by (${PROJECT_L}) (rate(${selector(CALLS, [...apply, [RESULT_L, "=", "failed"]])}[{{window}}]))`,
        total: `sum by (${PROJECT_L}) (rate(${selector(CALLS, [...apply, [RESULT_L, "=~", "applied|failed"]])}[{{window}}]))`,
      },
    }),
    drift: Slo({
      name: SLO_NAMES.drift,
      objective: 0.9,
      window: "28d",
      description: "Drift is corrected within a day.",
      // A 10% budget cannot burn at a paging rate; slow burns open a ticket.
      alerting: { page: false },
      sli: {
        good: `sum by (project) (count_over_time((${METRIC.driftRoots} == 0 or (time() - ${METRIC.driftSince}) <= 86400)[{{window}}:5m]))`,
        total: `sum by (project) (count_over_time(${METRIC.driftRoots}[{{window}}:5m]))`,
      },
    }),
  };
}

/** The pipeline alerts: drift too old, a wave waiting too long, a failed apply, a refused wave, a drift run that stopped. */
export function pipelineAlerts(s: Required<DashboardSettings>): RuleGroupEntity {
  const any: Matcher[] = [];
  return new RuleGroup({
    name: "terragucci",
    rules: [
      {
        alert: "TerragucciDriftOld",
        expr: `time() - (${driftOpen(any)}) > ${seconds(s.drift_age)}`,
        labels: { severity: "ticket" },
        annotations: { summary: `{{ $labels.project }} has drift older than ${s.drift_age}`, description: "Its drift issue names the roots. Correct the drift with a pull request, or apply the code as it is." },
      },
      {
        alert: "TerragucciWaveWaiting",
        expr: `time() - (${wavesWaiting(any)}) > ${seconds(s.wave_wait)}`,
        labels: { severity: "ticket" },
        annotations: { summary: `wave {{ $labels.wave }} of {{ $labels.project }} has waited for an approval longer than ${s.wave_wait}`, description: "Its apply job printed the chant approve command for its digest." },
      },
      {
        alert: "TerragucciApplyFailed",
        expr: `sum by (${PROJECT_L}) (increase(${selector(CALLS, [[STAGE_L, "=", "tf-apply"], [RESULT_L, "=", "failed"]])}[1h])) > 0`,
        labels: { severity: "page" },
        annotations: { summary: `an apply of {{ $labels.${PROJECT_L} }} failed in the last hour`, description: "The apply job's log and the triage response name the error." },
      },
      {
        alert: "TerragucciWaveRefused",
        expr: `sum by (${PROJECT_L}) (increase(${selector(CALLS, [[STAGE_L, "=", "tf-apply"], [RESULT_L, "=", "refused"]])}[1h])) > 0`,
        labels: { severity: "ticket" },
        annotations: { summary: `a wave of {{ $labels.${PROJECT_L} }} was refused: its plans moved after approval`, description: "The wave applied nothing. Read what moved, then approve the new digest." },
      },
      {
        alert: "TerragucciDriftStopped",
        expr: `time() - max by (project) (last_over_time(${selector(METRIC.lastRun, [["stage", "=", "tf-drift"]])}[30d])) > ${seconds(s.schedule)}`,
        labels: { severity: "ticket" },
        annotations: { summary: `{{ $labels.project }}'s drift run has not run for ${s.schedule}`, description: "Its schedule stopped, or every run failed before it could report." },
      },
    ],
  });
}

/** Every entity the dashboards and rules are built from. */
export function dashboardEntities(settings: Required<DashboardSettings>, links: DashboardLinks = {}): { grafana: Declarable[]; prometheus: Declarable[] } {
  const s = settings;
  const ds = prom(s.prometheus);
  const sl = slos();
  const grafana: Declarable[] = [
    new DashboardProvider({ name: "terragucci", folder: s.folder, path: s.path, foldersFromFilesStructure: false }),
    pipelineHealth(s),
    changeReview(s),
    rolloutsAndWaves(s),
    drift(s),
    estate(s, links),
    runs(s, links),
  ];
  for (const slo of Object.values(sl)) {
    grafana.push(SloDashboard({ slo, datasource: ds, tags: [DASHBOARD_TAG, "slo"] }).dashboard);
    grafana.push(SloAlertRules({ slo, datasource: ds, folder: s.folder, group: `${slo.rules.groupName}-grafana` }).rules);
  }
  return { grafana, prometheus: [...Object.values(sl).map((x) => x.rules), pipelineAlerts(s)] };
}

export interface RenderedFile {
  /** Relative to the repo. */
  path: string;
  content: string;
}

/**
 * The files `dashboards:` puts in the repo, under its `dir`:
 *
 *   grafana/dashboards/<uid>.json                 one per dashboard
 *   grafana/provisioning/dashboards/terragucci.yaml   the provider that loads them
 *   grafana/provisioning/alerting/terragucci.yaml     the SLO burn-rate alerts, Grafana-managed
 *   prometheus/terragucci.rules.yml               the SLO recording rules and alerts, and the pipeline alerts
 */
export function renderDashboards(settings: Required<DashboardSettings>, links: DashboardLinks = {}): RenderedFile[] {
  const dir = settings.dir.replace(/\/+$/, "");
  const { grafana, prometheus } = dashboardEntities(settings, links);
  const built = buildGrafana(grafana);
  const out: RenderedFile[] = [];
  for (const d of built.dashboards) out.push({ path: `${dir}/grafana/dashboards/${d.uid}.json`, content: built.files[d.file] });
  const provider = built.files["provisioning/dashboards/chant.yaml"];
  if (provider) out.push({ path: `${dir}/grafana/provisioning/dashboards/terragucci.yaml`, content: `${YAML_MARKER}\n${provider}` });
  const alerting = built.files["provisioning/alerting/chant.yaml"];
  if (alerting) out.push({ path: `${dir}/grafana/provisioning/alerting/terragucci.yaml`, content: `${YAML_MARKER}\n${alerting}` });
  out.push({ path: `${dir}/prometheus/terragucci.rules.yml`, content: `${YAML_MARKER}\n${emitYaml(buildRuleFile(prometheus).config)}` });
  return out.sort((a, b) => (a.path < b.path ? -1 : 1));
}

/** Whether a file at a dashboards path is one terragucci wrote: a YAML file with the marker, or a dashboard tagged terragucci. */
export function writtenByTerragucci(path: string, text: string): boolean {
  if (!path.endsWith(".json")) return text.startsWith(YAML_MARKER);
  try {
    const tags = (JSON.parse(text) as { tags?: unknown }).tags;
    return Array.isArray(tags) && tags.includes(DASHBOARD_TAG);
  } catch {
    return false;
  }
}
