/**
 * What the dashboards' declarations (index.ts) and the files `init` writes
 * from them (files.ts) share: the settings and their defaults, the uids, the
 * marker on each file. Plain data with no lexicon imports, so the bundle
 * carries it.
 */
import type { DashboardSettings } from "../config";

export type { DashboardSettings };

export const DASHBOARD_DEFAULTS: Required<DashboardSettings> = {
  dir: "observability/terragucci",
  prometheus: "prometheus",
  tempo: "tempo",
  folder: "terragucci",
  path: "/var/lib/grafana/dashboards/terragucci",
  drift_age: "1d",
  wave_wait: "4h",
  schedule: "2d",
};

/**
 * Where the dashboards link down to: `reports` is the address of the reports
 * bucket's prefix (`reports.url` and `reports.prefix`), when terragucci.yml
 * says where the bucket is served. Without it the dashboards link nothing
 * outside Grafana.
 */
export interface DashboardLinks {
  reports?: string;
}

/** The settings with every default filled in. */
export function dashboardSettings(s: boolean | DashboardSettings | undefined): Required<DashboardSettings> | undefined {
  if (!s) return undefined;
  return { ...DASHBOARD_DEFAULTS, ...(s === true ? {} : s) };
}

/** Each dashboard's uid: what a link, the provisioning and the smoke claims address it by. */
export const DASHBOARD_UIDS = {
  pipeline: "terragucci-pipeline-health",
  changes: "terragucci-change-review",
  waves: "terragucci-rollouts-waves",
  drift: "terragucci-drift",
  estate: "terragucci-estate",
  runs: "terragucci-runs",
} as const;

/** The SLOs, by the name their recorded series carry in the `slo` label. */
export const SLO_NAMES = {
  plans: "terragucci-plan-time",
  applies: "terragucci-apply-success",
  drift: "terragucci-drift-corrected",
} as const;

/** The first line of every YAML file terragucci writes here; init leaves a file without it alone. */
export const YAML_MARKER = "# Generated by terragucci from terragucci.yml (dashboards). Edit terragucci.yml, then run terragucci init.";
/** The tag on every dashboard terragucci writes. */
export const DASHBOARD_TAG = "terragucci";

export interface RenderedFile {
  /** Relative to the repo. */
  path: string;
  content: string;
}

/** Whether a file at a dashboards path is one terragucci wrote: a YAML file with the marker, or a dashboard tagged terragucci. */
export function writtenByTerragucci(path: string, text: string): boolean {
  if (!path.endsWith(".json")) return text.startsWith(YAML_MARKER);
  try {
    const tags = (JSON.parse(text) as { tags?: unknown }).tags;
    return Array.isArray(tags) && tags.includes(DASHBOARD_TAG);
  } catch {
    return false;
  }
}
