// The comparison's rows and every other product's marks. Each mark was
// read from the page its source names, in that product's own docs; where a
// product's docs say nothing about a row, the text says so and the mark is
// the conservative one. terragucci's own column is in ./marks.ts.
import type { Product, Row } from './types';

export const products: Product[] = [
	{ id: 'atlantis', name: 'Atlantis' },
	{ id: 'hcp', name: 'HCP Terraform' },
	{ id: 'spacelift', name: 'Spacelift' },
	{ id: 'opentaco', name: 'OpenTaco' },
];

const atlantis = {
	server: { title: 'Server configuration', url: 'https://www.runatlantis.io/docs/server-configuration' },
	api: { title: 'API endpoints', url: 'https://www.runatlantis.io/docs/api-endpoints' },
	policy: { title: 'Policy checking', url: 'https://www.runatlantis.io/docs/policy-checking' },
	automerge: { title: 'Automerging', url: 'https://www.runatlantis.io/docs/automerging' },
	commandRequirements: { title: 'Command requirements', url: 'https://www.runatlantis.io/docs/command-requirements' },
	repoYaml: { title: 'Repo level atlantis.yaml', url: 'https://www.runatlantis.io/docs/repo-level-atlantis-yaml' },
	locking: { title: 'Locking', url: 'https://www.runatlantis.io/docs/locking' },
	workflows: { title: 'Custom workflows', url: 'https://www.runatlantis.io/docs/custom-workflows' },
	faq: { title: 'FAQ', url: 'https://www.runatlantis.io/docs/faq' },
	deployment: { title: 'Deployment', url: 'https://www.runatlantis.io/docs/deployment' },
	credentials: { title: 'Provider credentials', url: 'https://www.runatlantis.io/docs/provider-credentials' },
	stats: { title: 'Metrics', url: 'https://www.runatlantis.io/docs/stats' },
	licence: { title: 'LICENSE', url: 'https://github.com/runatlantis/atlantis/blob/main/LICENSE' },
	home: { title: 'Atlantis home page', url: 'https://www.runatlantis.io/' },
	logs: { title: 'Real-time logs', url: 'https://www.runatlantis.io/docs/streaming-logs' },
	introducing: { title: 'Introducing Atlantis', url: 'https://www.runatlantis.io/blog/2017/introducing-atlantis' },
	cncf: { title: 'CNCF project page', url: 'https://www.cncf.io/projects/atlantis/' },
	requirements: { title: 'Requirements', url: 'https://www.runatlantis.io/docs/requirements' },
	using: { title: 'Using Atlantis', url: 'https://www.runatlantis.io/docs/using-atlantis' },
};

const hcp = {
	ui: { title: 'The UI- and VCS-driven run workflow', url: 'https://developer.hashicorp.com/terraform/cloud-docs/workspaces/run/ui' },
	vcs: { title: 'Workspace VCS settings', url: 'https://developer.hashicorp.com/terraform/cloud-docs/workspaces/settings/vcs' },
	plans: { title: 'Plans API', url: 'https://developer.hashicorp.com/terraform/cloud-docs/api-docs/plans' },
	policySets: { title: 'Manage policy sets', url: 'https://developer.hashicorp.com/terraform/cloud-docs/policy-enforcement/manage-policy-sets' },
	policyResults: { title: 'View policy results', url: 'https://developer.hashicorp.com/terraform/cloud-docs/workspaces/policy-enforcement/view-results' },
	remote: { title: 'Remote operations', url: 'https://developer.hashicorp.com/terraform/cloud-docs/workspaces/run/remote-operations' },
	stacks: { title: 'Stacks deployment conditions', url: 'https://developer.hashicorp.com/terraform/language/stacks/deploy/conditions' },
	cli: { title: 'The CLI-driven run workflow', url: 'https://developer.hashicorp.com/terraform/cloud-docs/workspaces/run/cli' },
	runTriggers: { title: 'Run triggers', url: 'https://developer.hashicorp.com/terraform/cloud-docs/workspaces/settings/run-triggers' },
	auditTrails: { title: 'Audit trails API', url: 'https://developer.hashicorp.com/terraform/cloud-docs/api-docs/audit-trails' },
	settings: { title: 'Workspace settings', url: 'https://developer.hashicorp.com/terraform/cloud-docs/workspaces/settings' },
	runEnv: { title: 'Run environment', url: 'https://developer.hashicorp.com/terraform/cloud-docs/workspaces/run/run-environment' },
	health: { title: 'Health assessments', url: 'https://developer.hashicorp.com/terraform/cloud-docs/workspaces/health' },
	cloudSettings: { title: 'HCP Terraform settings', url: 'https://developer.hashicorp.com/terraform/cli/cloud/settings' },
	dynamic: { title: 'Dynamic provider credentials', url: 'https://developer.hashicorp.com/terraform/cloud-docs/dynamic-provider-credentials' },
	telemetry: { title: 'Agent telemetry', url: 'https://developer.hashicorp.com/terraform/cloud-docs/agents/telemetry' },
	registry: { title: 'Publish modules', url: 'https://developer.hashicorp.com/terraform/cloud-docs/registry/publish-modules' },
	overview: { title: 'HCP Terraform overview', url: 'https://developer.hashicorp.com/terraform/cloud-docs/overview' },
	announce: { title: 'Announcing Terraform Cloud', url: 'https://www.hashicorp.com/en/blog/announcing-terraform-cloud' },
	product: { title: 'Terraform product page', url: 'https://www.hashicorp.com/en/products/terraform' },
	signUp: { title: 'Sign up for HCP Terraform', url: 'https://developer.hashicorp.com/terraform/tutorials/cloud-get-started/cloud-sign-up' },
	vcsProviders: { title: 'Connecting VCS providers', url: 'https://developer.hashicorp.com/terraform/cloud-docs/vcs' },
};

const spacelift = {
	prComments: { title: 'Pull request comments', url: 'https://docs.spacelift.io/concepts/run/pull-request-comments' },
	github: { title: 'GitHub integration', url: 'https://docs.spacelift.io/integrations/source-control/github' },
	stackSettings: { title: 'Stack settings', url: 'https://docs.spacelift.io/concepts/stack/stack-settings' },
	api: { title: 'API', url: 'https://docs.spacelift.io/integrations/api' },
	policy: { title: 'Policies', url: 'https://docs.spacelift.io/concepts/policy' },
	planPolicy: { title: 'Plan policy', url: 'https://docs.spacelift.io/concepts/policy/terraform-plan-policy' },
	promotion: { title: 'Run promotion', url: 'https://docs.spacelift.io/concepts/run/run-promotion' },
	approval: { title: 'Approval policy', url: 'https://docs.spacelift.io/concepts/policy/approval-policy' },
	dependencies: { title: 'Stack dependencies', url: 'https://docs.spacelift.io/concepts/stack/stack-dependencies' },
	run: { title: 'Runs', url: 'https://docs.spacelift.io/concepts/run' },
	runAll: { title: 'Terragrunt run-all', url: 'https://docs.spacelift.io/vendors/terragrunt/run-all' },
	terragrunt: { title: 'Terragrunt limitations', url: 'https://docs.spacelift.io/vendors/terragrunt/limitations' },
	drift: { title: 'Drift detection', url: 'https://docs.spacelift.io/concepts/stack/drift-detection' },
	workers: { title: 'Worker pools', url: 'https://docs.spacelift.io/concepts/worker-pools' },
	creating: { title: 'Creating a stack', url: 'https://docs.spacelift.io/concepts/stack/creating-a-stack' },
	cloud: { title: 'Cloud providers', url: 'https://docs.spacelift.io/integrations/cloud-providers' },
	prometheus: { title: 'Prometheus exporter', url: 'https://docs.spacelift.io/integrations/observability/prometheus' },
	datadog: { title: 'Datadog integration', url: 'https://docs.spacelift.io/integrations/observability/datadog' },
	registry: { title: 'Module registry', url: 'https://docs.spacelift.io/vendors/terraform/module-registry' },
	pricing: { title: 'Pricing', url: 'https://spacelift.io/pricing' },
	start: { title: 'Getting started', url: 'https://docs.spacelift.io/getting-started' },
	home: { title: 'Getting started with Spacelift Deploy', url: 'https://docs.spacelift.io/' },
	selfHosted: { title: 'Spacelift Self-Hosted', url: 'https://docs.spacelift.io/self-hosted' },
	careers: { title: 'Careers at Spacelift', url: 'https://careers.spacelift.io/' },
	customers: { title: 'Customer success stories', url: 'https://spacelift.io/customers' },
	tgVendor: { title: 'Terragrunt', url: 'https://docs.spacelift.io/vendors/terragrunt' },
	gitlab: { title: 'GitLab integration', url: 'https://docs.spacelift.io/integrations/source-control/gitlab' },
};

// OpenTaco's pages are on docs.opentaco.dev; the GitLab and Buildkite pages
// and the enterprise licence are only in its repository.
const opentaco = {
	noise: { title: 'Reducing PR noise', url: 'https://docs.opentaco.dev/ce/howto/noise-reduction' },
	include: { title: 'Include and exclude patterns', url: 'https://docs.opentaco.dev/ce/howto/include-exclude-patterns' },
	api: { title: 'Orchestrator API', url: 'https://docs.opentaco.dev/ce/reference/api' },
	conftest: { title: 'Inline policies (conftest)', url: 'https://docs.opentaco.dev/ce/howto/using-opa-conftest' },
	applyOnMerge: { title: 'Apply on merge', url: 'https://docs.opentaco.dev/ce/howto/apply-on-merge' },
	requirements: { title: 'Apply requirements', url: 'https://docs.opentaco.dev/ce/howto/apply-requirements' },
	layering: { title: 'Dependencies and layering', url: 'https://docs.opentaco.dev/ce/features/layering' },
	commentops: { title: 'CommentOps', url: 'https://docs.opentaco.dev/ce/features/commentops' },
	gcpLocks: { title: 'GCP: setup with GitHub Actions', url: 'https://docs.opentaco.dev/ce/gcp/setting-up-gcp-+-gh-actions' },
	terragrunt: { title: 'Terragrunt parsing', url: 'https://docs.opentaco.dev/ce/reference/terragrunt-parsing' },
	drift: { title: 'Drift detection', url: 'https://docs.opentaco.dev/ce/drift/overview' },
	backendless: { title: 'Backendless mode', url: 'https://docs.opentaco.dev/ce/howto/backendless-mode' },
	state: { title: 'State management', url: 'https://docs.opentaco.dev/introduction/state-management' },
	remoteRuns: { title: 'Remote runs', url: 'https://docs.opentaco.dev/introduction/remote-runs' },
	oidc: { title: 'AWS: authenticate with OIDC', url: 'https://docs.opentaco.dev/ce/cloud-providers/authenticating-with-oidc-on-aws' },
	telemetry: { title: 'Disable telemetry', url: 'https://docs.opentaco.dev/ce/howto/disable-telemetry' },
	features: { title: 'PR automation overview', url: 'https://docs.opentaco.dev/ce/features/overview' },
	gitlab: { title: 'GitLab', url: 'https://github.com/diggerhq/digger/blob/develop/docs/ce/features/gitlab.mdx' },
	buildkite: { title: 'Buildkite', url: 'https://github.com/diggerhq/digger/blob/develop/docs/ce/features/buildkite.mdx' },
	fips: { title: 'FIPS 140 standard', url: 'https://docs.opentaco.dev/ce/features/fips-140' },
	licence: { title: 'Enterprise LICENSE', url: 'https://github.com/diggerhq/digger/blob/develop/ee/LICENSE' },
	account: { title: 'Set up your OpenTaco account', url: 'https://docs.opentaco.dev/onboarding/account-setup' },
	remoteJobs: { title: 'Onboarding: Remote Runs', url: 'https://docs.opentaco.dev/onboarding/remote-jobs' },
	architecture: { title: 'System architecture', url: 'https://docs.opentaco.dev/self-host-and-develop/system-architecture' },
	workos: { title: 'WorkOS setup', url: 'https://docs.opentaco.dev/self-hosting/workos-setup' },
	usingTerragrunt: { title: 'Using Terragrunt', url: 'https://docs.opentaco.dev/ce/howto/using-terragrunt' },
	readme: { title: 'README', url: 'https://github.com/diggerhq/digger#readme' },
	releases: { title: 'Releases', url: 'https://github.com/diggerhq/digger/releases' },
};

export const rows: Row[] = [
	{
		id: 'grouped-note',
		label: 'One plan note across many roots',
		statement: 'A single note on the pull request covers every root the change reaches, and roots taking the same change are read once.',
		cells: {
			atlantis: { mark: 'warn', text: 'Comments each command\'s plans on the pull request; the docs describe no grouping of roots whose plans are the same', sources: [atlantis.server] },
			hcp: { mark: 'warn', text: 'A status check and a plan link per connected workspace; the plans are read in the HCP Terraform UI', sources: [hcp.ui] },
			spacelift: { mark: 'warn', text: 'A comment per stack run, turned on by a stack label, with checks per stack or aggregated; no grouping of identical plans', sources: [spacelift.prComments, spacelift.github] },
			opentaco: { mark: 'warn', text: 'A comment for every plan or apply plus a summary comment on top; no grouping of identical plans', sources: [opentaco.noise] },
		},
	},
	{
		id: 'affected-only',
		label: 'Plans only what a change affects',
		statement: 'Only the roots a change reaches are planned, including every root that uses a changed local module.',
		cells: {
			atlantis: { mark: 'good', text: 'With --autoplan-modules, which is off by default, it traces local modules and plans every project that uses a changed one', sources: [atlantis.server] },
			hcp: { mark: 'warn', text: 'Runs are filtered by trigger patterns or path prefixes set per workspace; module use is not followed', sources: [hcp.vcs] },
			spacelift: { mark: 'warn', text: 'Runs start on changes under the project root or the project globs you list; module use is not followed', sources: [spacelift.stackSettings] },
			opentaco: { mark: 'warn', text: 'A Terraform project triggers on the folders you list in include_patterns; Terragrunt projects can cascade to dependents', sources: [opentaco.include, opentaco.terragrunt] },
		},
	},
	{
		id: 'json-report',
		label: 'Plan report as JSON',
		statement: 'The run\'s plans, for every root, as one documented JSON report a script can read.',
		cells: {
			atlantis: { mark: 'warn', text: 'The /api/plan endpoint returns per-project results as JSON, for a run it starts itself; no JSON report of a pull request\'s plans is documented', sources: [atlantis.api] },
			hcp: { mark: 'warn', text: 'The API returns one run\'s raw JSON plan, with a token that has admin access to the workspace', sources: [hcp.plans] },
			spacelift: { mark: 'warn', text: 'A GraphQL API; the docs describe no JSON report of a run\'s plan results', sources: [spacelift.api] },
			opentaco: { mark: 'warn', text: 'Each project\'s plan is written as JSON in the job for steps like conftest; no run-wide report is documented, and the orchestrator\'s API is described as neither stable nor fully documented', sources: [opentaco.conftest, opentaco.api] },
		},
	},
	{
		id: 'policy',
		label: 'Policy checks on the plan',
		statement: 'Policy runs on every plan as part of the product, and the policies live in git where your team reviews them.',
		cells: {
			atlantis: { mark: 'warn', text: 'Conftest policies run on each plan and block apply; policy sets are local paths in the server\'s config, and keeping them in git means mounting them or pulling with conftest --update', sources: [atlantis.policy] },
			hcp: { mark: 'warn', text: 'Sentinel and OPA policy sets; the plan table lists policy enforcement in Standard and Premium only, where sets can also be kept in git', sources: [hcp.overview, hcp.policySets] },
			spacelift: { mark: 'warn', text: 'OPA plan, approval and push policies, managed by Spacelift admins; the pricing page lists the policy engine from Starter+', sources: [spacelift.policy] },
			opentaco: { mark: 'warn', text: 'Conftest runs over Rego in your repo as a workflow step you add; OPA access policies are set through the orchestrator\'s API', sources: [opentaco.conftest, opentaco.api] },
		},
	},
	{
		id: 'override',
		label: 'Policy override',
		statement: 'Named people can let a plan through a failed policy, and the override is recorded.',
		cells: {
			atlantis: { mark: 'good', text: 'Owners named per policy set approve a failure with atlantis approve_policies, and self-approval can be blocked', sources: [atlantis.policy] },
			hcp: { mark: 'warn', text: 'Teams given the manage policy overrides permission can override; audit trails record the override on paid editions, Standard and Premium by the audit trails page and Premium by the plan table', sources: [hcp.policyResults, hcp.auditTrails, hcp.overview] },
			spacelift: { mark: 'warn', text: 'Deny rules fail the run with no override; a warning only flags a tracked run on an autodeploy stack for human review', sources: [spacelift.planPolicy] },
			opentaco: { mark: 'bad', text: 'The docs describe no override of a failed policy check', sources: [opentaco.conftest] },
		},
	},
	{
		id: 'apply-when',
		label: 'Apply before or after merge',
		statement: 'Each project chooses whether a change applies on the open pull request or after merge.',
		cells: {
			atlantis: { mark: 'warn', text: 'Applies on the open pull request, and can merge it once every plan has applied; no apply-after-merge mode is documented', sources: [atlantis.automerge] },
			hcp: { mark: 'warn', text: 'Pull requests get speculative plans only; a VCS-connected workspace applies only after merge, and CLI applies are only for workspaces with no VCS connection', sources: [hcp.ui, hcp.cli] },
			spacelift: { mark: 'good', text: 'Tracked runs apply after merge; run promotion or a push policy deploys a pull request\'s commit before merge, set per stack', sources: [spacelift.promotion] },
			opentaco: { mark: 'good', text: 'Applies on the open pull request by default; a project\'s workflow can apply on merge instead', sources: [opentaco.applyOnMerge] },
		},
	},
	{
		id: 'approval-binds',
		label: 'What an approval binds to',
		statement: 'An approval covers the exact saved plan that applies, and nothing else can apply under it.',
		cells: {
			atlantis: { mark: 'warn', text: 'The approved requirement asks for a pull request approval; apply uses the saved plan file, and the approval does not name it', sources: [atlantis.commandRequirements, atlantis.workflows] },
			hcp: { mark: 'good', text: 'Confirming a run applies that run\'s own plan', sources: [hcp.remote] },
			spacelift: { mark: 'warn', text: 'A review is stored on the run and read by the approval policy; the docs do not say the apply reuses the reviewed plan', sources: [spacelift.approval] },
			opentaco: { mark: 'warn', text: 'The approved requirement checks for a pull request approval, not a particular plan', sources: [opentaco.requirements] },
		},
	},
	{
		id: 'waves',
		label: 'Staged rollout in waves',
		statement: 'Changed roots go out in ordered groups, and each group waits for its own approval.',
		cells: {
			atlantis: { mark: 'warn', text: 'execution_order_group and depends_on order plans and applies; no approval per group is documented', sources: [atlantis.repoYaml] },
			hcp: { mark: 'warn', text: 'Run triggers chain workspaces, each run confirmed on its own; orchestration rules for Stacks deployment groups need the Plus edition', sources: [hcp.runTriggers, hcp.stacks] },
			spacelift: { mark: 'warn', text: 'Stack dependencies run tracked runs in order and stop the chain on a failure; no approval per group is documented', sources: [spacelift.dependencies] },
			opentaco: { mark: 'warn', text: 'Layering orders projects into layers you plan and apply one at a time by comment; no approval per layer is documented', sources: [opentaco.layering] },
		},
	},
	{
		id: 'refuse-changed',
		label: 'Refuses a plan that changed after approval',
		statement: 'If what would apply is not what was approved, nothing applies until someone approves again.',
		cells: {
			atlantis: { mark: 'warn', text: 'The undiverged requirement, with the merge checkout strategy only, blocks apply when the base branch changed since the last plan; --discard-approval-on-plan, off by default, clears the approval when a new plan runs', sources: [atlantis.commandRequirements, atlantis.server] },
			hcp: { mark: 'good', text: 'A saved plan whose state changed under it is detected as stale and discarded', sources: [hcp.cli] },
			spacelift: { mark: 'warn', text: 'Proposed runs stop when newer code is pushed; the docs do not say a tracked run\'s approval is dropped', sources: [spacelift.run] },
			opentaco: { mark: 'warn', text: 'The undiverged requirement blocks apply when the base branch changed; nothing compares the plan with the approved one', sources: [opentaco.requirements] },
		},
	},
	{
		id: 'locks',
		label: 'Root locks',
		statement: 'A root is held by one pull request or run at a time, with a documented way to release it.',
		cells: {
			atlantis: { mark: 'good', text: 'A plan locks the directory and workspace to the pull request until it merges or closes; atlantis unlock releases it', sources: [atlantis.locking] },
			hcp: { mark: 'good', text: 'A workspace runs its queued runs one at a time; users with lock permission lock and unlock it, and workspace admins can force unlock', sources: [hcp.remote, hcp.settings] },
			spacelift: { mark: 'good', text: 'Tracked runs and tasks each take an exclusive lock on the stack, one at a time; a stack writer can also lock it by hand, and its creator or an admin releases it', sources: [spacelift.run, spacelift.creating] },
			opentaco: { mark: 'good', text: 'A project is locked to one pull request until it applies and merges or a digger unlock comment releases it', sources: [opentaco.gcpLocks, opentaco.commentops] },
		},
	},
	{
		id: 'terragrunt',
		label: 'Terragrunt waves with gates',
		statement: 'Terragrunt units go out in dependency order, in groups that each wait for an approval.',
		cells: {
			atlantis: { mark: 'warn', text: 'Terragrunt runs through custom workflows; no gated groups of units are documented', sources: [atlantis.workflows] },
			hcp: { mark: 'bad', text: 'The run environment documents Terraform only; no page mentions Terragrunt', sources: [hcp.runEnv] },
			spacelift: { mark: 'warn', text: 'run-all follows Terragrunt dependencies, with no gated groups, and the apply does not use the plan files', sources: [spacelift.runAll, spacelift.terragrunt] },
			opentaco: { mark: 'warn', text: 'Projects are generated from Terragrunt with its dependency order and execution-order groups; no gate per group is documented', sources: [opentaco.terragrunt] },
		},
	},
	{
		id: 'drift',
		label: 'Drift detection',
		statement: 'A scheduled check plans every root and reports drift where the team will see it.',
		cells: {
			atlantis: { mark: 'warn', text: 'An alpha drift API with webhook notifications and no scheduler; you call it from a cron of your own', sources: [atlantis.api, atlantis.faq] },
			hcp: { mark: 'warn', text: 'Health assessments report drift in the workspace and by notification, in the Standard and Premium editions', sources: [hcp.health] },
			spacelift: { mark: 'warn', text: 'Scheduled drift detection with reconcile runs and webhooks, on private workers and the Starter+ plan', sources: [spacelift.drift] },
			opentaco: { mark: 'good', text: 'Scheduled drift checks in GitHub Actions report to Slack or GitHub issues', sources: [opentaco.drift] },
		},
	},
	{
		id: 'hosting',
		label: 'Nothing new to host',
		statement: 'It runs on the CI runners you already have, with no server or service of its own.',
		cells: {
			atlantis: { mark: 'warn', text: 'You run the Atlantis server, a Go app or container, on Kubernetes, a VM or similar', sources: [atlantis.deployment] },
			hcp: { mark: 'warn', text: 'A service HashiCorp runs; agents in your network are optional and a paid feature', sources: [hcp.remote] },
			spacelift: { mark: 'warn', text: 'A service Spacelift runs, on its workers or on private workers in your infrastructure; a self-hosted install comes with Enterprise+', sources: [spacelift.workers, spacelift.selfHosted, spacelift.pricing] },
			opentaco: { mark: 'warn', text: 'Jobs run in your CI; full features need an orchestrator backend, the hosted app or one you run', sources: [opentaco.backendless] },
		},
	},
	{
		id: 'state',
		label: 'State stays in your backend',
		statement: 'State stays in the backend your roots already use, and the tool never has to hold it.',
		cells: {
			atlantis: { mark: 'good', text: 'Atlantis has no external database; your roots keep their own backend', sources: [atlantis.deployment] },
			hcp: { mark: 'bad', text: 'Each workspace keeps its state in HCP Terraform', sources: [hcp.cloudSettings] },
			spacelift: { mark: 'good', text: 'Your backend keeps state unless you opt in to Spacelift-managed state, which the docs recommend, when creating the stack', sources: [spacelift.creating] },
			opentaco: { mark: 'good', text: 'Teams bring their own backend such as S3; OpenTaco State Management holds state only if you opt in, and Remote Runs require it', sources: [opentaco.state, opentaco.remoteRuns] },
		},
	},
	{
		id: 'credentials',
		label: 'Cloud credentials stay with you',
		statement: 'Cloud access comes from your own runners\' identity, and the product never holds a credential.',
		cells: {
			atlantis: { mark: 'warn', text: 'Credentials live on the Atlantis server, as environment variables, files or an instance role', sources: [atlantis.credentials] },
			hcp: { mark: 'warn', text: 'Each run gets an OIDC token that HashiCorp\'s runners or your agents trade for short-lived credentials', sources: [hcp.dynamic] },
			spacelift: { mark: 'warn', text: 'Spacelift\'s workers get short-lived generated credentials; private workers can use your own cloud roles', sources: [spacelift.cloud] },
			opentaco: { mark: 'good', text: 'The job in your own CI trades its OIDC token for your role', sources: [opentaco.oidc] },
		},
	},
	{
		id: 'telemetry',
		label: 'Traces and metrics',
		statement: 'Each run sends traces and metrics to a backend you choose.',
		cells: {
			atlantis: { mark: 'warn', text: 'Run metrics to Statsd or Prometheus; no traces are documented', sources: [atlantis.stats] },
			hcp: { mark: 'warn', text: 'Self-hosted agents send OpenTelemetry metrics and traces; runs on HashiCorp\'s workers are not covered', sources: [hcp.telemetry] },
			spacelift: { mark: 'warn', text: 'A Prometheus exporter you run against the API, or a Datadog module built on notification policies', sources: [spacelift.prometheus, spacelift.datadog] },
			opentaco: { mark: 'bad', text: 'No metrics or traces of runs are documented, only anonymized product telemetry', sources: [opentaco.telemetry] },
		},
	},
	{
		id: 'modules',
		label: 'Module publishing and pinned rollouts',
		statement: 'Modules are published as versions, and a new version is rolled out to the roots that pin it.',
		cells: {
			atlantis: { mark: 'bad', text: 'The docs describe no module publishing or rollout of a pinned version', sources: [atlantis.faq] },
			hcp: { mark: 'warn', text: 'The private registry publishes modules from tags or branches; rolling a version out to its users is not documented', sources: [hcp.registry] },
			spacelift: { mark: 'warn', text: 'A private registry with version tests that can trigger the stacks using a module; nothing moves their pins', sources: [spacelift.registry] },
			opentaco: { mark: 'bad', text: 'The docs describe no module registry or rollout', sources: [opentaco.features] },
		},
	},
	{
		id: 'licence',
		label: 'Licence and cost',
		statement: 'Open source and free to run, with no paid tier holding a feature back.',
		cells: {
			atlantis: { mark: 'good', text: 'Apache 2.0, free to run', sources: [atlantis.licence] },
			hcp: { mark: 'warn', text: 'A proprietary service priced per managed resource; the Free plan caps at 500 managed resources, policy enforcement and cost estimation need Standard or Premium, and audit logging needs Premium', sources: [hcp.overview] },
			spacelift: { mark: 'warn', text: 'A proprietary service; the Free plan has 2 users and 1 public worker, and drift detection, the policy engine and a private worker come with Starter+, an annual plan at $20,000', sources: [spacelift.pricing] },
			opentaco: { mark: 'warn', text: 'The core is MIT; GitLab and Buildkite support and FIPS builds need the enterprise edition and its licence key', sources: [opentaco.gitlab, opentaco.buildkite, opentaco.fips, opentaco.licence] },
		},
	},
	{
		id: 'account',
		label: 'No account or sign-in',
		statement: 'Nothing to sign up for: no account with the vendor, and no sign-in to see a plan or approve a run.',
		cells: {
			atlantis: { mark: 'good', text: 'No vendor account; plans and approvals are on the pull request, and the server\'s web UI can be put behind basic auth', sources: [atlantis.server] },
			hcp: { mark: 'bad', text: 'Starts with an HCP Terraform account and organization; the full plan opens in its web app for members who can read runs', sources: [hcp.signUp, hcp.ui] },
			spacelift: { mark: 'bad', text: 'Starts with a Spacelift account; runs are triggered, viewed and confirmed in its web app', sources: [spacelift.home, spacelift.start] },
			opentaco: { mark: 'warn', text: 'Onboarding starts with a sign-up at otaco.app, and a self-hosted install signs users in through WorkOS; backendless mode runs as a GitHub Action with no backend and the basic features', sources: [opentaco.account, opentaco.workos, opentaco.backendless] },
		},
	},
	{
		id: 'hosted',
		label: 'A hosted web app',
		statement: 'A web app shows runs and plans, and the vendor can host everything for you.',
		cells: {
			atlantis: { mark: 'bad', text: 'No hosted service; the server you run has a web page of locks and live plan and apply logs, kept until the pull request closes', sources: [atlantis.locking, atlantis.logs, atlantis.home] },
			hcp: { mark: 'good', text: 'A web app shows runs, plans and history, and HashiCorp runs Terraform on its own machines by default', sources: [hcp.overview, hcp.ui] },
			spacelift: { mark: 'good', text: 'A web app where runs are triggered, viewed and confirmed; Spacelift hosts it as SaaS, and Enterprise+ adds a self-hosted install', sources: [spacelift.start, spacelift.selfHosted] },
			opentaco: { mark: 'warn', text: 'A hosted app at otaco.app runs the orchestrator, state and Remote Runs, with a run page in the browser; pull request plans run in your GitHub Actions and show in comments', sources: [opentaco.account, opentaco.remoteJobs, opentaco.architecture] },
		},
	},
	{
		id: 'maturity',
		label: 'Years in production',
		statement: 'Years in production use and a wide base of users.',
		cells: {
			atlantis: { mark: 'good', text: 'In production since 2017, and a CNCF Sandbox project since June 2024', sources: [atlantis.home, atlantis.introducing, atlantis.cncf] },
			hcp: { mark: 'good', text: 'Released as Terraform Cloud in September 2019; the Terraform product page names customers such as Deutsche Bank, GitHub and Skechers', sources: [hcp.announce, hcp.product] },
			spacelift: { mark: 'good', text: 'Founded in 2020; the customers page has stories from 1Password, Figma and Duolingo', sources: [spacelift.careers, spacelift.customers] },
			opentaco: { mark: 'warn', text: 'Releases since March 2023, under the name Digger until November 2025; the README links write-ups from teams at Converge Bio and Brevo', sources: [opentaco.releases, opentaco.readme] },
		},
	},
	{
		id: 'tg-before-merge',
		label: 'Apply before merge in a Terragrunt repo',
		statement: 'In a Terragrunt repo, a change can apply from the open pull request before it merges.',
		cells: {
			atlantis: { mark: 'good', text: 'Terragrunt runs through a custom workflow the docs give, and applies run on the open pull request before merge', sources: [atlantis.workflows, atlantis.locking] },
			hcp: { mark: 'bad', text: 'No page mentions Terragrunt, and a VCS-connected workspace applies only after merge', sources: [hcp.runEnv, hcp.cli] },
			spacelift: { mark: 'warn', text: 'Terragrunt stacks are supported, and run promotion or a push policy can deploy a pull request\'s commit before merge; the Terragrunt pages do not mention it, and the apply does not use the plan files', sources: [spacelift.promotion, spacelift.tgVendor, spacelift.terragrunt] },
			opentaco: { mark: 'good', text: 'Terragrunt projects apply from a digger apply comment on the open pull request, which is the default', sources: [opentaco.usingTerragrunt, opentaco.applyOnMerge] },
		},
	},
	{
		id: 'gitlab-comments',
		label: 'Comment commands on GitLab',
		statement: 'On GitLab, a merge request comment re-plans or applies.',
		cells: {
			atlantis: { mark: 'good', text: 'GitLab, self-managed included, is supported, and merge request comments run plan and apply', sources: [atlantis.requirements, atlantis.using] },
			hcp: { mark: 'bad', text: 'GitLab merge requests get a speculative plan and a link to it; no comment command is documented', sources: [hcp.vcsProviders] },
			spacelift: { mark: 'bad', text: 'GitLab merge requests get a comment showing the change; comment commands are documented for GitHub\'s comment events, and the GitLab webhook setup does not subscribe to comments', sources: [spacelift.gitlab, spacelift.prComments] },
			opentaco: { mark: 'warn', text: 'A digger plan comment on a merge request starts a plan, with the enterprise edition and its licence key; the page shows no apply by comment', sources: [opentaco.gitlab] },
		},
	},
];
