/**
 * `terragucci generate`: each plain root's backend, provider and version
 * files, written from terragucci.yml's `generate` key. The settings stack in
 * three levels, each over the one before: the repo's (`generate`'s own keys),
 * then each `generate.dirs` glob the root's path matches, in the order the
 * file lists them, then `generate.roots`, keyed by the root's exact path. A
 * control repo's `defaults.generate` comes before a project's own.
 *
 * Each file is plain HCL whose first line marks it as generated, and the
 * roots stay ordinary Terraform/OpenTofu: nothing reads the files but the
 * binary. `--check` (run by tf-check) refuses a generated file that differs
 * from what generate writes, one that is missing, and one the config no
 * longer asks for.
 *
 * `required_version`, when no level sets it, is the version terragucci.yml's
 * `version` gives the root (its map's first matching glob, or the one
 * release), so the version the job runs and the one the root declares come
 * from one key. A Terragrunt repo generates its boilerplate with Terragrunt's
 * own `generate` blocks, so generate refuses one.
 */
import { existsSync, readdirSync, readFileSync, statSync } from "node:fs";
import { join, relative } from "node:path";
import { ConfigError, type ResolvedSettings } from "./config";
import { findRoots, globMatch } from "./detect";
import { IDENT, isMap, overlayLevel, TERRAGRUNT_GENERATE, type GenerateLevel, type GenerateSettings } from "./generate-config";
import { versionGlobs } from "./pins";
import { detectTerragrunt } from "./terragrunt";

export { checkGenerate, combineGenerate, TERRAGRUNT_GENERATE, type GenerateLevel, type GenerateSettings } from "./generate-config";

/** A file generate writes, as init's FileChange. */
interface FileChange {
  path: string;
  status: "created" | "updated" | "unchanged" | "removed";
  content: string;
}

/** tf-check's result, as check.ts's CheckResult. */
interface CheckResult {
  ok: boolean;
  log: string[];
  report: string[];
}

/** What one root's files are written from, every level applied. */
export interface RootSettings {
  backend?: { type: string; config: Record<string, unknown> };
  providers: Record<string, Record<string, unknown>>;
  required_version?: string;
  /** Where `required_version` came from, when `version` gave it. */
  versionFrom?: string;
}

export const GENERATED_FILES = { backend: "backend.tf", providers: "providers.tf", versions: "versions.tf" } as const;

/** The first line of every generated file; generate rewrites and removes only files that start with it. */
export const GENERATED_MARKER = "# Generated by terragucci generate from terragucci.yml. Edit terragucci.yml and run terragucci generate; tf-check refuses a hand edit.";

const EXACT = /^\s*=?\s*(\d+\.\d+\.\d+(-[0-9A-Za-z.]+)?)\s*$/;

/** Drop the nulls an overlay kept. */
function settle(v: unknown): unknown {
  if (Array.isArray(v)) return v.map(settle);
  if (!isMap(v)) return v;
  return Object.fromEntries(Object.entries(v).filter(([, x]) => x !== null).map(([k, x]) => [k, settle(x)]));
}

/** The version terragucci.yml's `version` gives a root, and how. */
export function versionPin(version: unknown, root: string): { version: string; from: string } | undefined {
  if (typeof version === "string") return { version, from: "version" };
  const globs = versionGlobs(version);
  const glob = globs && Object.keys(globs).find((g) => globMatch(g, root));
  return glob !== undefined ? { version: String(globs![glob]), from: `version ${glob}` } : undefined;
}

/** Every level applied for one root, `{root}` filled in. */
export function rootSettings(generate: GenerateSettings, root: string, settings: Pick<ResolvedSettings, "version" | "binary"> = {}): RootSettings {
  const { dirs, roots, ...repoLevel } = generate;
  let level: GenerateLevel = overlayLevel({}, repoLevel);
  for (const [glob, s] of Object.entries(dirs ?? {})) if (globMatch(glob, root)) level = overlayLevel(level, s ?? {});
  const own = roots?.[root];
  if (own) level = overlayLevel(level, own);
  const fill = (v: unknown): unknown =>
    typeof v === "string" ? v.split("{root}").join(root) : Array.isArray(v) ? v.map(fill) : isMap(v) ? Object.fromEntries(Object.entries(v).map(([k, x]) => [k, fill(x)])) : v;
  const out: RootSettings = { providers: {} };
  if (level.backend) {
    const type = Object.keys(level.backend)[0];
    out.backend = { type, config: fill(settle(level.backend[type])) as Record<string, unknown> };
  }
  for (const [name, s] of Object.entries(level.providers ?? {})) if (s) out.providers[name] = fill(settle(s)) as Record<string, unknown>;
  // A choudoufu release is not the OpenTofu language version required_version names.
  const pin = settings.binary === "choudoufu" ? undefined : versionPin(settings.version, root);
  if (typeof level.required_version === "string") {
    out.required_version = level.required_version;
    const exact = EXACT.exec(level.required_version)?.[1];
    if (exact && pin && exact !== pin.version) {
      throw new ConfigError(`${root}: generate gives required_version ${level.required_version}, and terragucci.yml's ${pin.from} pins ${pin.version}; set one of them, or make them agree`);
    }
  } else if (level.required_version === undefined && pin) {
    out.required_version = pin.version;
    out.versionFrom = pin.from;
  }
  return out;
}

// ── HCL ──────────────────────────────────────────────────────────────────────

/** A string literal: HCL's escapes, with `${` and `%{` doubled so nothing interpolates. */
function hclString(s: string): string {
  const body = s.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\n/g, "\\n").replace(/\r/g, "\\r").replace(/\t/g, "\\t");
  return `"${body.replace(/\$\{/g, () => "$${").replace(/%\{/g, () => "%%{")}"`;
}

/** A value on one line: lists and maps inline, which `fmt` leaves as they are. */
function hclValue(v: unknown): string {
  if (typeof v === "string") return hclString(v);
  if (typeof v === "number" || typeof v === "boolean") return String(v);
  if (Array.isArray(v)) return `[${v.map(hclValue).join(", ")}]`;
  if (isMap(v)) {
    const entries = Object.entries(v);
    return entries.length === 0 ? "{}" : `{ ${entries.map(([k, x]) => `${IDENT.test(k) ? k : hclString(k)} = ${hclValue(x)}`).join(", ")} }`;
  }
  return "null";
}

/** Attribute lines aligned on `=`, as `fmt` aligns a run of them. */
function attributes(attrs: [string, unknown][], indent: string): string[] {
  const width = Math.max(0, ...attrs.map(([k]) => k.length));
  return attrs.map(([k, v]) => `${indent}${k.padEnd(width)} = ${hclValue(v)}`);
}

/** A block's body: its attributes, then (blank line apart) its nested blocks. `blocks`: maps are nested blocks, as a provider's are. */
function body(args: Record<string, unknown>, indent: string, blocks: boolean): string[] {
  const attrs = Object.entries(args).filter(([, v]) => !(blocks && isMap(v)));
  const nested = blocks ? Object.entries(args).filter(([, v]) => isMap(v)) : [];
  const out = attributes(attrs, indent);
  for (const [name, inner] of nested) {
    if (out.length) out.push("");
    const lines = body(inner as Record<string, unknown>, `${indent}  `, false);
    out.push(...(lines.length ? [`${indent}${name} {`, ...lines, `${indent}}`] : [`${indent}${name} {}`]));
  }
  return out;
}

function file(lines: string[]): string {
  return `${GENERATED_MARKER}\n\n${lines.join("\n")}\n`;
}

/** The content of each file a root's settings ask for; a file they do not ask for is absent. */
export function renderRoot(s: RootSettings): Partial<Record<keyof typeof GENERATED_FILES, string>> {
  const out: Partial<Record<keyof typeof GENERATED_FILES, string>> = {};
  if (s.backend) {
    const lines = body(s.backend.config, "    ", false);
    out.backend = file(["terraform {", ...(lines.length ? [`  backend "${s.backend.type}" {`, ...lines, "  }"] : [`  backend "${s.backend.type}" {}`]), "}"]);
  }
  const blocks: string[] = [];
  for (const [key, p] of Object.entries(s.providers)) {
    const [name, alias] = key.split(".");
    const args = Object.fromEntries(Object.entries(p).filter(([k]) => k !== "source" && k !== "version"));
    if (!alias && Object.keys(args).length === 0) continue;
    const lines = body({ ...(alias ? { alias } : {}), ...args }, "  ", true);
    if (blocks.length) blocks.push("");
    blocks.push(...(lines.length ? [`provider "${name}" {`, ...lines, "}"] : [`provider "${name}" {}`]));
  }
  if (blocks.length) out.providers = file(blocks);
  // required_providers: each local name once, its source and version from whichever configuration of it gives them.
  const required = new Map<string, [string, unknown][]>();
  for (const [key, p] of Object.entries(s.providers)) {
    const name = key.split(".")[0];
    const have = required.get(name) ?? [];
    for (const k of ["source", "version"]) if (typeof p[k] === "string" && !have.some(([x]) => x === k)) have.push([k, p[k]]);
    required.set(name, have);
  }
  const reqs = [...required].filter(([, a]) => a.length > 0).sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0));
  if (s.required_version !== undefined || reqs.length) {
    const lines = ["terraform {"];
    if (s.required_version !== undefined) lines.push(`  required_version = ${hclString(s.required_version)}`);
    if (reqs.length) {
      if (s.required_version !== undefined) lines.push("");
      lines.push("  required_providers {");
      for (const [name, a] of reqs) lines.push(`    ${name} = {`, ...attributes(a.sort(([x], [y]) => (x === "source" ? -1 : y === "source" ? 1 : 0)), "      "), "    }");
      lines.push("  }");
    }
    lines.push("}");
    out.versions = file(lines);
  }
  return out;
}

// ── the repo ─────────────────────────────────────────────────────────────────

const SKIP = new Set([".git", ".terraform", ".terragrunt-cache", "node_modules", ".terragucci"]);

/** Every file under `repo` with a generated file's name that starts with the marker. */
function generatedOnDisk(repo: string): string[] {
  const out: string[] = [];
  const names = new Set<string>(Object.values(GENERATED_FILES));
  const walk = (dir: string): void => {
    for (const name of readdirSync(dir)) {
      if (SKIP.has(name) || name.startsWith(".")) continue;
      const abs = join(dir, name);
      const st = statSync(abs);
      if (st.isDirectory()) walk(abs);
      else if (names.has(name) && readFileSync(abs, "utf-8").startsWith(GENERATED_MARKER)) out.push(abs);
    }
  };
  walk(repo);
  return out;
}

const stripComments = (text: string): string => text.replace(/\/\*[\s\S]*?\*\//g, "").replace(/(^|[^:"])(#|\/\/).*$/gm, "$1");

/** A root's own files (not generated) that already declare what a generated file would. */
function handDeclared(dir: string, what: "backend" | "required_version"): string | undefined {
  for (const name of readdirSync(dir).sort()) {
    if (!name.endsWith(".tf") && !name.endsWith(".tofu")) continue;
    const text = readFileSync(join(dir, name), "utf-8");
    if (text.startsWith(GENERATED_MARKER)) continue;
    const t = stripComments(text);
    if (what === "backend" ? /\bbackend\s+"[^"]+"\s*\{|^\s*cloud\s*\{/m.test(t) : /\brequired_version\s*=/.test(t)) return name;
  }
  return undefined;
}

export interface GeneratePlan {
  /** The roots generate wrote for. */
  roots: string[];
  /** Each generated file: created, updated, unchanged, or removed (generated, and no longer asked for). */
  files: FileChange[];
  /** Files at a generated file's path that terragucci did not write, with what to do. */
  foreign: string[];
}

/** The roots generate writes for: the ones init finds (by `roots`, or detection), and every `generate.roots` path. */
export function generateRoots(repo: string, settings: ResolvedSettings): string[] {
  const roots = new Set(findRoots(repo, settings.roots));
  for (const r of Object.keys(settings.generate?.roots ?? {})) {
    const dir = join(repo, r);
    if (!existsSync(dir) || !statSync(dir).isDirectory()) throw new ConfigError(`generate.roots names ${r}, which is not a directory in the repo`);
    roots.add(r.replace(/\/+$/, "") || ".");
  }
  return [...roots].sort();
}

/**
 * What generate would write, file by file, without writing it. Throws a
 * ConfigError for a Terragrunt repo and for settings that cannot be written.
 */
export function planGenerate(repo: string, settings: ResolvedSettings): GeneratePlan {
  if (detectTerragrunt(repo)) throw new ConfigError(TERRAGRUNT_GENERATE);
  const gen = settings.generate ?? {};
  const roots = settings.generate ? generateRoots(repo, settings) : [];
  const files: FileChange[] = [];
  const foreign: string[] = [];
  const wanted = new Set<string>();
  for (const root of roots) {
    const s = rootSettings(gen, root, settings);
    const dir = join(repo, root);
    const contents = renderRoot(s);
    for (const [kind, name] of Object.entries(GENERATED_FILES) as [keyof typeof GENERATED_FILES, string][]) {
      const content = contents[kind];
      if (content === undefined) continue;
      const path = join(dir, name);
      wanted.add(path);
      const before = existsSync(path) ? readFileSync(path, "utf-8") : undefined;
      if (before !== undefined && !before.startsWith(GENERATED_MARKER)) {
        foreign.push(`${rel(repo, path)} exists and terragucci did not write it; move what it declares into terragucci.yml's generate key and remove it, or drop ${kind === "versions" ? "required_version and the providers' source and version" : kind} from generate for ${root}`);
        continue;
      }
      if (kind === "backend") {
        const hand = handDeclared(dir, "backend");
        if (hand) throw new ConfigError(`${rel(repo, join(dir, hand))} declares a backend, and generate writes ${rel(repo, path)}; remove one of them`);
      }
      if (kind === "versions" && s.required_version !== undefined) {
        const hand = handDeclared(dir, "required_version");
        if (hand) throw new ConfigError(`${rel(repo, join(dir, hand))} sets required_version, and generate writes it in ${rel(repo, path)}${s.versionFrom ? ` from terragucci.yml's ${s.versionFrom}` : ""}; remove it from ${hand}${s.versionFrom ? ", or set required_version: null under generate" : ""}`);
      }
      files.push({ path, status: before === undefined ? "created" : before === content ? "unchanged" : "updated", content });
    }
  }
  for (const path of generatedOnDisk(repo)) if (!wanted.has(path)) files.push({ path, status: "removed", content: "" });
  return { roots, files, foreign };
}

const rel = (repo: string, path: string): string => relative(repo, path) || path;

/** The lines that differ, `-` what the file holds and `+` what generate writes. */
export function lineDiff(have: string, want: string): string[] {
  const a = have.split("\n");
  const b = want.split("\n");
  const n = a.length;
  const m = b.length;
  const lcs: number[][] = Array.from({ length: n + 1 }, () => new Array<number>(m + 1).fill(0));
  for (let i = n - 1; i >= 0; i--) for (let j = m - 1; j >= 0; j--) lcs[i][j] = a[i] === b[j] ? lcs[i + 1][j + 1] + 1 : Math.max(lcs[i + 1][j], lcs[i][j + 1]);
  const out: string[] = [];
  let i = 0;
  let j = 0;
  while (i < n || j < m) {
    if (i < n && j < m && a[i] === b[j]) {
      i++;
      j++;
    } else if (i < n && (j >= m || lcs[i + 1][j] >= lcs[i][j + 1])) out.push(`-${a[i++]}`);
    else out.push(`+${b[j++]}`);
  }
  return out;
}

/**
 * `generate --check`: tf-check's step. Passes when every generated file is
 * what generate writes; each one that differs, is missing, is no longer asked
 * for, or sits where a file terragucci did not write is, is refused by name.
 */
export function checkGenerated(repo: string, settings: ResolvedSettings): CheckResult {
  const plan = planGenerate(repo, settings);
  const log: string[] = [];
  const report: string[] = ["### Generated files", ""];
  for (const f of plan.files) {
    const path = rel(repo, f.path);
    if (f.status === "unchanged") continue;
    if (f.status === "created") log.push(`refused: ${path} is missing; terragucci generate writes it from terragucci.yml`);
    else if (f.status === "removed") log.push(`refused: ${path} was generated, and terragucci.yml no longer asks for it`);
    else {
      log.push(`refused: ${path} differs from what terragucci generate writes from terragucci.yml:`);
      for (const l of lineDiff(readFileSync(f.path, "utf-8"), f.content)) log.push(`    ${l}`);
    }
  }
  for (const line of plan.foreign) log.push(`refused: ${line}`);
  const refused = log.filter((l) => l.startsWith("refused: "));
  for (const l of refused) report.push(`- ${l}`);
  if (refused.length) {
    log.push(`FAILED generate: ${refused.length} generated file${refused.length === 1 ? "" : "s"} out of line with terragucci.yml; run terragucci generate and commit what it writes`);
    return { ok: false, log, report: [...report, ""] };
  }
  const n = plan.files.length;
  const line = `generated files match terragucci.yml: ${n} file${n === 1 ? "" : "s"} in ${plan.roots.length} root${plan.roots.length === 1 ? "" : "s"}`;
  return { ok: true, log: [line], report: [...report, `- ${line}`, ""] };
}

/** What `terragucci generate` prints. */
export function describeGenerate(repo: string, plan: GeneratePlan, dryRun: boolean): string {
  const verb = (s: FileChange["status"]): string =>
    s === "unchanged" ? "unchanged" : dryRun ? (s === "created" ? "would write" : s === "removed" ? "would remove" : "would update") : s === "created" ? "wrote" : s === "removed" ? "removed" : "updated";
  const lines = plan.files.map((f) => `${verb(f.status)} ${rel(repo, f.path)}`);
  const changed = plan.files.filter((f) => f.status !== "unchanged").length;
  lines.push(`${plan.files.length} generated file${plan.files.length === 1 ? "" : "s"} in ${plan.roots.length} root${plan.roots.length === 1 ? "" : "s"}, ${changed} ${dryRun ? "to change; nothing was written" : "changed"}`);
  return lines.join("\n");
}

/**
 * A control repo's project's `generate`, as written into the project's own
 * terragucci.yml: the project file carries no `version`, so a version the
 * control repo gives every root becomes the repo level's `required_version`,
 * and the project's tf-check still sees what reconcile generated.
 */
export function projectGenerate(settings: Pick<ResolvedSettings, "generate" | "version" | "binary">): GenerateSettings | undefined {
  const g = settings.generate;
  if (!g || g.required_version !== undefined || typeof settings.version !== "string" || settings.binary === "choudoufu") return g;
  return { ...g, required_version: settings.version };
}
