/**
 * `terragucci generate`: each plain root's backend, provider and version
 * files, written from terragucci.yml's `generate` key. The settings stack in
 * three levels, each over the one before: the repo's (`generate`'s own keys),
 * then each `generate.dirs` glob the root's path matches, in the order the
 * file lists them, then `generate.roots`, keyed by the root's exact path. A
 * control repo's `defaults.generate` comes before a project's own.
 *
 * Each file is plain HCL whose first line marks it as generated, and the
 * roots stay ordinary Terraform/OpenTofu: nothing reads the files but the
 * binary. `--check` (run by tf-check) refuses a generated file that differs
 * from what generate writes, one that is missing, and one the config no
 * longer asks for.
 *
 * `required_version`, when no level sets it, is the version terragucci.yml's
 * `version` gives the root (its map's first matching glob, or the one
 * release), so the version the job runs and the one the root declares come
 * from one key.
 *
 * In a Terragrunt repo the same settings, resolved for each unit with the
 * same three levels, become one file at the repo's root, `terragucci.hcl`:
 * a `remote_state` block and `generate` blocks that Terragrunt runs, keyed
 * by the unit's path, so Terragrunt writes each unit's backend.tf,
 * providers.tf and versions.tf in its working directory. Each unit includes
 * it (`include "terragucci"`); `--check` refuses a unit that does not, so no
 * unit silently goes without its settings, and a `remote_state` block or a
 * `generate` block for the same file elsewhere, which would contend with it.
 * Terragrunt's own blocks in root.hcl do the same within one repo; what
 * generate adds is one source across a control repo's projects
 * (`defaults.generate`), plain and Terragrunt alike, `required_version` kept
 * in line with `version`, and tf-check refusing a hand edit.
 */
import { existsSync, readdirSync, readFileSync, statSync } from "node:fs";
import { join, relative } from "node:path";
import { ConfigError, type ResolvedSettings } from "./config";
import { HTTP_LOCK_ATTRIBUTES, KEY_ATTRIBUTE, SUFFIX_READ } from "./ephemeral";
import { findRoots, globMatch } from "./detect";
import { IDENT, isMap, overlayLevel, type GenerateLevel, type GenerateSettings } from "./generate-config";
import { versionGlobs } from "./pins";
import { detectShape } from "./shape";
import { hclBlocks, walkUnits } from "./terragrunt";
import { explicitStackUnits, generatingStack } from "./tg-stacks";

export { checkGenerate, combineGenerate, type GenerateLevel, type GenerateSettings } from "./generate-config";

/** A file generate writes, as init's FileChange. */
interface FileChange {
  path: string;
  status: "created" | "updated" | "unchanged" | "removed";
  content: string;
}

/** tf-check's result, as check.ts's CheckResult. */
interface CheckResult {
  ok: boolean;
  log: string[];
  report: string[];
}

/** What one root's files are written from, every level applied. */
export interface RootSettings {
  backend?: { type: string; config: Record<string, unknown> };
  providers: Record<string, Record<string, unknown>>;
  required_version?: string;
  /** Where `required_version` came from, when `version` gave it. */
  versionFrom?: string;
  /** A Terragrunt unit's remote_state `disable_init`, when a level sets it. */
  disableInit?: boolean;
}

export const GENERATED_FILES = { backend: "backend.tf", providers: "providers.tf", versions: "versions.tf" } as const;

/** The first line of every generated file; generate rewrites and removes only files that start with it. */
export const GENERATED_MARKER = "# Generated by terragucci generate from terragucci.yml. Edit terragucci.yml and run terragucci generate; tf-check refuses a hand edit.";

const EXACT = /^\s*=?\s*(\d+\.\d+\.\d+(-[0-9A-Za-z.]+)?)\s*$/;

/** Drop the nulls an overlay kept. */
function settle(v: unknown): unknown {
  if (Array.isArray(v)) return v.map(settle);
  if (!isMap(v)) return v;
  return Object.fromEntries(Object.entries(v).filter(([, x]) => x !== null).map(([k, x]) => [k, settle(x)]));
}

/** The version terragucci.yml's `version` gives a root, and how. */
export function versionPin(version: unknown, root: string): { version: string; from: string } | undefined {
  if (typeof version === "string") return { version, from: "version" };
  const globs = versionGlobs(version);
  const glob = globs && Object.keys(globs).find((g) => globMatch(g, root));
  return glob !== undefined ? { version: String(globs![glob]), from: `version ${glob}` } : undefined;
}

/** Every level applied for one root, `{root}` filled in. */
export function rootSettings(generate: GenerateSettings, root: string, settings: Pick<ResolvedSettings, "version" | "binary"> = {}): RootSettings {
  const { dirs, roots, ...repoLevel } = generate;
  let level: GenerateLevel = overlayLevel({}, repoLevel);
  for (const [glob, s] of Object.entries(dirs ?? {})) if (globMatch(glob, root)) level = overlayLevel(level, s ?? {});
  const own = roots?.[root];
  if (own) level = overlayLevel(level, own);
  const fill = (v: unknown): unknown =>
    typeof v === "string" ? v.split("{root}").join(root) : Array.isArray(v) ? v.map(fill) : isMap(v) ? Object.fromEntries(Object.entries(v).map(([k, x]) => [k, fill(x)])) : v;
  const out: RootSettings = { providers: {} };
  if (level.backend) {
    const type = Object.keys(level.backend)[0];
    out.backend = { type, config: fill(settle(level.backend[type])) as Record<string, unknown> };
  }
  for (const [name, s] of Object.entries(level.providers ?? {})) if (s) out.providers[name] = fill(settle(s)) as Record<string, unknown>;
  if (typeof level.disable_init === "boolean") out.disableInit = level.disable_init;
  // A choudoufu release is not the OpenTofu language version required_version names.
  const pin = settings.binary === "choudoufu" ? undefined : versionPin(settings.version, root);
  if (typeof level.required_version === "string") {
    out.required_version = level.required_version;
    const exact = EXACT.exec(level.required_version)?.[1];
    if (exact && pin && exact !== pin.version) {
      throw new ConfigError(`${root}: generate gives required_version ${level.required_version}, and terragucci.yml's ${pin.from} pins ${pin.version}; set one of them, or make them agree`);
    }
  } else if (level.required_version === undefined && pin) {
    out.required_version = pin.version;
    out.versionFrom = pin.from;
  }
  return out;
}

// ── HCL ──────────────────────────────────────────────────────────────────────

/** A string literal: HCL's escapes, with `${` and `%{` doubled so nothing interpolates. */
function hclString(s: string): string {
  const body = s.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\n/g, "\\n").replace(/\r/g, "\\r").replace(/\t/g, "\\t");
  return `"${body.replace(/\$\{/g, () => "$${").replace(/%\{/g, () => "%%{")}"`;
}

/** A value on one line: lists and maps inline, which `fmt` leaves as they are. */
function hclValue(v: unknown): string {
  if (typeof v === "string") return hclString(v);
  if (typeof v === "number" || typeof v === "boolean") return String(v);
  if (Array.isArray(v)) return `[${v.map(hclValue).join(", ")}]`;
  if (isMap(v)) {
    const entries = Object.entries(v);
    return entries.length === 0 ? "{}" : `{ ${entries.map(([k, x]) => `${IDENT.test(k) ? k : hclString(k)} = ${hclValue(x)}`).join(", ")} }`;
  }
  return "null";
}

/** Attribute lines aligned on `=`, as `fmt` aligns a run of them. */
function attributes(attrs: [string, unknown][], indent: string): string[] {
  const width = Math.max(0, ...attrs.map(([k]) => k.length));
  return attrs.map(([k, v]) => `${indent}${k.padEnd(width)} = ${hclValue(v)}`);
}

/** A block's body: its attributes, then (blank line apart) its nested blocks. `blocks`: maps are nested blocks, as a provider's are. */
function body(args: Record<string, unknown>, indent: string, blocks: boolean): string[] {
  const attrs = Object.entries(args).filter(([, v]) => !(blocks && isMap(v)));
  const nested = blocks ? Object.entries(args).filter(([, v]) => isMap(v)) : [];
  const out = attributes(attrs, indent);
  for (const [name, inner] of nested) {
    if (out.length) out.push("");
    const lines = body(inner as Record<string, unknown>, `${indent}  `, false);
    out.push(...(lines.length ? [`${indent}${name} {`, ...lines, `${indent}}`] : [`${indent}${name} {}`]));
  }
  return out;
}

function file(lines: string[]): string {
  return `${GENERATED_MARKER}\n\n${lines.join("\n")}\n`;
}

/** The content of each file a root's settings ask for; a file they do not ask for is absent. */
export function renderRoot(s: RootSettings): Partial<Record<keyof typeof GENERATED_FILES, string>> {
  const out: Partial<Record<keyof typeof GENERATED_FILES, string>> = {};
  if (s.backend) {
    const lines = body(s.backend.config, "    ", false);
    out.backend = file(["terraform {", ...(lines.length ? [`  backend "${s.backend.type}" {`, ...lines, "  }"] : [`  backend "${s.backend.type}" {}`]), "}"]);
  }
  const blocks: string[] = [];
  for (const [key, p] of Object.entries(s.providers)) {
    const [name, alias] = key.split(".");
    const args = Object.fromEntries(Object.entries(p).filter(([k]) => k !== "source" && k !== "version"));
    if (!alias && Object.keys(args).length === 0) continue;
    const lines = body({ ...(alias ? { alias } : {}), ...args }, "  ", true);
    if (blocks.length) blocks.push("");
    blocks.push(...(lines.length ? [`provider "${name}" {`, ...lines, "}"] : [`provider "${name}" {}`]));
  }
  if (blocks.length) out.providers = file(blocks);
  // required_providers: each local name once, its source and version from whichever configuration of it gives them.
  const required = new Map<string, [string, unknown][]>();
  for (const [key, p] of Object.entries(s.providers)) {
    const name = key.split(".")[0];
    const have = required.get(name) ?? [];
    for (const k of ["source", "version"]) if (typeof p[k] === "string" && !have.some(([x]) => x === k)) have.push([k, p[k]]);
    required.set(name, have);
  }
  const reqs = [...required].filter(([, a]) => a.length > 0).sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0));
  if (s.required_version !== undefined || reqs.length) {
    const lines = ["terraform {"];
    if (s.required_version !== undefined) lines.push(`  required_version = ${hclString(s.required_version)}`);
    if (reqs.length) {
      if (s.required_version !== undefined) lines.push("");
      lines.push("  required_providers {");
      for (const [name, a] of reqs) lines.push(`    ${name} = {`, ...attributes(a.sort(([x], [y]) => (x === "source" ? -1 : y === "source" ? 1 : 0)), "      "), "    }");
      lines.push("  }");
    }
    lines.push("}");
    out.versions = file(lines);
  }
  return out;
}

// ── the repo ─────────────────────────────────────────────────────────────────

const SKIP = new Set([".git", ".terraform", ".terragrunt-cache", "node_modules", ".terragucci"]);

/** Every file under `repo` with a generated file's name that starts with the marker. */
function generatedOnDisk(repo: string): string[] {
  const out: string[] = [];
  const names = new Set<string>(Object.values(GENERATED_FILES));
  const walk = (dir: string): void => {
    for (const name of readdirSync(dir)) {
      if (SKIP.has(name) || name.startsWith(".")) continue;
      const abs = join(dir, name);
      const st = statSync(abs);
      if (st.isDirectory()) walk(abs);
      else if (names.has(name) && readFileSync(abs, "utf-8").startsWith(GENERATED_MARKER)) out.push(abs);
    }
  };
  walk(repo);
  return out;
}

const stripComments = (text: string): string => text.replace(/\/\*[\s\S]*?\*\//g, "").replace(/(^|[^:"])(#|\/\/).*$/gm, "$1");

/** A root's own files (not generated) that already declare what a generated file would. */
function handDeclared(dir: string, what: "backend" | "required_version"): string | undefined {
  for (const name of readdirSync(dir).sort()) {
    if (!name.endsWith(".tf") && !name.endsWith(".tofu")) continue;
    const text = readFileSync(join(dir, name), "utf-8");
    if (text.startsWith(GENERATED_MARKER)) continue;
    const t = stripComments(text);
    if (what === "backend" ? /\bbackend\s+"[^"]+"\s*\{|^\s*cloud\s*\{/m.test(t) : /\brequired_version\s*=/.test(t)) return name;
  }
  return undefined;
}

export interface GeneratePlan {
  /** The roots generate wrote for; in a Terragrunt repo, the units. */
  roots: string[];
  /** A Terragrunt repo: one terragucci.hcl for every unit. */
  terragrunt?: boolean;
  /** Each generated file: created, updated, unchanged, or removed (generated, and no longer asked for). */
  files: FileChange[];
  /** Files at a generated file's path that terragucci did not write, with what to do. */
  foreign: string[];
  /** What generate could not check, one line each. */
  notes?: string[];
}


/** The roots generate writes for: the ones init finds (by `roots`, or detection), and every `generate.roots` path. */
export function generateRoots(repo: string, settings: ResolvedSettings): string[] {
  const roots = new Set(findRoots(repo, settings.roots));
  for (const r of Object.keys(settings.generate?.roots ?? {})) {
    const dir = join(repo, r);
    if (!existsSync(dir) || !statSync(dir).isDirectory()) throw new ConfigError(`generate.roots names ${r}, which is not a directory in the repo`);
    roots.add(r.replace(/\/+$/, "") || ".");
  }
  return [...roots].sort();
}

/**
 * What generate would write, file by file, without writing it. Throws a
 * ConfigError where the repo's shape refuses generate (synth, whose app sets
 * what generate would write, and Atmos, whose stacks do), and for settings
 * that cannot be written.
 */
export function planGenerate(repo: string, settings: ResolvedSettings): GeneratePlan {
  const shape = detectShape(repo, settings);
  const noSynth = settings.synth ? shape.refuses("synth") : undefined;
  if (noSynth) throw new ConfigError(`synth: ${noSynth}`);
  const refused = settings.generate ? shape.refuses("generate") : undefined;
  if (refused) throw new ConfigError(`generate: ${refused}`);
  if (shape.kind === "terragrunt") return planTerragrunt(repo, settings, shape.terragrunt?.stacks ?? []);
  const gen = settings.generate ?? {};
  const roots = settings.generate ? generateRoots(repo, settings) : [];
  const files: FileChange[] = [];
  const foreign: string[] = [];
  const wanted = new Set<string>();
  for (const root of roots) {
    const s = rootSettings(gen, root, settings);
    if (s.disableInit !== undefined) throw new ConfigError(`generate sets disable_init for ${root}, which is a plain root; disable_init is the remote_state setting terragucci.hcl writes for Terragrunt units, so remove it`);
    const dir = join(repo, root);
    const contents = renderRoot(s);
    for (const [kind, name] of Object.entries(GENERATED_FILES) as [keyof typeof GENERATED_FILES, string][]) {
      const content = contents[kind];
      if (content === undefined) continue;
      const path = join(dir, name);
      wanted.add(path);
      const before = existsSync(path) ? readFileSync(path, "utf-8") : undefined;
      if (before !== undefined && !before.startsWith(GENERATED_MARKER)) {
        foreign.push(`${rel(repo, path)} exists and terragucci did not write it; move what it declares into terragucci.yml's generate key and remove it, or drop ${kind === "versions" ? "required_version and the providers' source and version" : kind} from generate for ${root}`);
        continue;
      }
      if (kind === "backend") {
        const hand = handDeclared(dir, "backend");
        if (hand) throw new ConfigError(`${rel(repo, join(dir, hand))} declares a backend, and generate writes ${rel(repo, path)}; remove one of them`);
      }
      if (kind === "versions" && s.required_version !== undefined) {
        const hand = handDeclared(dir, "required_version");
        if (hand) throw new ConfigError(`${rel(repo, join(dir, hand))} sets required_version, and generate writes it in ${rel(repo, path)}${s.versionFrom ? ` from terragucci.yml's ${s.versionFrom}` : ""}; remove it from ${hand}${s.versionFrom ? ", or set required_version: null under generate" : ""}`);
      }
      files.push({ path, status: before === undefined ? "created" : before === content ? "unchanged" : "updated", content });
    }
  }
  for (const path of generatedOnDisk(repo)) if (!wanted.has(path)) files.push({ path, status: "removed", content: "" });
  return { roots, files, foreign };
}

const rel = (repo: string, path: string): string => relative(repo, path) || path;

// ── Terragrunt ───────────────────────────────────────────────────────────────

/** The file generate writes at a Terragrunt repo's root, which every unit includes. */
export const TERRAGRUNT_FILE = "terragucci.hcl";
/** The include a unit names it by: its path is the unit's key in the file. */
export const TERRAGRUNT_INCLUDE = "terragucci";
/** What a unit's terragrunt.hcl adds to take generate's settings. */
export const INCLUDE_BLOCK = `include "${TERRAGRUNT_INCLUDE}" {\n  path = find_in_parent_folders("${TERRAGRUNT_FILE}")\n}`;

/** Text for an HCL template: `${` and `%{` doubled, so Terragrunt writes the file as it is. */
const literal = (text: string): string => text.replace(/\$\{/g, () => "$${").replace(/%\{/g, () => "%%{");

/** A generated file's body without the marker: Terragrunt heads the file with its own signature. */
const unmarked = (content: string): string => content.slice(GENERATED_MARKER.length + 2);

/** An indented heredoc, Terragrunt's `contents`: the text indented under the attribute, `<<-EOT` strips it. */
function heredoc(text: string, indent: string): string {
  const body = literal(text).replace(/\n$/, "").split("\n").map((l) => (l ? `${indent}  ${l}` : "")).join("\n");
  return `<<-EOT\n${body}\n${indent}EOT`;
}

/** Every `.hcl` file Terragrunt reads, but terragucci.hcl and the caches. */
function hclFiles(repo: string): string[] {
  const out: string[] = [];
  const walk = (dir: string): void => {
    for (const name of readdirSync(dir)) {
      if (SKIP.has(name) || name.startsWith(".")) continue;
      const abs = join(dir, name);
      if (statSync(abs).isDirectory()) walk(abs);
      else if (name.endsWith(".hcl") && abs !== join(repo, TERRAGRUNT_FILE)) out.push(abs);
    }
  };
  walk(repo);
  return out.sort();
}

const hclComments = (text: string): string => text.replace(/\/\*[\s\S]*?\*\//g, "").replace(/(^|[^:"$])(#|\/\/).*$/gm, "$1");

/** Whether a unit's terragrunt.hcl includes terragucci.hcl as `include "terragucci"`. */
export function includesGenerated(text: string): boolean {
  return hclBlocks(hclComments(text), `include(?=\\s+"${TERRAGRUNT_INCLUDE}")`).some((b) => b.includes(TERRAGRUNT_FILE));
}

/**
 * terragucci.hcl for a Terragrunt repo: each unit's settings, resolved as a
 * plain root's are, in a map keyed by the unit's path, which Terragrunt
 * reads through `path_relative_to_include("terragucci")`. The backend goes
 * through `remote_state`, with `disable_init = true` unless generate sets
 * `disable_init: false` (by default Terragrunt makes no bucket: the backend
 * is the binary's, as for a plain root; with false, an apply job lets
 * Terragrunt bootstrap it, see backendBootstrap); the providers and the
 * versions through `generate` blocks, each off for a unit without them.
 * Written as `terragrunt hcl fmt` leaves it.
 */
export function renderTerragrunt(units: Map<string, RootSettings>): string | undefined {
  const rendered = new Map([...units].map(([u, s]) => [u, { s, files: renderRoot(s) }]));
  const withBackend = [...rendered].filter(([, r]) => r.s.backend).map(([u]) => u);
  if (withBackend.length > 0 && withBackend.length < rendered.size) {
    const without = [...rendered.keys()].filter((u) => !withBackend.includes(u));
    throw new ConfigError(`generate gives ${withBackend.join(", ")} a backend and not ${without.join(", ")}; terragucci.hcl gives every unit that includes it a remote_state, so give each unit a backend or none`);
  }
  const setsInit = [...rendered].filter(([, r]) => r.s.disableInit !== undefined).map(([u]) => u);
  if (withBackend.length === 0 && setsInit.length > 0) {
    throw new ConfigError(`generate sets disable_init for ${setsInit.join(", ")} and gives no unit a backend, so terragucci.hcl writes no remote_state for it; give the units a backend, or remove disable_init`);
  }
  // disable_init: one literal when every unit has the same, else each unit's own in the map.
  const inits = new Set([...rendered.values()].map((r) => r.s.disableInit ?? true));
  const perUnitInit = inits.size > 1;
  const has = (k: "providers" | "versions"): boolean => [...rendered.values()].some((r) => r.files[k] !== undefined);
  if (withBackend.length === 0 && !has("providers") && !has("versions")) return undefined;
  const keys = [...(withBackend.length ? ["backend", "config"] : []), ...(perUnitInit ? ["disable_init"] : []), ...(has("providers") ? ["providers"] : []), ...(has("versions") ? ["versions"] : [])];
  const width = Math.max(...keys.map((k) => k.length));
  const attr = (k: string, v: string): string => `      ${k.padEnd(width)} = ${v}`;
  const entries = [...rendered].sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0)).map(([u, r]) => {
    const lines = [`    ${hclString(u)} = {`];
    if (r.s.backend) lines.push(attr("backend", hclString(r.s.backend.type)), attr("config", backendConfig(r.s.backend)));
    if (perUnitInit) lines.push(attr("disable_init", String(r.s.disableInit ?? true)));
    for (const k of ["providers", "versions"] as const) {
      if (!keys.includes(k)) continue;
      const f = r.files[k];
      lines.push(attr(k, f === undefined ? '""' : heredoc(unmarked(f), "      ")));
    }
    lines.push("    }");
    return lines.join("\n");
  });
  const out = [
    GENERATED_MARKER,
    "#",
    "# Every unit includes it, in its terragrunt.hcl:",
    "#",
    ...INCLUDE_BLOCK.split("\n").map((l) => `#   ${l}`),
    "",
    "locals {",
    "  terragucci_units = {",
    entries.join("\n"),
    "  }",
    `  terragucci_unit = local.terragucci_units[path_relative_to_include("${TERRAGRUNT_INCLUDE}")]`,
    "}",
  ];
  if (withBackend.length) {
    const init = perUnitInit ? "local.terragucci_unit.disable_init" : String([...inits][0]);
    out.push("", "remote_state {", "  backend      = local.terragucci_unit.backend", `  disable_init = ${init}`, "", "  generate = {", `    path      = "${GENERATED_FILES.backend}"`, '    if_exists = "overwrite_terragrunt"', "  }", "", "  config = local.terragucci_unit.config", "}");
  }
  for (const k of ["providers", "versions"] as const) {
    if (!keys.includes(k)) continue;
    out.push("", `generate "terragucci_${k}" {`, `  path      = "${GENERATED_FILES[k]}"`, '  if_exists = "overwrite_terragrunt"', `  disable   = local.terragucci_unit.${k} == ""`, `  contents  = local.terragucci_unit.${k}`, "}");
  }
  return out.join("\n") + "\n";
}

/**
 * A unit's backend config as terragucci.hcl gives it: the attribute that holds
 * the state key (`key`, gcs's `prefix`, local's `path`, http's `address` and
 * its lock addresses) reads
 * TERRAGUCCI_EPHEMERAL_SUFFIX, which is empty but in an ephemeral copy's run,
 * where it is `-pr-<n>`, before a closing `.tfstate` or at the end. So the
 * key is the one terragucci.yml gives everywhere else, and every unit can be
 * copied per pull request (ephemeral.ts).
 */
function backendConfig(backend: NonNullable<RootSettings["backend"]>): string {
  const attribute = KEY_ATTRIBUTE[backend.type];
  const key = attribute ? backend.config[attribute] : undefined;
  if (typeof key !== "string") return hclValue(backend.config);
  const marker = "\u0000terragucci-suffix\u0000";
  const k = key.replace(/\/+$/, "");
  const marked = /\.tfstate$/.test(k) ? k.replace(/\.tfstate$/, `${marker}.tfstate`) : `${k}${marker}`;
  const config: Record<string, unknown> = { ...backend.config, [attribute!]: marked };
  // A GitLab state's lock is `<address>/lock`: its state name takes the suffix too, so a copy locks its own state.
  if (backend.type === "http") {
    for (const name of HTTP_LOCK_ATTRIBUTES) {
      const v = backend.config[name];
      if (typeof v === "string" && /\/lock\/?$/.test(v)) config[name] = v.replace(/\/lock\/?$/, `${marker}/lock`);
    }
  }
  return hclValue(config).replaceAll(marker, () => `\${${SUFFIX_READ}}`);
}

/**
 * Whether an apply job lets Terragrunt bootstrap the backend
 * (`TG_BACKEND_BOOTSTRAP`): when generate gives any Terragrunt unit
 * `disable_init: false`. Terragrunt then creates a missing bucket and brings
 * an existing one to its settings (versioning, encryption, access), so only
 * an apply job does it: a pull request's plan runs its own code with the plan
 * role, and leaves the bucket as it is.
 */
export function backendBootstrap(repo: string, settings: Pick<ResolvedSettings, "generate" | "terragrunt" | "version" | "binary">): boolean {
  const gen = settings.generate;
  if (!gen) return false;
  const levels = [gen, ...Object.values(gen.dirs ?? {}), ...Object.values(gen.roots ?? {})];
  if (!levels.some((l) => l?.disable_init === false)) return false;
  return walkUnits(repo, settings.terragrunt?.exclude).some((u) => rootSettings(gen, u.path, settings).disableInit === false);
}

/** generate in a Terragrunt repo: terragucci.hcl, and why a unit or another file would keep it from taking effect. */
function planTerragrunt(repo: string, settings: ResolvedSettings, stacks: readonly string[]): GeneratePlan {
  const path = join(repo, TERRAGRUNT_FILE);
  const before = existsSync(path) ? readFileSync(path, "utf-8") : undefined;
  const files: FileChange[] = [];
  const foreign: string[] = [];
  const gen = settings.generate;
  // A stack's units from its stack file, generated or not; the walk finds them only once they are.
  const generated = gen ? explicitStackUnits(repo, stacks) : [];
  const units = gen ? [...walkUnits(repo, settings.terragrunt?.exclude).map((u) => u.path).filter((u) => generatingStack(u) === undefined), ...generated.map((g) => g.unit)].sort() : [];
  const notes: string[] = [];
  for (const u of Object.keys(gen?.roots ?? {})) {
    if (!units.includes(u.replace(/\/+$/, ""))) throw new ConfigError(`generate.roots names ${u}, which is not a Terragrunt unit in the repo`);
  }
  const content = gen ? renderTerragrunt(new Map(units.map((u) => [u, rootSettings(gen, u, settings)]))) : undefined;
  if (content !== undefined) {
    if (before !== undefined && !before.startsWith(GENERATED_MARKER)) {
      foreign.push(`${TERRAGRUNT_FILE} exists and terragucci did not write it; move what it declares into terragucci.yml's generate key and remove it, or rename it`);
    } else files.push({ path, status: before === undefined ? "created" : before === content ? "unchanged" : "updated", content });
    for (const u of units) {
      if (generatingStack(u) !== undefined) continue;
      const text = readFileSync(join(repo, u, "terragrunt.hcl"), "utf-8");
      if (!includesGenerated(text)) foreign.push(`${u}/terragrunt.hcl does not include ${TERRAGRUNT_FILE}, so generate's settings never reach it; add ${INCLUDE_BLOCK.replace(/\n\s*/g, " ")}`);
    }
    // A generated unit's terragrunt.hcl is its template's: the template must include terragucci.hcl.
    for (const g of generated) {
      const tpl = g.template !== undefined ? join(repo, g.template, "terragrunt.hcl") : undefined;
      if (tpl === undefined || !existsSync(tpl)) {
        notes.push(`${g.unit}: ${g.file} generates it from a template outside the repo, so generate cannot check that it includes ${TERRAGRUNT_FILE}`);
        continue;
      }
      if (!includesGenerated(readFileSync(tpl, "utf-8"))) foreign.push(`${g.template}/terragrunt.hcl does not include ${TERRAGRUNT_FILE}, so generate's settings never reach ${g.unit}, which ${g.file} generates from it; add ${INCLUDE_BLOCK.replace(/\n\s*/g, " ")}`);
    }
    // Another remote_state, or a generate block for a file terragucci.hcl writes, would contend with it in the units that include both.
    const writes = new Set<string>([...(content.includes("remote_state {") ? [GENERATED_FILES.backend] : []), ...(["providers", "versions"] as const).filter((k) => content.includes(`generate "terragucci_${k}"`)).map((k) => GENERATED_FILES[k])]);
    for (const f of hclFiles(repo)) {
      const text = hclComments(readFileSync(f, "utf-8"));
      if (writes.has(GENERATED_FILES.backend) && /^\s*remote_state\s*\{/m.test(text)) foreign.push(`${rel(repo, f)} declares remote_state, and ${TERRAGRUNT_FILE} gives each unit its backend from generate; remove one of them`);
      // generate "<name>" blocks only: remote_state's own `generate = {` is its backend, which the line above covers.
      for (const b of hclBlocks(text, 'generate(?=\\s+")')) {
        const target = /^\s*path\s*=\s*"([^"]+)"/m.exec(b)?.[1];
        if (target && writes.has(target)) foreign.push(`${rel(repo, f)} has a generate block that writes ${target}, which ${TERRAGRUNT_FILE} writes from generate; remove one of them`);
      }
    }
  } else if (before?.startsWith(GENERATED_MARKER)) files.push({ path, status: "removed", content: "" });
  // Files a plain root's generate wrote are left over here: generate removes them.
  for (const p of generatedOnDisk(repo)) files.push({ path: p, status: "removed", content: "" });
  return { roots: units, terragrunt: true, files, foreign, ...(notes.length ? { notes } : {}) };
}

/** The lines that differ, `-` what the file holds and `+` what generate writes. */
export function lineDiff(have: string, want: string): string[] {
  const a = have.split("\n");
  const b = want.split("\n");
  const n = a.length;
  const m = b.length;
  const lcs: number[][] = Array.from({ length: n + 1 }, () => new Array<number>(m + 1).fill(0));
  for (let i = n - 1; i >= 0; i--) for (let j = m - 1; j >= 0; j--) lcs[i][j] = a[i] === b[j] ? lcs[i + 1][j + 1] + 1 : Math.max(lcs[i + 1][j], lcs[i][j + 1]);
  const out: string[] = [];
  let i = 0;
  let j = 0;
  while (i < n || j < m) {
    if (i < n && j < m && a[i] === b[j]) {
      i++;
      j++;
    } else if (i < n && (j >= m || lcs[i + 1][j] >= lcs[i][j + 1])) out.push(`-${a[i++]}`);
    else out.push(`+${b[j++]}`);
  }
  return out;
}

/**
 * `generate --check`: tf-check's step. Passes when every generated file is
 * what generate writes; each one that differs, is missing, is no longer asked
 * for, or sits where a file terragucci did not write is, is refused by name.
 */
export function checkGenerated(repo: string, settings: ResolvedSettings): CheckResult {
  const plan = planGenerate(repo, settings);
  const log: string[] = [];
  const report: string[] = ["### Generated files", ""];
  for (const f of plan.files) {
    const path = rel(repo, f.path);
    if (f.status === "unchanged") continue;
    if (f.status === "created") log.push(`refused: ${path} is missing; terragucci generate writes it from terragucci.yml`);
    else if (f.status === "removed") log.push(`refused: ${path} was generated, and terragucci.yml no longer asks for it`);
    else {
      log.push(`refused: ${path} differs from what terragucci generate writes from terragucci.yml:`);
      for (const l of lineDiff(readFileSync(f.path, "utf-8"), f.content)) log.push(`    ${l}`);
    }
  }
  for (const line of plan.foreign) log.push(`refused: ${line}`);
  for (const line of plan.notes ?? []) log.push(`note: ${line}`);
  const refused = log.filter((l) => l.startsWith("refused: "));
  for (const l of refused) report.push(`- ${l}`);
  if (refused.length) {
    log.push(`FAILED generate: ${refused.length} generated file${refused.length === 1 ? "" : "s"} out of line with terragucci.yml; run terragucci generate and commit what it writes`);
    return { ok: false, log, report: [...report, ""] };
  }
  const n = plan.files.length;
  const where = plan.terragrunt ? `for ${plan.roots.length} unit${plan.roots.length === 1 ? "" : "s"}` : `in ${plan.roots.length} root${plan.roots.length === 1 ? "" : "s"}`;
  const line = `generated files match terragucci.yml: ${n} file${n === 1 ? "" : "s"} ${where}`;
  return { ok: true, log: [...(plan.notes ?? []).map((l) => `note: ${l}`), line], report: [...report, `- ${line}`, ""] };
}

/** What `terragucci generate` prints. */
export function describeGenerate(repo: string, plan: GeneratePlan, dryRun: boolean): string {
  const verb = (s: FileChange["status"]): string =>
    s === "unchanged" ? "unchanged" : dryRun ? (s === "created" ? "would write" : s === "removed" ? "would remove" : "would update") : s === "created" ? "wrote" : s === "removed" ? "removed" : "updated";
  const lines = plan.files.map((f) => `${verb(f.status)} ${rel(repo, f.path)}`);
  const changed = plan.files.filter((f) => f.status !== "unchanged").length;
  const where = plan.terragrunt ? `for ${plan.roots.length} unit${plan.roots.length === 1 ? "" : "s"}` : `in ${plan.roots.length} root${plan.roots.length === 1 ? "" : "s"}`;
  for (const l of plan.notes ?? []) lines.push(`note: ${l}`);
  lines.push(`${plan.files.length} generated file${plan.files.length === 1 ? "" : "s"} ${where}, ${changed} ${dryRun ? "to change; nothing was written" : "changed"}`);
  return lines.join("\n");
}

/**
 * A control repo's project's `generate`, as written into the project's own
 * terragucci.yml: the project file carries no `version`, so a version the
 * control repo gives every root becomes the repo level's `required_version`,
 * and the project's tf-check still sees what reconcile generated.
 */
export function projectGenerate(settings: Pick<ResolvedSettings, "generate" | "version" | "binary">): GenerateSettings | undefined {
  const g = settings.generate;
  if (!g || g.required_version !== undefined || typeof settings.version !== "string" || settings.binary === "choudoufu") return g;
  return { ...g, required_version: settings.version };
}
