/**
 * The pipeline terragucci writes into a repo, rendered through chant's forge
 * lexicons so GitHub, Forgejo and GitLab get the same jobs in their own syntax.
 *
 * check  every push: format check and validate, for every root.
 * plan   pull requests from the same repo: `terragucci stage tf-plan` plans
 *        the roots the change reaches against the target branch, and the
 *        roots that read their state, in apply order, and writes the plan
 *        report, kept as the job's artifact (and in a bucket when one is
 *        named). Its note, chant's grouped summary across those roots, is the
 *        one plan note and its counts the one terragucci/plan status.
 *        Read-only role.
 * apply  pushes to the default branch: one job per wave, canary first, each
 *        needing the one before. `terragucci stage tf-apply` plans the wave,
 *        and a wave the gate policy holds waits for a person's approval of
 *        its set digest (`chant approve`); one whose plans changed after the
 *        approval applies nothing. A root that reads another's state applies
 *        after it. One apply per project at a time; posts one
 *        terragucci/apply status and marks plan notes the push made stale.
 *        A Terragrunt repo applies every wave in one job.
 *
 * drift  only when `drift:` names a schedule: `terragucci stage tf-drift` plans
 *        every root with -refresh-only, keeps the same report, and opens,
 *        updates or closes the project's one drift issue. It never applies.
 *        Read-only role. On GitLab the schedule itself is set in the
 *        project's CI/CD schedules; the job runs for scheduled pipelines.
 *
 * The stages terragucci is building take these jobs' place as they ship;
 * the file stays where it is.
 */
// Each lexicon's serializer and generated entities, never its entry point: the
// entry points carry lint rules, codegen and the TypeScript compiler, which the
// bundle must not (terragucci#18).
import { Job, Step, Workflow } from "@intentius/chant-lexicon-github/generated/index";
import { githubSerializer } from "@intentius/chant-lexicon-github/serializer";
import { applyForgejoDialect } from "@intentius/chant-lexicon-forgejo/dialect";
import { Image, Job as GitLabJob, Rule } from "@intentius/chant-lexicon-gitlab/generated/index";
import { gitlabSerializer } from "@intentius/chant-lexicon-gitlab/serializer";

/** Forgejo is the github dialect with Forgejo's runner labels and action refs. */
const forgejoSerializer = {
  serialize(entities: Map<string, never>): ReturnType<typeof githubSerializer.serialize> {
    return githubSerializer.serialize(applyForgejoDialect(entities as never, {}).entities as never);
  },
};
import { responseTo, type Binary, type ForgeName, type Gate, type RespondEvent, type RolePair } from "./config";
import { DEFAULT_TOKEN_ENV } from "./forge";
import { applyWaves } from "./apply";
import type { Tool } from "./install";
import {
  cacheExports,
  credentialsScript,
  forgeCache,
  terragruntApplyBody,
  terragruntCheckScript,
  terragruntJobEnv,
  type TerragruntPipelineInput,
} from "./render-terragrunt";

export const MARKER = "# Generated by terragucci.";

export const PIPELINE_PATHS: Record<ForgeName, string> = {
  github: ".github/workflows/terragucci.yml",
  forgejo: ".forgejo/workflows/terragucci.yml",
  gitlab: ".gitlab-ci.yml",
};

export interface PipelineInput {
  forge: ForgeName;
  binary: Binary;
  version: string;
  /** The job image, as a pipeline names it (tag, and digest once published). */
  image: string;
  /** Set when the repo pins a version the image does not carry: the job installs it. */
  install?: { binary: Binary; version: string };
  /** Roots in apply order: each inner list applies together. In Terragrunt mode, units by wave. */
  layers: string[][];
  /** Set for a Terragrunt repo: the jobs run Terragrunt over its units. */
  terragrunt?: TerragruntPipelineInput & { installs: { tool: Tool; version: string }[] };
  env: Record<string, string>;
  /** Cloud roles the jobs assume over OIDC: plan reads, apply writes. */
  oidc?: { plan_role: string; apply_role: string; audience?: string };
  /** The environment variable holding the forge token, where the forge's own job token cannot post statuses (GitLab). */
  tokenEnv?: string;
  /** The secret holding `OTEL_EXPORTER_OTLP_HEADERS`, mapped into the environment of the plan, apply and drift jobs. */
  headersSecret?: string;
  /** The variable holding the decision service's key (`decide.token_env`), for the plan jobs of a repo with respond.description on. A secret of that name is mapped into their environment on GitHub and Forgejo; GitLab's CI variables are already there. */
  decideTokenEnv?: string;
  /** A bucket for plan reports, besides the job's artifact. */
  reports?: PlanReportInput["reports"];
  /** Set when `modules.publish` is: the pipeline gets a job that publishes changed modules after apply. */
  publish?: boolean;
  /** A cron schedule: the pipeline gets a drift job that runs on it. */
  drift?: string;
  /** Globs for the canary wave, which applies first. Plain roots only. */
  canary?: string[];
  /** When a wave waits for an approval. Default on-destroy. Plain roots only. */
  gate?: Gate;
  /** The response to each event, from `respond:`; the jobs call `terragucci respond` for each one that is not off. */
  respond?: Partial<Record<RespondEvent, string>>;
}

export interface RenderedPipeline {
  path: string;
  content: string;
}

export class RenderError extends Error {}

/** Whether the pipeline calls `terragucci respond` for an event: its setting is not off. */
const responds = (r: PipelineInput["respond"], event: RespondEvent): boolean => responseTo({ respond: r }, event) !== "off";

/**
 * A response that pushes or opens a pull request needs the forge token under the
 * name respond reads, and on GitLab a remote that can push. A response that
 * fails never fails the job: it is help on top of a result already decided.
 */
function respondSetup(forge: ForgeName, tokenEnv?: string): string[] {
  return [
    `export ${tokenEnv ?? DEFAULT_TOKEN_ENV[forge]}="$TG_TOKEN"`,
    ...(forge === "gitlab" ? ['git remote set-url origin "https://oauth2:${TG_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git"'] : []),
  ];
}

/** The fmt commit after a failing check, on a branch other than the default branch. Never an approval, never a push to the default branch. */
export function fmtScript(binary: Binary, forge: ForgeName, tokenEnv?: string): string {
  return [
    "set -u",
    ...respondSetup(forge, tokenEnv),
    `terragucci respond fmt --mode apply --binary ${binary} --branch "${forge === "gitlab" ? "$CI_COMMIT_BRANCH" : "$GITHUB_REF_NAME"}" || true`,
  ].join("\n");
}

/** The tips response: one small pull request per tip, from the default branch after the apply. A response that fails never fails the job. */
export function tipsScript(binary: Binary, forge: ForgeName, tokenEnv?: string): string {
  return ["set -u", ...respondSetup(forge, tokenEnv), `terragucci respond tips --mode apply --binary ${binary} || true`].join("\n");
}

/**
 * The version-bump response: a release pull request per module whose next version the commits do not
 * settle, from the default branch after the apply. It needs the full history and the tags, and the
 * decision service's key when `decide:` is set. A response that fails never fails the job.
 */
export function versionBumpScript(forge: ForgeName, tokenEnv?: string): string {
  return ["set -u", ...respondSetup(forge, tokenEnv), "terragucci respond version-bump --mode apply || true"].join("\n");
}

/** Where `terragucci respond` writes an agent's input, kept with the job when a response is `agent`. */
const RESPOND_DIR = "terragucci-respond";

const sh = (s: string): string => `'${s.replace(/'/g, `'\\''`)}'`;

/** The step that puts a pinned version the image does not carry on the path. */
export function installScript(binary: Binary | Tool, version: string, forge: ForgeName): string {
  const dir = `dir="$(terragucci install ${binary} ${version})"`;
  return forge === "gitlab" ? `${dir}\nexport PATH="$dir:$PATH"` : `${dir}\necho "$dir" >> "$GITHUB_PATH"`;
}

export function checkScript(binary: Binary, roots: string[]): string {
  return [
    "set -eu",
    `${binary} fmt -check -recursive -diff .`,
    `for dir in ${roots.map(sh).join(" ")}; do`,
    `  ${binary} -chdir="$dir" init -backend=false -input=false -no-color >/dev/null`,
    `  ${binary} -chdir="$dir" validate -no-color >/dev/null`,
    '  echo "valid $dir"',
    "done",
  ].join("\n");
}

/**
 * The forge calls the pipeline makes beyond running the binary: commit statuses,
 * the plan note, marking a note stale, and the OIDC token. Plain Node, because
 * the CI images carry node and git but not curl or jq. A failed status or note
 * never fails the job; a failed token request does.
 */
const FORGE_API_JS = [
  'import { writeFileSync, readFileSync } from "node:fs";',
  "const [cmd, ...a] = process.argv.slice(1);",
  "const e = process.env, gl = e.TG_FORGE === \"gitlab\", tok = e.TG_TOKEN;",
  'const MARK = "<!-- terragucci:plan";',
  "try {",
  '  if (cmd === "oidc") {',
  '    const r = await fetch(e.ACTIONS_ID_TOKEN_REQUEST_URL + "&audience=" + encodeURIComponent(a[1]), { headers: { authorization: "bearer " + e.ACTIONS_ID_TOKEN_REQUEST_TOKEN } });',
  '    if (!r.ok) throw new Error("the OIDC token request answered " + r.status + "; the job needs permission to request an OIDC token");',
  "    writeFileSync(a[0], (await r.json()).value, { mode: 0o600 });",
  "  } else if (!tok) {",
  '    console.log("terragucci: no forge token, so no " + cmd);',
  "  } else {",
  '    const api = gl ? e.CI_API_V4_URL : e.GITHUB_API_URL || e.GITHUB_SERVER_URL + "/api/v1";',
  '    const repo = gl ? "projects/" + e.CI_PROJECT_ID : "repos/" + e.GITHUB_REPOSITORY;',
  "    const call = async (m, p, b) => {",
  '      const r = await fetch(api + "/" + p, { method: m, headers: { "content-type": "application/json", ...(gl ? { "private-token": tok } : { authorization: "token " + tok }) }, body: b ? JSON.stringify(b) : undefined });',
  '      if (!r.ok) throw new Error(m + " " + p + " answered " + r.status);',
  "      return r.status === 204 ? null : r.json();",
  "    };",
  '    const notes = (n) => gl ? repo + "/merge_requests/" + n + "/notes" : repo + "/issues/" + n + "/comments";',
  '    const find = async (n) => (await call("GET", notes(n) + "?per_page=100")).find((c) => c.body.startsWith(MARK));',
  '    const edit = (n, id, body) => gl ? call("PUT", notes(n) + "/" + id, { body }) : call("PATCH", repo + "/issues/comments/" + id, { body });',
  '    if (cmd === "status") {',
  "      const [context, state, description] = a;",
  '      const url = gl ? e.CI_PIPELINE_URL : e.GITHUB_SERVER_URL + "/" + e.GITHUB_REPOSITORY + "/actions/runs/" + e.GITHUB_RUN_ID;',
  '      const sha = e.TG_SHA;',
  '      if (gl) await call("POST", repo + "/statuses/" + sha, { name: context, state: { pending: "running", success: "success", failure: "failed" }[state], description, target_url: url });',
  '      else await call("POST", repo + "/statuses/" + sha, { context, state, description, target_url: url });',
  '    } else if (cmd === "note") {',
  "      const body = readFileSync(a[0], \"utf-8\"), old = await find(e.TG_PR);",
  '      if (old) await edit(e.TG_PR, old.id, body); else await call("POST", notes(e.TG_PR), { body });',
  '    } else if (cmd === "reply") {',
  '      await call("POST", notes(e.TG_PR), { body: "terragucci: " + a[0] });',
  '    } else if (cmd === "alive") {',
  '      const run = await call("GET", repo + "/actions/runs/" + a[0]);',
  '      console.log(["success", "failure", "cancelled", "skipped", "completed"].includes(run.status) ? "dead" : "alive");',
  '    } else if (cmd === "stale") {',
  '      const moved = a[0].split(",");',
  '      const open = gl ? await call("GET", repo + "/merge_requests?state=opened&target_branch=" + a[1] + "&per_page=100") : await call("GET", repo + "/pulls?state=open&base=" + a[1] + "&per_page=100");',
  "      for (const pr of open) {",
  "        const n = gl ? pr.iid : pr.number, note = await find(n);",
  "        if (!note || note.body.includes(\"<!-- terragucci:stale -->\")) continue;",
  '        const hit = (note.body.match(/roots=(\\S*) -->/)?.[1] ?? "").split(",").filter((r) => moved.includes(r));',
  "        if (!hit.length) continue;",
  '        const lines = note.body.split("\\n");',
  '        lines.splice(1, 0, "> This plan is stale: " + a[1] + " moved under " + hit.join(", ") + ". Push to this pull request to plan again. <!-- terragucci:stale -->");',
  '        await edit(n, note.id, lines.join("\\n"));',
  "      }",
  "    }",
  "  }",
  "} catch (err) {",
  '  console.log("terragucci: " + cmd + " failed: " + err.message);',
  '  if (cmd === "oidc") process.exit(1);',
  "}",
].join("\n");

/** Shell that defines `tg`, the forge calls above. */
export function forgeApi(forge: ForgeName): string {
  return [`export TG_FORGE=${forge}`, `tg() { node --input-type=module -e '${FORGE_API_JS}' -- "$@"; }`].join("\n");
}

const AUDIENCE = "sts.amazonaws.com";

/** What a job that got no OIDC token needs, by forge. */
const NO_TOKEN: Record<Exclude<ForgeName, "gitlab">, string> = {
  github: "the job needs permissions: id-token: write",
  forgejo: "Forgejo serves one from version 15, with Forgejo Runner 12.5 or later, to a job that sets enable-openid-connect: true; on an older Forgejo leave oidc unset and give the runner static credentials",
};

/**
 * Write the job's OIDC token to `$AWS_WEB_IDENTITY_TOKEN_FILE`, or stop the job:
 * the scripts run without `set -e`, and a job that went on would plan or apply
 * with whatever credentials the runner happens to hold.
 */
export function tokenScript(forge: ForgeName, audience = AUDIENCE): string {
  if (forge === "gitlab") return 'printf \'%s\' "$TERRAGUCCI_OIDC" >"$AWS_WEB_IDENTITY_TOKEN_FILE"';
  return [
    'if [ -z "${ACTIONS_ID_TOKEN_REQUEST_URL:-}" ]; then',
    `  echo ${sh(`terragucci: the runner served this job no OIDC token (no ACTIONS_ID_TOKEN_REQUEST_URL); ${NO_TOKEN[forge]}`)} >&2`,
    "  exit 1",
    "fi",
    `tg oidc "$AWS_WEB_IDENTITY_TOKEN_FILE" ${sh(audience)} || exit 1`,
  ].join("\n");
}

export function oidcScript(forge: ForgeName, role: string, session: string, audience = AUDIENCE): string {
  const token = tokenScript(forge, audience);
  return [
    `export AWS_ROLE_ARN=${sh(role)} AWS_ROLE_SESSION_NAME=${sh(session)}`,
    'export AWS_WEB_IDENTITY_TOKEN_FILE="$(mktemp)"',
    token,
  ].join("\n");
}

/** Roots that changed in the push, or all of them when the push cannot be diffed. */
export function movedRoots(roots: string[]): string {
  return [
    'if [ -n "${TG_BEFORE:-}" ] && [ "${TG_BEFORE#0000000}" = "$TG_BEFORE" ] && git fetch -q --depth=1 origin "$TG_BEFORE" 2>/dev/null; then',
    '  changed="$(git diff --name-only "$TG_BEFORE" HEAD)"',
    "else",
    "  changed=",
    "fi",
    'moved=""',
    `for dir in ${roots.map(sh).join(" ")}; do`,
    '  if [ -z "$changed" ] || printf \'%s\\n\' "$changed" | grep -q "^$dir/"; then moved="${moved:+$moved,}$dir"; fi',
    "done",
  ].join("\n");
}

/**
 * Applies on Forgejo run one at a time through a tag on the remote. The tag
 * points at a commit whose subject is the holder's lease, "run <id> <epoch>".
 * A runner that kills a job never runs its exit trap, so a waiter takes the
 * lock over, atomically, when the holder's run is no longer running or the
 * lease is older than TG_LOCK_STALE seconds. A run that finds a newer push on
 * the branch stands down, since that push applies the whole tree.
 */
export function forgejoLock(): string {
  const id = '${GITHUB_RUN_ID:-$$}';
  return [
    'lock_ref="refs/tags/terragucci-apply-lock"',
    'empty="$(git mktree </dev/null)"',
    `mine="$(GIT_AUTHOR_NAME=terragucci GIT_AUTHOR_EMAIL=terragucci@localhost GIT_COMMITTER_NAME=terragucci GIT_COMMITTER_EMAIL=terragucci@localhost git commit-tree "$empty" -m "run ${id} $(date +%s)")"`,
    "tries=0",
    'until git push -q origin "$mine:$lock_ref" 2>/dev/null; do',
    '  held="$(git ls-remote origin "$lock_ref" | cut -f1)"',
    '  if [ -n "$held" ] && git fetch -q origin "+$lock_ref:$lock_ref" 2>/dev/null; then',
    '    lease="$(git log -1 --format=%s "$lock_ref")"',
    '    holder="$(echo "$lease" | cut -d" " -f2)"; since="$(echo "$lease" | cut -d" " -f3)"',
    '    if [ "$(tg alive "$holder")" = dead ] || [ $(( $(date +%s) - ${since:-0} )) -ge "${TG_LOCK_STALE:-7200}" ]; then',
    '      echo "the apply lock was held by run $holder, which is gone; taking it over"',
    '      git push -q --force-with-lease="$lock_ref:$held" origin "+$mine:$lock_ref" 2>/dev/null && break',
    "    fi",
    "  fi",
    '  if [ "$tries" -ge 360 ]; then echo "another apply has held $lock_ref for an hour" >&2; exit 1; fi',
    '  sleep "${TG_LOCK_POLL:-10}"; tries=$((tries + 1))',
    "done",
    "trap 'git push -q --force-with-lease=\"$lock_ref:$mine\" origin \":$lock_ref\" || true' EXIT",
    'tip="$(git ls-remote origin "refs/heads/${GITHUB_REF_NAME}" | cut -f1)"',
    'if [ -n "$tip" ] && [ "$tip" != "$GITHUB_SHA" ]; then',
    '  echo "a newer push to ${GITHUB_REF_NAME} applies everything; standing down"',
    '  tg status terragucci/apply success "superseded by a newer push"',
    "  exit 0",
    "fi",
  ].join("\n");
}

/** Which wave an apply job runs, and how the waves are cut and gated. */
export interface ApplyWaveInput {
  /** 1-based. */
  wave: number;
  /** Globs for wave 1, from `waves.canary`. */
  canary?: string[];
  gate?: Gate;
  /** The response to each event; apply-failed and wave-refused are called from the wave's exit code. */
  respond?: PipelineInput["respond"];
}

/**
 * One wave's apply job: `terragucci stage tf-apply` plans the wave's roots,
 * decides the wave's gate against its set digest, and applies the plans it
 * made. The first wave marks stale plan notes and posts the pending status;
 * the last posts the one success. A wave that waits for an approval, or whose
 * plans changed after one, says so in the status and fails the job, so the
 * waves after it do not start.
 */
export function applyScript(
  binary: Binary,
  layers: string[][],
  forge: ForgeName = "github",
  oidc?: PipelineInput["oidc"],
  input: ApplyWaveInput = { wave: 1 },
): string {
  const roots = layers.flat().sort();
  const total = layers.flat().length;
  const gate = input.gate ?? "on-destroy";
  const count = applyWaves(layers, input.canary).length;
  const first = input.wave === 1;
  const last = input.wave === count;
  const triage = responds(input.respond, "apply-failed");
  const refused = responds(input.respond, "wave-refused");
  const args = [
    "--wave", String(input.wave),
    "--layers", sh(layers.map((l) => l.join(",")).join(";")),
    ...(input.canary?.length ? ["--canary", sh(input.canary.join(","))] : []),
    "--binary", binary,
    "--gate", gate,
  ];
  return [
    "set -uo pipefail",
    forgeApi(forge),
    ...(oidc ? [oidcScript(forge, oidc.apply_role, "terragucci-apply", oidc.audience)] : []),
    ...(first
      ? [movedRoots(roots), '# The base branch moved under these roots: plan notes that cover them are stale.', 'tg stale "$moved" "${TG_BRANCH:-}"']
      : []),
    ...(forge === "forgejo" ? [forgejoLock()] : []),
    ...(first ? ['tg status terragucci/apply pending "applying"'] : []),
    // A waiting wave records what it planned on the chant/lifecycle branch, so the job's checkout must be able to push.
    ...(forge === "gitlab" && gate !== "never" ? ['git remote set-url origin "https://oauth2:${TG_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git"'] : []),
    'outcome="$(mktemp)"',
    ...(triage ? ['log="$(mktemp)"'] : []),
    `TG_OUTCOME="$outcome" terragucci stage tf-apply ${args.join(" ")}${triage ? ' 2>&1 | tee "$log"' : ""}`,
    triage ? "rc=${PIPESTATUS[0]}" : "rc=$?",
    'case "$rc" in',
    "  0) ;;",
    '  3) tg status terragucci/apply pending "$(cat "$outcome")"; exit 3 ;;',
    // A wave waiting at a gate (3) is not a failure. A refused wave (4) and a failed apply are, and each gets its response before the job fails.
    `  4) tg status terragucci/apply failure "$(cat "$outcome")"; ${refused ? `terragucci respond wave-refused --wave ${input.wave} --approved ${REPORT_DIR}/approved --current ${REPORT_DIR}/current || true; ` : ""}exit 4 ;;`,
    `  *) tg status terragucci/apply failure "an apply failed"; ${triage ? 'terragucci respond apply-failed --log "$log" || true; ' : ""}exit 1 ;;`,
    "esac",
    ...(last
      ? [`tg status terragucci/apply success "${total} roots in ${layers.length} groups applied"`, 'echo "all roots applied"']
      : [`echo "wave ${input.wave} of ${count} applied"`]),
  ].join("\n");
}

/** Shell for a Terragrunt job's credentials: the auth provider, and the OIDC token when `oidc` did not fetch it. */
function terragruntCredentials(forge: ForgeName, phase: "plan" | "apply", oidc: PipelineInput["oidc"], credentials?: Record<string, RolePair>): string[] {
  if (!credentials || Object.keys(credentials).length === 0) return [];
  return [credentialsScript(credentials, phase, oidc ? undefined : tokenScript(forge, AUDIENCE))];
}

/** A Terragrunt repo's apply: the stale notes, the lock and status as for roots, then one `run --all` per wave. */
export function terragruntApplyScript(
  waves: string[][],
  forge: ForgeName = "github",
  oidc?: PipelineInput["oidc"],
  credentials?: Record<string, RolePair>,
  respond?: PipelineInput["respond"],
): string {
  return [
    "set -uo pipefail",
    forgeApi(forge),
    ...(oidc ? [oidcScript(forge, oidc.apply_role, "terragucci-apply", oidc.audience)] : []),
    ...terragruntCredentials(forge, "apply", oidc, credentials),
    movedRoots(waves.flat().sort()),
    '# The base branch moved under these units: plan notes that cover them are stale.',
    'tg stale "$moved" "${TG_BRANCH:-}"',
    ...(forge === "forgejo" ? [forgejoLock()] : []),
    'tg status terragucci/apply pending "applying"',
    ...terragruntApplyBody(waves, responds(respond, "apply-failed")),
  ].join("\n");
}

/** Where a plan job's report is kept, and what the stage needs beyond the roots. */
export interface PlanReportInput {
  /** Copy the report to this bucket as well as keeping it with the job. */
  reports?: { bucket: string; endpoint?: string; prefix?: string; url?: string };
  /** Globs for the canary wave the report shows. */
  canary?: string[];
  /** A Terragrunt repo: the stage runs Terragrunt, after this shell (credentials, caches). */
  terragrunt?: { prelude: string };
  /** respond.description is on: before the note is posted, flag a pull request whose description does not match its plan. */
  description?: boolean;
}

/** The plan report's directory in the job's workspace. */
export const REPORT_DIR = "terragucci-report";

/**
 * Where the note links the HTML report when the bucket's address is not
 * configured: the job's artifact on GitLab, the run elsewhere, where the
 * report is a download in the run's artifacts and the note says so. With
 * `reports.url` the stage links the bucket's copy instead.
 */
function reportUrl(forge: ForgeName): string {
  return forge === "gitlab"
    ? `"$CI_JOB_URL/artifacts/file/${REPORT_DIR}/report.html"`
    : '"$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"';
}

/** The status line from the report: roots, groups, destroys and replacements, and refusals. */
const COUNTS_JS =
  'const r=JSON.parse(require("fs").readFileSync(process.argv[1],"utf-8"));' +
  'const n=(a)=>r.named.filter((x)=>a.includes(x.action)).length;' +
  'const f=n(["refused"]);' +
  'console.log((f?f+" failed: ":"")+r.roots.length+" roots, "+r.groups.length+" groups, "+n(["delete","replace"])+" destroys")';

/** "yes" when the plan report planned nothing and held nothing back: the change reaches no root. */
const UNREACHED_JS = 'const r=JSON.parse(require("fs").readFileSync(process.argv[1],"utf-8"));console.log(r.roots.length===0&&!(r.deferred||[]).length?"yes":"")';

/** The roots (or units) a plan report planned, comma-separated, for the note's first line. */
const PLANNED_JS = 'console.log(JSON.parse(require("fs").readFileSync(process.argv[1],"utf-8")).roots.map((x)=>x.path).join(","))';

/**
 * The pull request stage: `terragucci stage tf-plan` plans the roots the
 * change reaches, in apply order, and writes the plan report. The report's
 * note is posted as the one plan note, and its counts are the one
 * terragucci/plan status.
 */
export function planScript(binary: Binary, layers: string[][], forge: ForgeName = "github", oidc?: PipelineInput["oidc"], report: PlanReportInput = {}, replan = false): string {
  const args = [
    "--out", REPORT_DIR,
    "--binary", binary,
    "--layers", sh(layers.map((l) => l.join(",")).join(";")),
    "--report-url", reportUrl(forge),
    // A re-plan names its root, when the comment did; TG_BASE (set by replanPrelude) is the range it reads.
    ...(replan ? ['${TG_ROOT:+--root "$TG_ROOT"}'] : []),
    ...(report.canary?.length ? ["--canary", sh(report.canary.join(","))] : []),
    ...(report.terragrunt ? ["--terragrunt"] : []),
    ...(report.reports ? ["--bucket", sh(report.reports.bucket)] : []),
    ...(report.reports?.endpoint ? ["--bucket-endpoint", sh(report.reports.endpoint)] : []),
    ...(report.reports?.prefix ? ["--bucket-prefix", sh(report.reports.prefix)] : []),
    ...(report.reports?.url ? ["--bucket-url", sh(report.reports.url)] : []),
  ];
  return [
    "set -uo pipefail",
    forgeApi(forge),
    ...(replan ? [replanPrelude(layers, forge)] : []),
    ...(oidc ? [oidcScript(forge, oidc.plan_role, "terragucci-plan", oidc.audience)] : []),
    ...(report.terragrunt ? [report.terragrunt.prelude] : []),
    // A re-plan of one named root may find the change does not reach it, and then leaves the status as it was.
    replan ? '[ -n "${TG_ROOT:-}" ] || tg status terragucci/plan pending "planning"' : 'tg status terragucci/plan pending "planning"',
    `terragucci stage tf-plan ${args.join(" ")}`,
    "rc=$?",
    `if [ ! -f ${REPORT_DIR}/report.json ]; then`,
    '  tg status terragucci/plan failure "the plan report was not written"',
    "  exit 1",
    "fi",
    // A re-plan that names a root the change does not reach answers that, and leaves the plan note and the status as they are.
    ...(replan
      ? [
          `if [ -n "$TG_ROOT" ] && [ "$(node -e '${UNREACHED_JS}' ${REPORT_DIR}/report.json)" = yes ]; then`,
          '  tg reply "$TG_ROOT is not affected by this pull request, so nothing was planned."',
          '  exit 0',
          'fi',
        ]
      : []),
    `counts="$(node -e '${COUNTS_JS}' ${REPORT_DIR}/report.json)"`,
    'if [ -n "${TG_PR:-}" ]; then',
    ...(report.description ? [`  terragucci respond description --mode apply --report ${REPORT_DIR} || true`] : []),
    '  note="$(mktemp)"',
    "  # The first line says which roots the note covers, so an apply can mark it stale.",
    `  { echo "<!-- terragucci:plan roots=$(node -e '${PLANNED_JS}' ${REPORT_DIR}/report.json) -->"; cat ${REPORT_DIR}/note.md; } >"$note"`,
    '  tg note "$note"',
    "fi",
    'if [ "$rc" -ne 0 ]; then tg status terragucci/plan failure "$counts"; exit 1; fi',
    'tg status terragucci/plan success "$counts"',
  ].join("\n");
}

/** Reads the decision file `terragucci comment` wrote. */
const DECISION_JS = 'const d=JSON.parse(require("fs").readFileSync(process.argv[1],"utf-8"));console.log(d.go?[d.pr,d.sha,d.base,d.root||"-"].join(" "):"")';

/**
 * The re-plan job's first lines, before any credential is asked for. The
 * comment is read by `terragucci comment`, which writes a decision file; the
 * shell only reads four values from it (a number, a sha, a branch and a root,
 * each already checked against a pattern with no shell syntax), never the
 * comment. On Forgejo the command reads the commenter's permission from the
 * event, since the job's token may not ask the API for it. The job then checks
 * out the pull request's head: the event's sha is the default branch's, so the
 * head comes from the pull request, fetched by its number.
 */
function replanPrelude(layers: string[][], forge: ForgeName): string {
  return [
    `terragucci comment --layers ${sh(layers.map((l) => l.join(",")).join(";"))}${forge === "forgejo" ? " --forge forgejo" : ""} --out terragucci-comment.json || exit 1`,
    `read -r TG_PR TG_SHA TG_BASE TG_ROOT <<EOF`,
    `$(node -e '${DECISION_JS}' terragucci-comment.json)`,
    "EOF",
    '[ -n "$TG_PR" ] || exit 0',
    '[ "$TG_ROOT" = "-" ] && TG_ROOT=""',
    'export TG_PR TG_SHA TG_ROOT TG_BASE="origin/$TG_BASE"',
    'git fetch --quiet origin "refs/pull/$TG_PR/head" || { echo "terragucci: could not fetch the pull request head" >&2; exit 1; }',
    'if [ "$(git rev-parse FETCH_HEAD)" != "$TG_SHA" ]; then echo "terragucci: the pull request moved while the comment was read; its push plans it" >&2; exit 0; fi',
    'git checkout --quiet --detach "$TG_SHA"',
  ].join("\n");
}

/**
 * The publish job's script. It needs the whole history and the module tags
 * (publish reads the last release from them), and on GitLab a remote that can
 * push, since the job's checkout carries no write credentials.
 */
export function publishScript(forge: ForgeName): string {
  return [
    "set -eu",
    ...(forge === "gitlab"
      ? [
          'git remote set-url origin "https://oauth2:${TG_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git"',
          'git fetch --quiet --tags origin',
        ]
      : []),
    "terragucci publish",
  ].join("\n");
}

/**
 * The scheduled stage: `terragucci stage tf-drift` plans every root with
 * -refresh-only, writes the plan report, and keeps the drift issue. A root
 * that cannot be refreshed fails the job; drift alone does not.
 */
export function driftScript(binary: Binary, layers: string[][], forge: ForgeName = "github", oidc?: PipelineInput["oidc"], report: PlanReportInput = {}, pullRequest?: { tokenEnv?: string }): string {
  const args = [
    "--out", REPORT_DIR,
    "--binary", binary,
    "--forge", forge,
    "--layers", sh(layers.map((l) => l.join(",")).join(";")),
    "--report-url", reportUrl(forge),
    ...(report.terragrunt ? ["--terragrunt"] : []),
    ...(report.reports ? ["--bucket", sh(report.reports.bucket)] : []),
    ...(report.reports?.endpoint ? ["--bucket-endpoint", sh(report.reports.endpoint)] : []),
    ...(report.reports?.prefix ? ["--bucket-prefix", sh(report.reports.prefix)] : []),
    ...(report.reports?.url ? ["--bucket-url", sh(report.reports.url)] : []),
  ];
  return [
    "set -uo pipefail",
    // The stage keeps the issue itself; the forge calls here are only for the OIDC token.
    ...(oidc ? [forgeApi(forge), oidcScript(forge, oidc.plan_role, "terragucci-drift", oidc.audience)] : []),
    ...(report.terragrunt ? [report.terragrunt.prelude] : []),
    `terragucci stage tf-drift ${args.join(" ")}`,
    // The drift pull request: a person reviews and merges it, or closes it.
    ...(pullRequest
      ? ["rc=$?", ...respondSetup(forge, pullRequest.tokenEnv), `if [ "$rc" -eq 0 ]; then terragucci respond drift --mode apply --binary ${binary} || true; fi`, 'exit "$rc"']
      : []),
  ].join("\n");
}

function header(image: string): string {
  return [
    MARKER,
    "# terragucci writes this file from terragucci.yml, or from its defaults when",
    "# the repo has none. Change terragucci.yml and run `npx terragucci init`",
    "# rather than editing it here.",
    image.includes("@")
      ? `# Every job runs in ${image.split("@")[0]}, pinned by digest.`
      : `# Every job runs in ${image}; init pins its digest once the image is published.`,
    "",
  ].join("\n");
}

function text(result: string | { primary: string }): string {
  return typeof result === "string" ? result : result.primary;
}

export function renderPipeline(input: PipelineInput): RenderedPipeline {
  const { forge, binary, image, install, layers, env, oidc, tokenEnv, headersSecret } = input;
  const tg = input.terragrunt;
  const credentials = tg?.credentials && Object.keys(tg.credentials).length > 0 ? tg.credentials : undefined;
  // A job asks the forge for an OIDC token when it assumes a role, by oidc or by unit path.
  const needsToken = Boolean(oidc || credentials);
  // The canary wave comes from the repo's terragucci.yml at plan time, so a repo
  // with no config file gets the same pipeline as one whose config only sets waves.
  const report: PlanReportInput = {
    ...(input.reports ? { reports: input.reports } : {}),
    ...(responds(input.respond, "description") ? { description: true } : {}),
    ...(tg ? { terragrunt: { prelude: [cacheExports(), ...terragruntCredentials(forge, "plan", oidc, credentials)].join("\n") } } : {}),
  };
  const drift = input.drift;
  const roots = layers.flat().sort();
  if (roots.length === 0) throw new RenderError(tg ? "there are no Terragrunt units to run" : "there are no roots to run");
  const jobEnv = { TF_IN_AUTOMATION: "1", TF_INPUT: "0", ...(tg ? terragruntJobEnv(binary, tg) : {}), ...env };
  // Only the jobs that run a stage send telemetry (plan, apply, drift), so only they get the headers secret; check and publish never see it.
  const headersEnv = headersSecret ? { OTEL_EXPORTER_OTLP_HEADERS: forge === "gitlab" ? `$${headersSecret}` : `\${{ secrets.${headersSecret} }}` } : {};
  // The service's key reaches the jobs that ask it: the plan jobs for the description check, the drift job
  // when it attributes (plain roots only; a Terragrunt drift run does not attribute), and the version-bump job.
  const decideSecret = input.decideTokenEnv ? { [input.decideTokenEnv]: `\${{ secrets.${input.decideTokenEnv} }}` } : {};
  const decideEnv = responds(input.respond, "description") ? decideSecret : {};
  const driftDecideEnv = !tg && responseTo({ respond: input.respond }, "drift") === "attribute" ? decideSecret : {};
  const bumpOn = responds(input.respond, "version-bump");
  const installs = tg ? tg.installs : install ? [{ tool: install.binary as Tool | Binary, version: install.version }] : [];
  const installStep = installs.length > 0 ? installs.map((i) => installScript(i.tool, i.version, forge)).join("\n") : undefined;
  const installName = `Install ${installs.map((i) => `${i.tool} ${i.version}`).join(", ")}`;
  const audience = oidc?.audience ?? AUDIENCE;
  const checkBody = tg ? terragruntCheckScript(tg, binary) : checkScript(binary, roots);
  // Plain roots apply a wave per job, each behind its gate; a Terragrunt repo applies in one job.
  const gate = input.gate ?? "on-destroy";
  const waveCount = tg ? 1 : applyWaves(layers, input.canary).length;
  const applyJobs = Array.from({ length: waveCount }, (_, i) => ({
    name: tg ? "apply" : `apply-wave-${i + 1}`,
    body: tg ? terragruntApplyScript(layers, forge, oidc, credentials, input.respond) : applyScript(binary, layers, forge, oidc, { wave: i + 1, canary: input.canary, gate, respond: input.respond }),
  }));
  const lastApply = applyJobs[applyJobs.length - 1].name;
  // A wave that waits records its plan on the chant/lifecycle branch.
  const writesLedger = !tg && gate !== "never";
  const what = tg ? "unit" : "root";
  // The fmt commit and the drift pull request are for plain roots, where respond finds the roots itself.
  const fmtOn = !tg && responds(input.respond, "fmt");
  const driftPr = !tg && responds(input.respond, "drift") ? { tokenEnv } : undefined;
  // Tips are pull requests from the default branch, for plain roots and Terragrunt repos alike.
  const tipsOn = responds(input.respond, "tips");
  // An agent response writes its input file; the job keeps it as an artifact.
  const agentApply = responseTo({ respond: input.respond }, "apply-failed") === "agent";
  const agentDrift = !tg && responseTo({ respond: input.respond }, "drift") === "agent";

  if (forge === "gitlab") {
    const jobImage = new Image({ name: image });
    const script = (main: string): string[] => (installStep ? [installStep, main] : [main]);
    const bash = (tag: string, body: string): string => `bash <<'${tag}'\n${body}\n${tag}`;
    const gitlabEnv = {
      ...jobEnv,
      ...headersEnv,
      TG_TOKEN: `$${tokenEnv ?? "GITLAB_TOKEN"}`,
      TG_SHA: "$CI_COMMIT_SHA",
      TG_BRANCH: "$CI_DEFAULT_BRANCH",
    };
    const idTokens = needsToken ? { id_tokens: { TERRAGUCCI_OIDC: { aud: audience } } } : {};
    const notScheduled = drift ? { rules: [new Rule({ if: '$CI_PIPELINE_SOURCE != "schedule"' })] } : {};
    const check = new GitLabJob({
      stage: "check",
      image: jobImage,
      variables: fmtOn ? { ...jobEnv, TG_TOKEN: gitlabEnv.TG_TOKEN } : jobEnv,
      ...notScheduled,
      script: script(checkBody),
      // After a failing check on a branch, commit the formatting; the job's own result stands.
      ...(fmtOn
        ? { after_script: [...(installStep ? [installStep] : []), bash("FMT", `if [ "$CI_JOB_STATUS" = failed ] && [ -n "$CI_COMMIT_BRANCH" ] && [ "$CI_COMMIT_BRANCH" != "$CI_DEFAULT_BRANCH" ]; then\n${fmtScript(binary, forge, tokenEnv)}\nfi`)] }
        : {}),
    } as never);
    // Plan runs a merge request's code, so it gets the read-only role, and never
    // runs for a merge request from a fork.
    const plan = new GitLabJob({
      stage: "plan",
      image: jobImage,
      variables: { ...gitlabEnv, TG_PR: "$CI_MERGE_REQUEST_IID", GIT_DEPTH: "0" },
      rules: [new Rule({ if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_SOURCE_PROJECT_PATH == $CI_PROJECT_PATH' })],
      ...idTokens,
      ...(tg ? forgeCache("gitlab") : {}),
      script: script(bash("PLAN", planScript(binary, layers, forge, oidc, report))),
      // The report stays with the job; its counts feed the merge request's widget.
      artifacts: { name: REPORT_DIR, when: "always", paths: [`${REPORT_DIR}/`], reports: { terraform: `${REPORT_DIR}/gitlab-terraform.json` } },
    } as never);
    const jobs = new Map<string, never>([["check", check as never], ["plan", plan as never]]);
    for (const [i, job] of applyJobs.entries()) {
      jobs.set(job.name, new GitLabJob({
        stage: "apply",
        image: jobImage,
        ...(i > 0 ? { needs: [applyJobs[i - 1].name] } : {}),
        variables: { ...gitlabEnv, TG_BEFORE: "$CI_COMMIT_BEFORE_SHA" },
        rules: [new Rule({ if: drift ? '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE != "schedule"' : "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH" })],
        resource_group: "terragucci-apply",
        ...idTokens,
        ...(tg ? forgeCache("gitlab") : {}),
        script: script(bash("APPLY", job.body)),
        // The wave's report stays with the job, like the plan's; the agent's input joins it when there is one.
        artifacts: { name: `${REPORT_DIR}-${job.name}`, when: "always", paths: [`${REPORT_DIR}/`, ...(agentApply ? [`${RESPOND_DIR}/`] : [])] },
      } as never) as never);
    }
    if (tipsOn) {
      // Runs after the last apply, so a wave that waits or fails holds the tips back too.
      jobs.set("tips", new GitLabJob({
        stage: "tips",
        image: jobImage,
        needs: [lastApply],
        variables: { ...gitlabEnv, GIT_DEPTH: "0" },
        rules: [new Rule({ if: drift ? '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE != "schedule"' : "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH" })],
        resource_group: "terragucci-tips",
        script: script(bash("TIPS", tipsScript(binary, forge, tokenEnv))),
      } as never) as never);
    }
    if (bumpOn) {
      // Runs after the last apply, from the default branch, with the history and tags the commits are counted from.
      jobs.set("version-bump", new GitLabJob({
        stage: "version-bump",
        image: jobImage,
        needs: [lastApply],
        variables: { ...gitlabEnv, GIT_DEPTH: "0" },
        rules: [new Rule({ if: drift ? '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE != "schedule"' : "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH" })],
        resource_group: "terragucci-version-bump",
        script: [bash("BUMP", versionBumpScript(forge, tokenEnv))],
      } as never) as never);
    }
    if (input.publish) {
      // GitLab hands project variables (TERRAGUCCI_REGISTRY_USER and _PASSWORD)
      // to every job, so mark them protected and masked to keep them off merge requests.
      jobs.set("publish", new GitLabJob({
        stage: "publish",
        image: jobImage,
        needs: [lastApply],
        variables: { ...jobEnv, TG_TOKEN: gitlabEnv.TG_TOKEN, TG_SHA: gitlabEnv.TG_SHA, TG_BRANCH: gitlabEnv.TG_BRANCH, GIT_DEPTH: "0" },
        rules: [new Rule({ if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH" })],
        resource_group: "terragucci-publish",
        script: script(bash("PUBLISH", publishScript(forge))),
      } as never) as never);
    }
    if (drift) {
      jobs.set("drift", new GitLabJob({
        stage: "drift",
        image: jobImage,
        variables: gitlabEnv,
        rules: [new Rule({ if: '$CI_PIPELINE_SOURCE == "schedule"' })],
        ...idTokens,
        ...(tg ? forgeCache("gitlab") : {}),
        script: script(bash("DRIFT", driftScript(binary, layers, forge, oidc, report, driftPr))),
        artifacts: { name: `${REPORT_DIR}-drift`, when: "always", paths: [`${REPORT_DIR}/`, ...(agentDrift ? [`${RESPOND_DIR}/`] : [])] },
      } as never) as never);
    }
    const out = text(gitlabSerializer.serialize(jobs));
    return { path: PIPELINE_PATHS.gitlab, content: header(image) + out };
  }

  const sameRepo = "github.event.pull_request.head.repo.full_name == github.repository";
  const isFork = "github.event.pull_request.head.repo.full_name != github.repository";
  // Forgejo (15 and later, with runner 12.5 or later) serves a job an OIDC token
  // only when the job sets enable-openid-connect; it does not read id-token: write.
  const openid = (on: boolean): Record<string, boolean> => (on && forge === "forgejo" ? { "enable-openid-connect": true } : {});
  const workflow = new Workflow({
    name: "terragucci",
    on: {
      push: { branches: ["**"] },
      pull_request: {},
      // `/terragucci plan [root]` in a pull request comment re-plans it; see comment.ts.
      issue_comment: { types: ["created"] },
      ...(drift ? { schedule: [{ cron: drift }], workflow_dispatch: {} } : {}),
    },
    env: jobEnv,
    permissions: { contents: "read" },
    // Forgejo cancels the runs of an earlier push to a branch, even one that is
    // applying, unless the workflow names a concurrency group. A group that does
    // not cancel makes a later run wait instead.
    ...(forge === "forgejo" ? { concurrency: { group: "terragucci-${{ github.event_name == 'issue_comment' && format('comment-{0}', github.event.issue.number) || github.ref }}", "cancel-in-progress": false } } : {}),
  } as never);
  // A plan reads the range from the target branch, so its checkout has the history.
  const steps = (main: InstanceType<typeof Step>, cached = false, history = false): InstanceType<typeof Step>[] => [
    new Step({ uses: "actions/checkout@v4", ...(history ? { with: { "fetch-depth": 0 } } : {}) }),
    ...(installStep ? [new Step({ name: installName, run: installStep })] : []),
    ...(cached && tg ? [new Step({ name: "Cache Terragrunt sources and providers", ...forgeCache(forge) } as never)] : []),
    main,
  ];
  // Check runs for a push, and for a fork's pull request, which has no push here.
  const check = new Job({
    "runs-on": "ubuntu-latest",
    container: { image },
    if: `github.event_name == 'push' || (github.event_name == 'pull_request' && ${isFork})`,
    ...(fmtOn ? { permissions: { contents: "write" }, env: { TG_TOKEN: "${{ github.token }}" } } : {}),
    steps: [
      ...steps(new Step({ name: `Format check and validate, every ${what}`, run: checkBody })),
      // After a failing check on a branch, commit the formatting to it; a fork's pull request has no push here.
      ...(fmtOn
        ? [new Step({
            name: "Commit the formatting",
            if: "failure() && github.event_name == 'push' && github.ref != format('refs/heads/{0}', github.event.repository.default_branch)",
            shell: "bash",
            run: fmtScript(binary, forge, tokenEnv),
          })]
        : []),
    ],
  } as never);
  // Plan runs a pull request's code, so it gets the read-only role, and never
  // runs for a fork, whose pull requests carry no token and no OIDC.
  const plan = new Job({
    "runs-on": "ubuntu-latest",
    container: { image },
    if: `github.event_name == 'pull_request' && ${sameRepo}`,
    permissions: { contents: "read", statuses: "write", "pull-requests": "write", ...(needsToken ? { "id-token": "write" } : {}) },
    ...openid(needsToken),
    env: {
      TG_TOKEN: "${{ github.token }}",
      TG_SHA: "${{ github.event.pull_request.head.sha }}",
      TG_PR: "${{ github.event.pull_request.number }}",
      ...headersEnv,
      ...decideEnv,
    },
    steps: [
      ...steps(new Step({ name: `Plan the ${what}s the change reaches and write the plan report`, shell: "bash", run: planScript(binary, layers, forge, oidc, report) }), true, true),
      // The report stays with the run. Forgejo's artifact store speaks the v3 protocol.
      new Step({
        name: "Keep the plan report",
        if: "always()",
        uses: forge === "forgejo" ? "actions/upload-artifact@v3" : "actions/upload-artifact@v4",
        with: { name: REPORT_DIR, path: `${REPORT_DIR}/`, "if-no-files-found": "ignore" },
      }),
    ],
  } as never);
  // A comment re-plans a pull request of this repository for someone who can write to it. The comment is
  // never an expression in the script: the command reads it from the event file (comment.ts).
  const replan = new Job({
    "runs-on": "ubuntu-latest",
    container: { image },
    if: "github.event_name == 'issue_comment' && startsWith(github.event.comment.body, '/terragucci')",
    permissions: { contents: "read", statuses: "write", "pull-requests": "write", ...(needsToken ? { "id-token": "write" } : {}) },
    ...openid(needsToken),
    concurrency: { group: "terragucci-replan-${{ github.repository }}-${{ github.event.issue.number }}", "cancel-in-progress": false },
    env: { TG_TOKEN: "${{ github.token }}", ...headersEnv, ...decideEnv },
    steps: [
      ...steps(new Step({ name: `Re-plan the pull request on request and write the plan report`, shell: "bash", run: planScript(binary, layers, forge, oidc, report, true) }), true, true),
      new Step({
        name: "Keep the plan report",
        if: "always()",
        uses: forge === "forgejo" ? "actions/upload-artifact@v3" : "actions/upload-artifact@v4",
        with: { name: `${REPORT_DIR}-replan`, path: `${REPORT_DIR}/`, "if-no-files-found": "ignore" },
      }),
    ],
  } as never);
  const entities = new Map<string, never>([
    ["workflow", workflow as never],
    ["check", check as never],
    ["plan", plan as never],
    ["replan", replan as never],
  ]);
  for (const [i, job] of applyJobs.entries()) {
    entities.set(job.name, new Job({
      "runs-on": "ubuntu-latest",
      container: { image },
      // Each wave needs the one before, so a wave that waits holds back every later one.
      needs: i === 0 ? "check" : applyJobs[i - 1].name,
      if: `${drift ? "github.event_name == 'push' && " : ""}github.ref == format('refs/heads/{0}', github.event.repository.default_branch)`,
      // contents: write only to record a waiting wave's plan on the chant/lifecycle branch.
      permissions: { contents: writesLedger ? "write" : "read", statuses: "write", "pull-requests": "write", ...(needsToken ? { "id-token": "write" } : {}) },
      ...openid(needsToken),
      // One apply per project at a time; a push that waits is not cancelled.
      concurrency: { group: "terragucci-apply-${{ github.repository }}", "cancel-in-progress": false },
      env: {
        TG_TOKEN: "${{ github.token }}",
        TG_SHA: "${{ github.sha }}",
        TG_BEFORE: "${{ github.event.before }}",
        TG_BRANCH: "${{ github.event.repository.default_branch }}",
        ...headersEnv,
      },
      steps: [
        ...steps(new Step({ name: tg ? `Apply every ${what}` : `Apply wave ${i + 1} of ${waveCount}`, shell: "bash", run: job.body }), true),
        new Step({ name: "Keep the apply report", if: "always()", uses: forge === "forgejo" ? "actions/upload-artifact@v3" : "actions/upload-artifact@v4", with: { name: `${REPORT_DIR}-${job.name}`, path: `${REPORT_DIR}/`, "if-no-files-found": "ignore" } }),
        ...(agentApply
          ? [new Step({ name: "Keep the agent input", if: "failure()", uses: forge === "forgejo" ? "actions/upload-artifact@v3" : "actions/upload-artifact@v4", with: { name: `${RESPOND_DIR}-${job.name}`, path: `${RESPOND_DIR}/`, "if-no-files-found": "ignore" } })]
          : []),
      ],
    } as never) as never);
  }
  if (tipsOn) {
    // One small pull request per tip, from the default branch once every wave has applied.
    entities.set("tips", new Job({
      "runs-on": "ubuntu-latest",
      container: { image },
      needs: lastApply,
      if: `${drift ? "github.event_name == 'push' && " : ""}github.ref == format('refs/heads/{0}', github.event.repository.default_branch)`,
      permissions: { contents: "write", "pull-requests": "write" },
      concurrency: { group: "terragucci-tips-${{ github.repository }}", "cancel-in-progress": false },
      env: { TG_TOKEN: "${{ github.token }}" },
      steps: [
        new Step({ uses: "actions/checkout@v4", with: { "fetch-depth": 0 } }),
        ...(installStep ? [new Step({ name: installName, run: installStep })] : []),
        new Step({ name: "Open a pull request for each tip", shell: "bash", run: tipsScript(binary, forge, tokenEnv) }),
      ],
    } as never) as never);
  }
  if (bumpOn) {
    // A release pull request per module the commits do not settle, from the default branch once every wave has applied.
    entities.set("version-bump", new Job({
      "runs-on": "ubuntu-latest",
      container: { image },
      needs: lastApply,
      if: `${drift ? "github.event_name == 'push' && " : ""}github.ref == format('refs/heads/{0}', github.event.repository.default_branch)`,
      permissions: { contents: "write", "pull-requests": "write" },
      concurrency: { group: "terragucci-version-bump-${{ github.repository }}", "cancel-in-progress": false },
      env: { TG_TOKEN: "${{ github.token }}", ...decideSecret },
      steps: [
        new Step({ uses: "actions/checkout@v4", with: { "fetch-depth": 0 } }),
        new Step({ name: "Suggest the next version of each module that changed", shell: "bash", run: versionBumpScript(forge, tokenEnv) }),
      ],
    } as never) as never);
  }
  if (input.publish) {
    // The only job that sees the registry credentials. It pushes tags, so it is
    // the only one with write access to contents, and it runs after apply.
    entities.set("publish", new Job({
      "runs-on": "ubuntu-latest",
      container: { image },
      needs: lastApply,
      if: "github.ref == format('refs/heads/{0}', github.event.repository.default_branch)",
      permissions: { contents: "write" },
      concurrency: { group: "terragucci-publish-${{ github.repository }}", "cancel-in-progress": false },
      env: {
        TERRAGUCCI_REGISTRY_USER: "${{ secrets.TERRAGUCCI_REGISTRY_USER }}",
        TERRAGUCCI_REGISTRY_PASSWORD: "${{ secrets.TERRAGUCCI_REGISTRY_PASSWORD }}",
      },
      steps: [
        new Step({ uses: "actions/checkout@v4", with: { "fetch-depth": 0 } }),
        ...(installStep && install ? [new Step({ name: `Install ${install.binary} ${install.version}`, run: installStep })] : []),
        new Step({ name: "Publish the modules that changed", shell: "bash", run: publishScript(forge) }),
      ],
    } as never) as never);
  }
  if (drift) {
    // Reads every root, so it takes the plan job's read-only role, and writes only the issue.
    entities.set("drift", new Job({
      "runs-on": "ubuntu-latest",
      container: { image },
      if: "github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'",
      permissions: { contents: driftPr ? "write" : "read", issues: "write", ...(driftPr ? { "pull-requests": "write" } : {}), ...(oidc ? { "id-token": "write" } : {}) },
      ...openid(Boolean(oidc)),
      env: {
        TG_TOKEN: "${{ github.token }}",
        TG_SHA: "${{ github.sha }}",
        ...headersEnv,
        ...driftDecideEnv,
      },
      steps: [
        ...steps(new Step({ name: `Plan every ${what} against what exists, and keep the drift issue`, shell: "bash", run: driftScript(binary, layers, forge, oidc, report, driftPr) }), true),
        new Step({
          name: "Keep the drift report",
          if: "always()",
          uses: forge === "forgejo" ? "actions/upload-artifact@v3" : "actions/upload-artifact@v4",
          with: { name: `${REPORT_DIR}-drift`, path: `${REPORT_DIR}/`, "if-no-files-found": "ignore" },
        }),
        ...(agentDrift
          ? [new Step({ name: "Keep the agent input", if: "always()", uses: forge === "forgejo" ? "actions/upload-artifact@v3" : "actions/upload-artifact@v4", with: { name: `${RESPOND_DIR}-drift`, path: `${RESPOND_DIR}/`, "if-no-files-found": "ignore" } })]
          : []),
      ],
    } as never) as never);
  }
  const serializer = forge === "forgejo" ? forgejoSerializer : githubSerializer;
  return { path: PIPELINE_PATHS[forge], content: header(image) + text(serializer.serialize(entities)) };
}
