/**
 * The pipeline terragucci writes into a repo, rendered through chant's forge
 * lexicons so GitHub, Forgejo and GitLab get the same jobs in their own syntax.
 *
 * check  every push: format check and validate, for every root.
 * apply  pushes to the default branch: apply every root, a layer at a time,
 *        roots in one layer together. A root that reads another's state
 *        applies after it.
 *
 * The stages terragucci is building (grouped plans, gated waves, drift) take
 * these jobs' place as they ship; the file stays where it is.
 */
// Each lexicon's serializer and generated entities, never its entry point: the
// entry points carry lint rules, codegen and the TypeScript compiler, which the
// bundle must not (chant#3421).
import { Job, Step, Workflow } from "@intentius/chant-lexicon-github/generated/index";
import { githubSerializer } from "@intentius/chant-lexicon-github/serializer";
import { applyForgejoDialect } from "@intentius/chant-lexicon-forgejo/dialect";
import { Image, Job as GitLabJob, Rule } from "@intentius/chant-lexicon-gitlab/generated/index";
import { gitlabSerializer } from "@intentius/chant-lexicon-gitlab/serializer";

/** Forgejo is the github dialect with Forgejo's runner labels and action refs. */
const forgejoSerializer = {
  serialize(entities: Map<string, never>): ReturnType<typeof githubSerializer.serialize> {
    return githubSerializer.serialize(applyForgejoDialect(entities as never, {}).entities as never);
  },
};
import type { Binary, ForgeName } from "./config";

export const MARKER = "# Generated by terragucci.";

export const PIPELINE_PATHS: Record<ForgeName, string> = {
  github: ".github/workflows/terragucci.yml",
  forgejo: ".forgejo/workflows/terragucci.yml",
  gitlab: ".gitlab-ci.yml",
};

export interface PipelineInput {
  forge: ForgeName;
  binary: Binary;
  version: string;
  /** The job image, as a pipeline names it (tag, and digest once published). */
  image: string;
  /** Set when the repo pins a version the image does not carry: the job installs it. */
  install?: { binary: Binary; version: string };
  /** Roots in apply order: each inner list applies together. */
  layers: string[][];
  env: Record<string, string>;
}

export interface RenderedPipeline {
  path: string;
  content: string;
}

export class RenderError extends Error {}

const sh = (s: string): string => `'${s.replace(/'/g, `'\\''`)}'`;

/** The step that puts a pinned version the image does not carry on the path. */
export function installScript(binary: Binary, version: string, forge: ForgeName): string {
  const dir = `dir="$(terragucci install ${binary} ${version})"`;
  return forge === "gitlab" ? `${dir}\nexport PATH="$dir:$PATH"` : `${dir}\necho "$dir" >> "$GITHUB_PATH"`;
}

export function checkScript(binary: Binary, roots: string[]): string {
  return [
    "set -eu",
    `${binary} fmt -check -recursive -diff .`,
    `for dir in ${roots.map(sh).join(" ")}; do`,
    `  ${binary} -chdir="$dir" init -backend=false -input=false -no-color >/dev/null`,
    `  ${binary} -chdir="$dir" validate -no-color >/dev/null`,
    '  echo "valid $dir"',
    "done",
  ].join("\n");
}

export function applyScript(binary: Binary, layers: string[][]): string {
  return [
    "set -uo pipefail",
    "# Each root's output goes to its own log, printed when the root is done.",
    "apply_root() {",
    '  local dir="$1" log',
    '  log="$(mktemp)"',
    `  if ${binary} -chdir="$dir" init -input=false -no-color >"$log" 2>&1 &&`,
    `    ${binary} -chdir="$dir" apply -auto-approve -input=false -no-color >>"$log" 2>&1; then`,
    `    echo "applied $dir: $(grep -o 'Resources: .*destroyed' "$log" | tail -1)"`,
    "  else",
    '    echo "FAILED $dir"',
    "    sed 's/^/    /' \"$log\"",
    '    rm -f "$log"',
    "    return 1",
    "  fi",
    '  rm -f "$log"',
    "}",
    "apply_together() {",
    "  local pids=() rc=0",
    '  for dir in "$@"; do apply_root "$dir" & pids+=("$!"); done',
    '  for pid in "${pids[@]}"; do wait "$pid" || rc=1; done',
    "  return $rc",
    "}",
    ...layers.map((layer) => `apply_together ${layer.map(sh).join(" ")} || exit 1`),
    'echo "all roots applied"',
  ].join("\n");
}

function header(image: string): string {
  return [
    MARKER,
    "# terragucci writes this file from terragucci.yml, or from its defaults when",
    "# the repo has none. Change terragucci.yml and run `npx terragucci init`",
    "# rather than editing it here.",
    image.includes("@")
      ? `# Every job runs in ${image.split("@")[0]}, pinned by digest.`
      : `# Every job runs in ${image}; init pins its digest once the image is published.`,
    "",
  ].join("\n");
}

function text(result: string | { primary: string }): string {
  return typeof result === "string" ? result : result.primary;
}

export function renderPipeline(input: PipelineInput): RenderedPipeline {
  const { forge, binary, image, install, layers, env } = input;
  const roots = layers.flat().sort();
  if (roots.length === 0) throw new RenderError("there are no roots to run");
  const jobEnv = { TF_IN_AUTOMATION: "1", TF_INPUT: "0", ...env };
  const installStep = install ? installScript(install.binary, install.version, forge) : undefined;

  if (forge === "gitlab") {
    const jobImage = new Image({ name: image });
    const script = (main: string): string[] => (installStep ? [installStep, main] : [main]);
    const check = new GitLabJob({ stage: "check", image: jobImage, variables: jobEnv, script: script(checkScript(binary, roots)) });
    const apply = new GitLabJob({
      stage: "apply",
      image: jobImage,
      variables: jobEnv,
      rules: [new Rule({ if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH" })],
      script: script(`bash <<'APPLY'\n${applyScript(binary, layers)}\nAPPLY`),
    });
    const out = text(gitlabSerializer.serialize(new Map<string, never>([["check", check as never], ["apply", apply as never]])));
    return { path: PIPELINE_PATHS.gitlab, content: header(image) + out };
  }

  const workflow = new Workflow({ name: "terragucci", on: { push: { branches: ["**"] } }, env: jobEnv });
  const steps = (main: InstanceType<typeof Step>): InstanceType<typeof Step>[] => [
    new Step({ uses: "actions/checkout@v4" }),
    ...(installStep && install ? [new Step({ name: `Install ${install.binary} ${install.version}`, run: installStep })] : []),
    main,
  ];
  const check = new Job({
    "runs-on": "ubuntu-latest",
    container: { image },
    steps: steps(new Step({ name: "Format check and validate, every root", run: checkScript(binary, roots) })),
  });
  const apply = new Job({
    "runs-on": "ubuntu-latest",
    container: { image },
    needs: "check",
    if: "github.ref == format('refs/heads/{0}', github.event.repository.default_branch)",
    steps: steps(new Step({ name: "Apply every root", shell: "bash", run: applyScript(binary, layers) })),
  });
  const entities = new Map<string, never>([["workflow", workflow as never], ["check", check as never], ["apply", apply as never]]);
  const serializer = forge === "forgejo" ? forgejoSerializer : githubSerializer;
  return { path: PIPELINE_PATHS[forge], content: header(image) + text(serializer.serialize(entities)) };
}
