/**
 * Terragrunt's explicit stacks (`terragrunt.stack.hcl`): the one place that
 * knows a stack's units are generated, where they are, which stack file
 * generates each, and how to generate them before they are read. Plain
 * Terragrunt units are ./terragrunt.ts's.
 *
 *   prepare      generateStacks, ensureGenerated
 *   discover     explicitStackUnits (from the stack files, before Terragrunt runs)
 *   edit target  generatingStack, stackFile: a generated unit is changed in its stack file or template
 *   report       stackOfUnit, unitStack
 */
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { findTerragruntStackFiles, readTerragruntStackFile } from "@intentius/chant-lexicon-terraform/terragrunt/affected";
import { checkTerragruntVersion, type TerragruntExec } from "@intentius/chant-lexicon-terraform/terragrunt/run";
import { stackOfUnit as parentOfUnit } from "@intentius/chant-lexicon-terraform/terragrunt/units";
import { terragruntExec } from "./binary-env";
import { ConfigError } from "./config";

/** Where `terragrunt stack generate` writes a stack's units, beside its `terragrunt.stack.hcl`. */
export const STACK_DIR = ".terragrunt-stack";

const posix = (p: string): string => p.split("\\").join("/");

/** The directories holding a `terragrunt.stack.hcl` the repo keeps (not one a stack generated), sorted. */
export function stackDirs(repo: string): string[] {
  return findTerragruntStackFiles(repo)
    .filter((f) => !f.split("/").includes(STACK_DIR))
    .map((f) => (f.includes("/") ? f.slice(0, f.lastIndexOf("/")) : "."))
    .sort();
}

/**
 * The explicit stack that generates `unit`: the directory holding its
 * `terragrunt.stack.hcl`, or undefined for a unit the repo holds itself.
 */
export function generatingStack(unit: string): string | undefined {
  const p = posix(unit);
  if (p.startsWith(`${STACK_DIR}/`)) return ".";
  const i = p.lastIndexOf(`/${STACK_DIR}/`);
  return i < 0 ? undefined : p.slice(0, i);
}

/** The `terragrunt.stack.hcl` of the stack in directory `stack`. */
export function stackFile(stack: string): string {
  return stack === "." ? "terragrunt.stack.hcl" : `${stack}/terragrunt.stack.hcl`;
}

/** A unit's stack: the explicit stack that generates it, else its parent directory (an implicit stack). */
export function stackOfUnit(unit: string): string {
  return generatingStack(unit) ?? parentOfUnit(unit);
}

/** A unit's stack as the report gives it: the stack, and the stack file when an explicit stack generates the unit. */
export function unitStack(unit: string): { stack: string; stack_file?: string } {
  const g = generatingStack(unit);
  return g === undefined ? { stack: parentOfUnit(unit) } : { stack: g, stack_file: stackFile(g) };
}

/**
 * Generate the units of the repo's explicit stacks (`terragrunt.stack.hcl`)
 * with `terragrunt stack generate`, so discovery and the waves see them under
 * each stack's `.terragrunt-stack/`. Nothing to do in a repo with no stack.
 * Only Terragrunt can generate a stack's units, so a repo with stacks needs
 * Terragrunt 1.1 or later: without it this throws, rather than leave the
 * stacks' units out.
 */
export async function generateStacks(repo: string, options: { terragrunt?: string; binary?: string; exec?: TerragruntExec } = {}): Promise<string[]> {
  const stacks = stackDirs(repo);
  if (stacks.length === 0) return [];
  const terragrunt = options.terragrunt ?? process.env.TERRAGUCCI_TERRAGRUNT ?? "terragrunt";
  const exec = options.exec ?? terragruntExec;
  const run = { dir: repo, terragrunt, ...(options.binary ? { binary: options.binary } : {}), exec };
  try {
    await checkTerragruntVersion(run);
  } catch (e) {
    throw new ConfigError(`${stacks.map(stackFile).join(", ")}: an explicit stack's units are generated by terragrunt stack generate, and Terragrunt did not run (${(e as Error).message.split("\n")[0]}); put Terragrunt 1.1 or later on the path, or set TERRAGUCCI_TERRAGRUNT`);
  }
  const out = await exec(terragrunt, ["stack", "generate", "--non-interactive", "--no-color"], { cwd: repo, env: { TG_NON_INTERACTIVE: "true", ...(options.binary ? { TG_TF_PATH: options.binary } : {}) } });
  if (out.code !== 0) throw new ConfigError(`terragrunt stack generate failed (exit ${out.code}):\n${(out.stderr || out.stdout).trim().split("\n").slice(-20).join("\n")}`);
  return stacks;
}

/**
 * Generate the repo's explicit stacks when any of `units` is one of their
 * units and is not generated yet, so it can be prepared where it runs.
 */
export async function ensureGenerated(repo: string, units: readonly string[], options: { terragrunt?: string; binary?: string; exec?: TerragruntExec } = {}): Promise<void> {
  if (units.some((u) => generatingStack(u) !== undefined && !existsSync(join(repo, u, "terragrunt.hcl")))) await generateStacks(repo, options);
}

/**
 * The units a repo's explicit stacks generate, read from each
 * `terragrunt.stack.hcl` without running Terragrunt, so generate keys them in
 * terragucci.hcl before they exist. Each with the template it is copied from
 * when that is in the repo. A `stack` block nests a stack whose units only
 * Terragrunt can list, so it is refused.
 */
export function explicitStackUnits(repo: string, stacks: readonly string[]): { unit: string; file: string; name: string; template?: string }[] {
  const out: { unit: string; file: string; name: string; template?: string }[] = [];
  for (const stack of stacks) {
    const file = stackFile(stack);
    const text = readFileSync(join(repo, file), "utf-8");
    for (const b of readTerragruntStackFile(repo, file, text)) {
      // A source under ${get_repo_root()} is in the repo too.
      if (b.template === undefined) {
        const at = new RegExp(`\\b${b.type}\\s+"${b.name.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}"\\s*\\{`).exec(text);
        const rest = at ? text.slice(at.index + at[0].length) : "";
        const next = rest.search(/^\s*(unit|stack)\s+"/m);
        const src = at ? /^\s*source\s*=\s*"\$\{get_repo_root\(\)\}\/([^"$]*)"/m.exec(next < 0 ? rest : rest.slice(0, next)) : null;
        if (src) b.template = src[1].replace("//", "/").replace(/\/+$/, "");
      }
      if (b.type === "stack") throw new ConfigError(`${file}: stack "${b.name}" nests a stack, and generate reads the units a stack file names in its unit blocks; only Terragrunt can list a nested stack's units, so give each unit its own unit block, or leave generate unset`);
      out.push({ unit: b.generated, file, name: b.name, ...(b.template !== undefined ? { template: b.template } : {}) });
    }
  }
  return out;
}
